services: 
  disbot:
    image: ghcr.io/disbotdevelopment/disbot-bot:latest
    container_name: disbot-bot
    environment:
      MONGODBURL: "mongodb://<user>:<pw>@disbot-database:27017/disbot-beta-db?authSource=admin"
    volumes:
      - "/docker/disbot-bot/config.yml:/bot/config.yml"
      # Config will be generated if the config.yml is a FILE! 
  disbot-database:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=<hostname>
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=YOUR !PASSWORD!
      - MONGODB_REPLICA_SET_KEY=disbotrep
    # ports:
    #   - '27017:27017'
    volumes:
      - '/docker/disbot-db:/bitnami/mongodb'