services:
  disbot-bot:
    image: ghcr.io/disbotdevelopment/disbot-bot:v2
    container_name: disbot-bot
    env_file:
      - .env
    environment:
      - "BOT__DiscordApplicationToken=${DISCORD_APPLICATION_TOKEN}"
      - "BOT__DiscordAdminGuildId=${DISCORD_ADMIN_GUILD_ID}"
      - "BOT__DiscordApplicationId=${DISCORD_APPLICATION_ID}"
      - "LOGGING__ErrorReportForumTags=${LOGGING_REPORT_FORUM_TAGS}"
      - "LOGGING__ErrorReportForumId=${LOGGING_REPORT_FORUM_ID}"
      - "LOGGING__GitHubApiToken=${LOGGING_GITHUB_API_KEY}"
      - "DATABASE__Host=${DATABASE_HOST}"
      - "DATABASE__Port=${DATABASE_PORT}"
      - "DATABASE__Username=${DATABASE_USERNAME}"
      - "DATABASE__Password=${DATABASE_PASSWORD}"
      - "DATABASE__Database=${DATABASE_DATABASE_NAME}"
    depends_on:
      - database
  disbot-api:
    image: ghcr.io/disbotdevelopment/disbot-api:v2
    container_name: disbot-api
    environment:
      - "DATABASE__Host=${DATABASE_HOST}"
      - "DATABASE__Port=${DATABASE_PORT}"
      - "DATABASE__Username=${DATABASE_USERNAME}"
      - "DATABASE__Password=${DATABASE_PASSWORD}"
      - "DATABASE__Database=${DATABASE_DATABASE_NAME}"
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "8181:8080"
  disbot-dashboard:
    image: ghcr.io/disbotdevelopment/disbot-dashboard:v2
    container_name: disbot-dash
    environment:
      - "BACKEND__ApiUrl=${FRONTEND_API_URL}"
    env_file:
      - .env
    ports:
      - "8080:8080"
  database:
    image: postgres
    container_name: disbot-database
    env_file:
      - .env
    environment:
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
    ports:
      - "2343:5432"