
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BuildInCommands` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model BuildInCommands
 * 
 */
export type BuildInCommandsModel = runtime.Types.Result.DefaultSelection<Prisma.$BuildInCommandsPayload>

export type AggregateBuildInCommands = {
  _count: BuildInCommandsCountAggregateOutputType | null
  _avg: BuildInCommandsAvgAggregateOutputType | null
  _sum: BuildInCommandsSumAggregateOutputType | null
  _min: BuildInCommandsMinAggregateOutputType | null
  _max: BuildInCommandsMaxAggregateOutputType | null
}

export type BuildInCommandsAvgAggregateOutputType = {
  Id: number | null
}

export type BuildInCommandsSumAggregateOutputType = {
  Id: number | null
}

export type BuildInCommandsMinAggregateOutputType = {
  Id: number | null
  UUID: string | null
  CustomName: string | null
  Description: string | null
  Permissions: string | null
  IsEnabled: boolean | null
  CodeName: string | null
  GuildCommandMangerId: string | null
}

export type BuildInCommandsMaxAggregateOutputType = {
  Id: number | null
  UUID: string | null
  CustomName: string | null
  Description: string | null
  Permissions: string | null
  IsEnabled: boolean | null
  CodeName: string | null
  GuildCommandMangerId: string | null
}

export type BuildInCommandsCountAggregateOutputType = {
  Id: number
  UUID: number
  CustomName: number
  Description: number
  Permissions: number
  IsEnabled: number
  CodeName: number
  GuildCommandMangerId: number
  _all: number
}


export type BuildInCommandsAvgAggregateInputType = {
  Id?: true
}

export type BuildInCommandsSumAggregateInputType = {
  Id?: true
}

export type BuildInCommandsMinAggregateInputType = {
  Id?: true
  UUID?: true
  CustomName?: true
  Description?: true
  Permissions?: true
  IsEnabled?: true
  CodeName?: true
  GuildCommandMangerId?: true
}

export type BuildInCommandsMaxAggregateInputType = {
  Id?: true
  UUID?: true
  CustomName?: true
  Description?: true
  Permissions?: true
  IsEnabled?: true
  CodeName?: true
  GuildCommandMangerId?: true
}

export type BuildInCommandsCountAggregateInputType = {
  Id?: true
  UUID?: true
  CustomName?: true
  Description?: true
  Permissions?: true
  IsEnabled?: true
  CodeName?: true
  GuildCommandMangerId?: true
  _all?: true
}

export type BuildInCommandsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BuildInCommands to aggregate.
   */
  where?: Prisma.BuildInCommandsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuildInCommands to fetch.
   */
  orderBy?: Prisma.BuildInCommandsOrderByWithRelationInput | Prisma.BuildInCommandsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BuildInCommandsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuildInCommands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuildInCommands.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BuildInCommands
  **/
  _count?: true | BuildInCommandsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BuildInCommandsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BuildInCommandsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BuildInCommandsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BuildInCommandsMaxAggregateInputType
}

export type GetBuildInCommandsAggregateType<T extends BuildInCommandsAggregateArgs> = {
      [P in keyof T & keyof AggregateBuildInCommands]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBuildInCommands[P]>
    : Prisma.GetScalarType<T[P], AggregateBuildInCommands[P]>
}




export type BuildInCommandsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BuildInCommandsWhereInput
  orderBy?: Prisma.BuildInCommandsOrderByWithAggregationInput | Prisma.BuildInCommandsOrderByWithAggregationInput[]
  by: Prisma.BuildInCommandsScalarFieldEnum[] | Prisma.BuildInCommandsScalarFieldEnum
  having?: Prisma.BuildInCommandsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BuildInCommandsCountAggregateInputType | true
  _avg?: BuildInCommandsAvgAggregateInputType
  _sum?: BuildInCommandsSumAggregateInputType
  _min?: BuildInCommandsMinAggregateInputType
  _max?: BuildInCommandsMaxAggregateInputType
}

export type BuildInCommandsGroupByOutputType = {
  Id: number
  UUID: string
  CustomName: string
  Description: string | null
  Permissions: string | null
  IsEnabled: boolean | null
  CodeName: string
  GuildCommandMangerId: string
  _count: BuildInCommandsCountAggregateOutputType | null
  _avg: BuildInCommandsAvgAggregateOutputType | null
  _sum: BuildInCommandsSumAggregateOutputType | null
  _min: BuildInCommandsMinAggregateOutputType | null
  _max: BuildInCommandsMaxAggregateOutputType | null
}

type GetBuildInCommandsGroupByPayload<T extends BuildInCommandsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BuildInCommandsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BuildInCommandsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BuildInCommandsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BuildInCommandsGroupByOutputType[P]>
      }
    >
  >



export type BuildInCommandsWhereInput = {
  AND?: Prisma.BuildInCommandsWhereInput | Prisma.BuildInCommandsWhereInput[]
  OR?: Prisma.BuildInCommandsWhereInput[]
  NOT?: Prisma.BuildInCommandsWhereInput | Prisma.BuildInCommandsWhereInput[]
  Id?: Prisma.IntFilter<"BuildInCommands"> | number
  UUID?: Prisma.StringFilter<"BuildInCommands"> | string
  CustomName?: Prisma.StringFilter<"BuildInCommands"> | string
  Description?: Prisma.StringNullableFilter<"BuildInCommands"> | string | null
  Permissions?: Prisma.StringNullableFilter<"BuildInCommands"> | string | null
  IsEnabled?: Prisma.BoolNullableFilter<"BuildInCommands"> | boolean | null
  CodeName?: Prisma.StringFilter<"BuildInCommands"> | string
  GuildCommandMangerId?: Prisma.StringFilter<"BuildInCommands"> | string
  GuildCommandMangers?: Prisma.XOR<Prisma.GuildCommandMangerScalarRelationFilter, Prisma.GuildCommandMangerWhereInput>
}

export type BuildInCommandsOrderByWithRelationInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  CustomName?: Prisma.SortOrder
  Description?: Prisma.SortOrderInput | Prisma.SortOrder
  Permissions?: Prisma.SortOrderInput | Prisma.SortOrder
  IsEnabled?: Prisma.SortOrderInput | Prisma.SortOrder
  CodeName?: Prisma.SortOrder
  GuildCommandMangerId?: Prisma.SortOrder
  GuildCommandMangers?: Prisma.GuildCommandMangerOrderByWithRelationInput
}

export type BuildInCommandsWhereUniqueInput = Prisma.AtLeast<{
  Id?: number
  UUID?: string
  AND?: Prisma.BuildInCommandsWhereInput | Prisma.BuildInCommandsWhereInput[]
  OR?: Prisma.BuildInCommandsWhereInput[]
  NOT?: Prisma.BuildInCommandsWhereInput | Prisma.BuildInCommandsWhereInput[]
  CustomName?: Prisma.StringFilter<"BuildInCommands"> | string
  Description?: Prisma.StringNullableFilter<"BuildInCommands"> | string | null
  Permissions?: Prisma.StringNullableFilter<"BuildInCommands"> | string | null
  IsEnabled?: Prisma.BoolNullableFilter<"BuildInCommands"> | boolean | null
  CodeName?: Prisma.StringFilter<"BuildInCommands"> | string
  GuildCommandMangerId?: Prisma.StringFilter<"BuildInCommands"> | string
  GuildCommandMangers?: Prisma.XOR<Prisma.GuildCommandMangerScalarRelationFilter, Prisma.GuildCommandMangerWhereInput>
}, "Id" | "UUID">

export type BuildInCommandsOrderByWithAggregationInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  CustomName?: Prisma.SortOrder
  Description?: Prisma.SortOrderInput | Prisma.SortOrder
  Permissions?: Prisma.SortOrderInput | Prisma.SortOrder
  IsEnabled?: Prisma.SortOrderInput | Prisma.SortOrder
  CodeName?: Prisma.SortOrder
  GuildCommandMangerId?: Prisma.SortOrder
  _count?: Prisma.BuildInCommandsCountOrderByAggregateInput
  _avg?: Prisma.BuildInCommandsAvgOrderByAggregateInput
  _max?: Prisma.BuildInCommandsMaxOrderByAggregateInput
  _min?: Prisma.BuildInCommandsMinOrderByAggregateInput
  _sum?: Prisma.BuildInCommandsSumOrderByAggregateInput
}

export type BuildInCommandsScalarWhereWithAggregatesInput = {
  AND?: Prisma.BuildInCommandsScalarWhereWithAggregatesInput | Prisma.BuildInCommandsScalarWhereWithAggregatesInput[]
  OR?: Prisma.BuildInCommandsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BuildInCommandsScalarWhereWithAggregatesInput | Prisma.BuildInCommandsScalarWhereWithAggregatesInput[]
  Id?: Prisma.IntWithAggregatesFilter<"BuildInCommands"> | number
  UUID?: Prisma.StringWithAggregatesFilter<"BuildInCommands"> | string
  CustomName?: Prisma.StringWithAggregatesFilter<"BuildInCommands"> | string
  Description?: Prisma.StringNullableWithAggregatesFilter<"BuildInCommands"> | string | null
  Permissions?: Prisma.StringNullableWithAggregatesFilter<"BuildInCommands"> | string | null
  IsEnabled?: Prisma.BoolNullableWithAggregatesFilter<"BuildInCommands"> | boolean | null
  CodeName?: Prisma.StringWithAggregatesFilter<"BuildInCommands"> | string
  GuildCommandMangerId?: Prisma.StringWithAggregatesFilter<"BuildInCommands"> | string
}

export type BuildInCommandsCreateInput = {
  UUID: string
  CustomName: string
  Description?: string | null
  Permissions?: string | null
  IsEnabled?: boolean | null
  CodeName: string
  GuildCommandMangers: Prisma.GuildCommandMangerCreateNestedOneWithoutBuildInCommandsInput
}

export type BuildInCommandsUncheckedCreateInput = {
  Id?: number
  UUID: string
  CustomName: string
  Description?: string | null
  Permissions?: string | null
  IsEnabled?: boolean | null
  CodeName: string
  GuildCommandMangerId: string
}

export type BuildInCommandsUpdateInput = {
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  CustomName?: Prisma.StringFieldUpdateOperationsInput | string
  Description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Permissions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IsEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  CodeName?: Prisma.StringFieldUpdateOperationsInput | string
  GuildCommandMangers?: Prisma.GuildCommandMangerUpdateOneRequiredWithoutBuildInCommandsNestedInput
}

export type BuildInCommandsUncheckedUpdateInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  CustomName?: Prisma.StringFieldUpdateOperationsInput | string
  Description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Permissions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IsEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  CodeName?: Prisma.StringFieldUpdateOperationsInput | string
  GuildCommandMangerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BuildInCommandsCreateManyInput = {
  Id?: number
  UUID: string
  CustomName: string
  Description?: string | null
  Permissions?: string | null
  IsEnabled?: boolean | null
  CodeName: string
  GuildCommandMangerId: string
}

export type BuildInCommandsUpdateManyMutationInput = {
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  CustomName?: Prisma.StringFieldUpdateOperationsInput | string
  Description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Permissions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IsEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  CodeName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BuildInCommandsUncheckedUpdateManyInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  CustomName?: Prisma.StringFieldUpdateOperationsInput | string
  Description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Permissions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IsEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  CodeName?: Prisma.StringFieldUpdateOperationsInput | string
  GuildCommandMangerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BuildInCommandsListRelationFilter = {
  every?: Prisma.BuildInCommandsWhereInput
  some?: Prisma.BuildInCommandsWhereInput
  none?: Prisma.BuildInCommandsWhereInput
}

export type BuildInCommandsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BuildInCommandsCountOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  CustomName?: Prisma.SortOrder
  Description?: Prisma.SortOrder
  Permissions?: Prisma.SortOrder
  IsEnabled?: Prisma.SortOrder
  CodeName?: Prisma.SortOrder
  GuildCommandMangerId?: Prisma.SortOrder
}

export type BuildInCommandsAvgOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type BuildInCommandsMaxOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  CustomName?: Prisma.SortOrder
  Description?: Prisma.SortOrder
  Permissions?: Prisma.SortOrder
  IsEnabled?: Prisma.SortOrder
  CodeName?: Prisma.SortOrder
  GuildCommandMangerId?: Prisma.SortOrder
}

export type BuildInCommandsMinOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  CustomName?: Prisma.SortOrder
  Description?: Prisma.SortOrder
  Permissions?: Prisma.SortOrder
  IsEnabled?: Prisma.SortOrder
  CodeName?: Prisma.SortOrder
  GuildCommandMangerId?: Prisma.SortOrder
}

export type BuildInCommandsSumOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type BuildInCommandsCreateNestedManyWithoutGuildCommandMangersInput = {
  create?: Prisma.XOR<Prisma.BuildInCommandsCreateWithoutGuildCommandMangersInput, Prisma.BuildInCommandsUncheckedCreateWithoutGuildCommandMangersInput> | Prisma.BuildInCommandsCreateWithoutGuildCommandMangersInput[] | Prisma.BuildInCommandsUncheckedCreateWithoutGuildCommandMangersInput[]
  connectOrCreate?: Prisma.BuildInCommandsCreateOrConnectWithoutGuildCommandMangersInput | Prisma.BuildInCommandsCreateOrConnectWithoutGuildCommandMangersInput[]
  createMany?: Prisma.BuildInCommandsCreateManyGuildCommandMangersInputEnvelope
  connect?: Prisma.BuildInCommandsWhereUniqueInput | Prisma.BuildInCommandsWhereUniqueInput[]
}

export type BuildInCommandsUncheckedCreateNestedManyWithoutGuildCommandMangersInput = {
  create?: Prisma.XOR<Prisma.BuildInCommandsCreateWithoutGuildCommandMangersInput, Prisma.BuildInCommandsUncheckedCreateWithoutGuildCommandMangersInput> | Prisma.BuildInCommandsCreateWithoutGuildCommandMangersInput[] | Prisma.BuildInCommandsUncheckedCreateWithoutGuildCommandMangersInput[]
  connectOrCreate?: Prisma.BuildInCommandsCreateOrConnectWithoutGuildCommandMangersInput | Prisma.BuildInCommandsCreateOrConnectWithoutGuildCommandMangersInput[]
  createMany?: Prisma.BuildInCommandsCreateManyGuildCommandMangersInputEnvelope
  connect?: Prisma.BuildInCommandsWhereUniqueInput | Prisma.BuildInCommandsWhereUniqueInput[]
}

export type BuildInCommandsUpdateManyWithoutGuildCommandMangersNestedInput = {
  create?: Prisma.XOR<Prisma.BuildInCommandsCreateWithoutGuildCommandMangersInput, Prisma.BuildInCommandsUncheckedCreateWithoutGuildCommandMangersInput> | Prisma.BuildInCommandsCreateWithoutGuildCommandMangersInput[] | Prisma.BuildInCommandsUncheckedCreateWithoutGuildCommandMangersInput[]
  connectOrCreate?: Prisma.BuildInCommandsCreateOrConnectWithoutGuildCommandMangersInput | Prisma.BuildInCommandsCreateOrConnectWithoutGuildCommandMangersInput[]
  upsert?: Prisma.BuildInCommandsUpsertWithWhereUniqueWithoutGuildCommandMangersInput | Prisma.BuildInCommandsUpsertWithWhereUniqueWithoutGuildCommandMangersInput[]
  createMany?: Prisma.BuildInCommandsCreateManyGuildCommandMangersInputEnvelope
  set?: Prisma.BuildInCommandsWhereUniqueInput | Prisma.BuildInCommandsWhereUniqueInput[]
  disconnect?: Prisma.BuildInCommandsWhereUniqueInput | Prisma.BuildInCommandsWhereUniqueInput[]
  delete?: Prisma.BuildInCommandsWhereUniqueInput | Prisma.BuildInCommandsWhereUniqueInput[]
  connect?: Prisma.BuildInCommandsWhereUniqueInput | Prisma.BuildInCommandsWhereUniqueInput[]
  update?: Prisma.BuildInCommandsUpdateWithWhereUniqueWithoutGuildCommandMangersInput | Prisma.BuildInCommandsUpdateWithWhereUniqueWithoutGuildCommandMangersInput[]
  updateMany?: Prisma.BuildInCommandsUpdateManyWithWhereWithoutGuildCommandMangersInput | Prisma.BuildInCommandsUpdateManyWithWhereWithoutGuildCommandMangersInput[]
  deleteMany?: Prisma.BuildInCommandsScalarWhereInput | Prisma.BuildInCommandsScalarWhereInput[]
}

export type BuildInCommandsUncheckedUpdateManyWithoutGuildCommandMangersNestedInput = {
  create?: Prisma.XOR<Prisma.BuildInCommandsCreateWithoutGuildCommandMangersInput, Prisma.BuildInCommandsUncheckedCreateWithoutGuildCommandMangersInput> | Prisma.BuildInCommandsCreateWithoutGuildCommandMangersInput[] | Prisma.BuildInCommandsUncheckedCreateWithoutGuildCommandMangersInput[]
  connectOrCreate?: Prisma.BuildInCommandsCreateOrConnectWithoutGuildCommandMangersInput | Prisma.BuildInCommandsCreateOrConnectWithoutGuildCommandMangersInput[]
  upsert?: Prisma.BuildInCommandsUpsertWithWhereUniqueWithoutGuildCommandMangersInput | Prisma.BuildInCommandsUpsertWithWhereUniqueWithoutGuildCommandMangersInput[]
  createMany?: Prisma.BuildInCommandsCreateManyGuildCommandMangersInputEnvelope
  set?: Prisma.BuildInCommandsWhereUniqueInput | Prisma.BuildInCommandsWhereUniqueInput[]
  disconnect?: Prisma.BuildInCommandsWhereUniqueInput | Prisma.BuildInCommandsWhereUniqueInput[]
  delete?: Prisma.BuildInCommandsWhereUniqueInput | Prisma.BuildInCommandsWhereUniqueInput[]
  connect?: Prisma.BuildInCommandsWhereUniqueInput | Prisma.BuildInCommandsWhereUniqueInput[]
  update?: Prisma.BuildInCommandsUpdateWithWhereUniqueWithoutGuildCommandMangersInput | Prisma.BuildInCommandsUpdateWithWhereUniqueWithoutGuildCommandMangersInput[]
  updateMany?: Prisma.BuildInCommandsUpdateManyWithWhereWithoutGuildCommandMangersInput | Prisma.BuildInCommandsUpdateManyWithWhereWithoutGuildCommandMangersInput[]
  deleteMany?: Prisma.BuildInCommandsScalarWhereInput | Prisma.BuildInCommandsScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type BuildInCommandsCreateWithoutGuildCommandMangersInput = {
  UUID: string
  CustomName: string
  Description?: string | null
  Permissions?: string | null
  IsEnabled?: boolean | null
  CodeName: string
}

export type BuildInCommandsUncheckedCreateWithoutGuildCommandMangersInput = {
  Id?: number
  UUID: string
  CustomName: string
  Description?: string | null
  Permissions?: string | null
  IsEnabled?: boolean | null
  CodeName: string
}

export type BuildInCommandsCreateOrConnectWithoutGuildCommandMangersInput = {
  where: Prisma.BuildInCommandsWhereUniqueInput
  create: Prisma.XOR<Prisma.BuildInCommandsCreateWithoutGuildCommandMangersInput, Prisma.BuildInCommandsUncheckedCreateWithoutGuildCommandMangersInput>
}

export type BuildInCommandsCreateManyGuildCommandMangersInputEnvelope = {
  data: Prisma.BuildInCommandsCreateManyGuildCommandMangersInput | Prisma.BuildInCommandsCreateManyGuildCommandMangersInput[]
  skipDuplicates?: boolean
}

export type BuildInCommandsUpsertWithWhereUniqueWithoutGuildCommandMangersInput = {
  where: Prisma.BuildInCommandsWhereUniqueInput
  update: Prisma.XOR<Prisma.BuildInCommandsUpdateWithoutGuildCommandMangersInput, Prisma.BuildInCommandsUncheckedUpdateWithoutGuildCommandMangersInput>
  create: Prisma.XOR<Prisma.BuildInCommandsCreateWithoutGuildCommandMangersInput, Prisma.BuildInCommandsUncheckedCreateWithoutGuildCommandMangersInput>
}

export type BuildInCommandsUpdateWithWhereUniqueWithoutGuildCommandMangersInput = {
  where: Prisma.BuildInCommandsWhereUniqueInput
  data: Prisma.XOR<Prisma.BuildInCommandsUpdateWithoutGuildCommandMangersInput, Prisma.BuildInCommandsUncheckedUpdateWithoutGuildCommandMangersInput>
}

export type BuildInCommandsUpdateManyWithWhereWithoutGuildCommandMangersInput = {
  where: Prisma.BuildInCommandsScalarWhereInput
  data: Prisma.XOR<Prisma.BuildInCommandsUpdateManyMutationInput, Prisma.BuildInCommandsUncheckedUpdateManyWithoutGuildCommandMangersInput>
}

export type BuildInCommandsScalarWhereInput = {
  AND?: Prisma.BuildInCommandsScalarWhereInput | Prisma.BuildInCommandsScalarWhereInput[]
  OR?: Prisma.BuildInCommandsScalarWhereInput[]
  NOT?: Prisma.BuildInCommandsScalarWhereInput | Prisma.BuildInCommandsScalarWhereInput[]
  Id?: Prisma.IntFilter<"BuildInCommands"> | number
  UUID?: Prisma.StringFilter<"BuildInCommands"> | string
  CustomName?: Prisma.StringFilter<"BuildInCommands"> | string
  Description?: Prisma.StringNullableFilter<"BuildInCommands"> | string | null
  Permissions?: Prisma.StringNullableFilter<"BuildInCommands"> | string | null
  IsEnabled?: Prisma.BoolNullableFilter<"BuildInCommands"> | boolean | null
  CodeName?: Prisma.StringFilter<"BuildInCommands"> | string
  GuildCommandMangerId?: Prisma.StringFilter<"BuildInCommands"> | string
}

export type BuildInCommandsCreateManyGuildCommandMangersInput = {
  Id?: number
  UUID: string
  CustomName: string
  Description?: string | null
  Permissions?: string | null
  IsEnabled?: boolean | null
  CodeName: string
}

export type BuildInCommandsUpdateWithoutGuildCommandMangersInput = {
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  CustomName?: Prisma.StringFieldUpdateOperationsInput | string
  Description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Permissions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IsEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  CodeName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BuildInCommandsUncheckedUpdateWithoutGuildCommandMangersInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  CustomName?: Prisma.StringFieldUpdateOperationsInput | string
  Description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Permissions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IsEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  CodeName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BuildInCommandsUncheckedUpdateManyWithoutGuildCommandMangersInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  CustomName?: Prisma.StringFieldUpdateOperationsInput | string
  Description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Permissions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  IsEnabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  CodeName?: Prisma.StringFieldUpdateOperationsInput | string
}



export type BuildInCommandsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UUID?: boolean
  CustomName?: boolean
  Description?: boolean
  Permissions?: boolean
  IsEnabled?: boolean
  CodeName?: boolean
  GuildCommandMangerId?: boolean
  GuildCommandMangers?: boolean | Prisma.GuildCommandMangerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buildInCommands"]>

export type BuildInCommandsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UUID?: boolean
  CustomName?: boolean
  Description?: boolean
  Permissions?: boolean
  IsEnabled?: boolean
  CodeName?: boolean
  GuildCommandMangerId?: boolean
  GuildCommandMangers?: boolean | Prisma.GuildCommandMangerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buildInCommands"]>

export type BuildInCommandsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UUID?: boolean
  CustomName?: boolean
  Description?: boolean
  Permissions?: boolean
  IsEnabled?: boolean
  CodeName?: boolean
  GuildCommandMangerId?: boolean
  GuildCommandMangers?: boolean | Prisma.GuildCommandMangerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buildInCommands"]>

export type BuildInCommandsSelectScalar = {
  Id?: boolean
  UUID?: boolean
  CustomName?: boolean
  Description?: boolean
  Permissions?: boolean
  IsEnabled?: boolean
  CodeName?: boolean
  GuildCommandMangerId?: boolean
}

export type BuildInCommandsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Id" | "UUID" | "CustomName" | "Description" | "Permissions" | "IsEnabled" | "CodeName" | "GuildCommandMangerId", ExtArgs["result"]["buildInCommands"]>
export type BuildInCommandsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  GuildCommandMangers?: boolean | Prisma.GuildCommandMangerDefaultArgs<ExtArgs>
}
export type BuildInCommandsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  GuildCommandMangers?: boolean | Prisma.GuildCommandMangerDefaultArgs<ExtArgs>
}
export type BuildInCommandsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  GuildCommandMangers?: boolean | Prisma.GuildCommandMangerDefaultArgs<ExtArgs>
}

export type $BuildInCommandsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BuildInCommands"
  objects: {
    GuildCommandMangers: Prisma.$GuildCommandMangerPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Id: number
    UUID: string
    CustomName: string
    Description: string | null
    Permissions: string | null
    IsEnabled: boolean | null
    CodeName: string
    GuildCommandMangerId: string
  }, ExtArgs["result"]["buildInCommands"]>
  composites: {}
}

export type BuildInCommandsGetPayload<S extends boolean | null | undefined | BuildInCommandsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload, S>

export type BuildInCommandsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BuildInCommandsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BuildInCommandsCountAggregateInputType | true
  }

export interface BuildInCommandsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BuildInCommands'], meta: { name: 'BuildInCommands' } }
  /**
   * Find zero or one BuildInCommands that matches the filter.
   * @param {BuildInCommandsFindUniqueArgs} args - Arguments to find a BuildInCommands
   * @example
   * // Get one BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BuildInCommandsFindUniqueArgs>(args: Prisma.SelectSubset<T, BuildInCommandsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BuildInCommandsClient<runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BuildInCommands that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BuildInCommandsFindUniqueOrThrowArgs} args - Arguments to find a BuildInCommands
   * @example
   * // Get one BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BuildInCommandsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BuildInCommandsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BuildInCommandsClient<runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BuildInCommands that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildInCommandsFindFirstArgs} args - Arguments to find a BuildInCommands
   * @example
   * // Get one BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BuildInCommandsFindFirstArgs>(args?: Prisma.SelectSubset<T, BuildInCommandsFindFirstArgs<ExtArgs>>): Prisma.Prisma__BuildInCommandsClient<runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BuildInCommands that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildInCommandsFindFirstOrThrowArgs} args - Arguments to find a BuildInCommands
   * @example
   * // Get one BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BuildInCommandsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BuildInCommandsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BuildInCommandsClient<runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BuildInCommands that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildInCommandsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.findMany()
   * 
   * // Get first 10 BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.findMany({ take: 10 })
   * 
   * // Only select the `Id`
   * const buildInCommandsWithIdOnly = await prisma.buildInCommands.findMany({ select: { Id: true } })
   * 
   */
  findMany<T extends BuildInCommandsFindManyArgs>(args?: Prisma.SelectSubset<T, BuildInCommandsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BuildInCommands.
   * @param {BuildInCommandsCreateArgs} args - Arguments to create a BuildInCommands.
   * @example
   * // Create one BuildInCommands
   * const BuildInCommands = await prisma.buildInCommands.create({
   *   data: {
   *     // ... data to create a BuildInCommands
   *   }
   * })
   * 
   */
  create<T extends BuildInCommandsCreateArgs>(args: Prisma.SelectSubset<T, BuildInCommandsCreateArgs<ExtArgs>>): Prisma.Prisma__BuildInCommandsClient<runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BuildInCommands.
   * @param {BuildInCommandsCreateManyArgs} args - Arguments to create many BuildInCommands.
   * @example
   * // Create many BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BuildInCommandsCreateManyArgs>(args?: Prisma.SelectSubset<T, BuildInCommandsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BuildInCommands and returns the data saved in the database.
   * @param {BuildInCommandsCreateManyAndReturnArgs} args - Arguments to create many BuildInCommands.
   * @example
   * // Create many BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BuildInCommands and only return the `Id`
   * const buildInCommandsWithIdOnly = await prisma.buildInCommands.createManyAndReturn({
   *   select: { Id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BuildInCommandsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BuildInCommandsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BuildInCommands.
   * @param {BuildInCommandsDeleteArgs} args - Arguments to delete one BuildInCommands.
   * @example
   * // Delete one BuildInCommands
   * const BuildInCommands = await prisma.buildInCommands.delete({
   *   where: {
   *     // ... filter to delete one BuildInCommands
   *   }
   * })
   * 
   */
  delete<T extends BuildInCommandsDeleteArgs>(args: Prisma.SelectSubset<T, BuildInCommandsDeleteArgs<ExtArgs>>): Prisma.Prisma__BuildInCommandsClient<runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BuildInCommands.
   * @param {BuildInCommandsUpdateArgs} args - Arguments to update one BuildInCommands.
   * @example
   * // Update one BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BuildInCommandsUpdateArgs>(args: Prisma.SelectSubset<T, BuildInCommandsUpdateArgs<ExtArgs>>): Prisma.Prisma__BuildInCommandsClient<runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BuildInCommands.
   * @param {BuildInCommandsDeleteManyArgs} args - Arguments to filter BuildInCommands to delete.
   * @example
   * // Delete a few BuildInCommands
   * const { count } = await prisma.buildInCommands.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BuildInCommandsDeleteManyArgs>(args?: Prisma.SelectSubset<T, BuildInCommandsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BuildInCommands.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildInCommandsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BuildInCommandsUpdateManyArgs>(args: Prisma.SelectSubset<T, BuildInCommandsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BuildInCommands and returns the data updated in the database.
   * @param {BuildInCommandsUpdateManyAndReturnArgs} args - Arguments to update many BuildInCommands.
   * @example
   * // Update many BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BuildInCommands and only return the `Id`
   * const buildInCommandsWithIdOnly = await prisma.buildInCommands.updateManyAndReturn({
   *   select: { Id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BuildInCommandsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BuildInCommandsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BuildInCommands.
   * @param {BuildInCommandsUpsertArgs} args - Arguments to update or create a BuildInCommands.
   * @example
   * // Update or create a BuildInCommands
   * const buildInCommands = await prisma.buildInCommands.upsert({
   *   create: {
   *     // ... data to create a BuildInCommands
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BuildInCommands we want to update
   *   }
   * })
   */
  upsert<T extends BuildInCommandsUpsertArgs>(args: Prisma.SelectSubset<T, BuildInCommandsUpsertArgs<ExtArgs>>): Prisma.Prisma__BuildInCommandsClient<runtime.Types.Result.GetResult<Prisma.$BuildInCommandsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BuildInCommands.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildInCommandsCountArgs} args - Arguments to filter BuildInCommands to count.
   * @example
   * // Count the number of BuildInCommands
   * const count = await prisma.buildInCommands.count({
   *   where: {
   *     // ... the filter for the BuildInCommands we want to count
   *   }
   * })
  **/
  count<T extends BuildInCommandsCountArgs>(
    args?: Prisma.Subset<T, BuildInCommandsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BuildInCommandsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BuildInCommands.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildInCommandsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BuildInCommandsAggregateArgs>(args: Prisma.Subset<T, BuildInCommandsAggregateArgs>): Prisma.PrismaPromise<GetBuildInCommandsAggregateType<T>>

  /**
   * Group by BuildInCommands.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuildInCommandsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BuildInCommandsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BuildInCommandsGroupByArgs['orderBy'] }
      : { orderBy?: BuildInCommandsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BuildInCommandsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBuildInCommandsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BuildInCommands model
 */
readonly fields: BuildInCommandsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BuildInCommands.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BuildInCommandsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  GuildCommandMangers<T extends Prisma.GuildCommandMangerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuildCommandMangerDefaultArgs<ExtArgs>>): Prisma.Prisma__GuildCommandMangerClient<runtime.Types.Result.GetResult<Prisma.$GuildCommandMangerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BuildInCommands model
 */
export interface BuildInCommandsFieldRefs {
  readonly Id: Prisma.FieldRef<"BuildInCommands", 'Int'>
  readonly UUID: Prisma.FieldRef<"BuildInCommands", 'String'>
  readonly CustomName: Prisma.FieldRef<"BuildInCommands", 'String'>
  readonly Description: Prisma.FieldRef<"BuildInCommands", 'String'>
  readonly Permissions: Prisma.FieldRef<"BuildInCommands", 'String'>
  readonly IsEnabled: Prisma.FieldRef<"BuildInCommands", 'Boolean'>
  readonly CodeName: Prisma.FieldRef<"BuildInCommands", 'String'>
  readonly GuildCommandMangerId: Prisma.FieldRef<"BuildInCommands", 'String'>
}
    

// Custom InputTypes
/**
 * BuildInCommands findUnique
 */
export type BuildInCommandsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsInclude<ExtArgs> | null
  /**
   * Filter, which BuildInCommands to fetch.
   */
  where: Prisma.BuildInCommandsWhereUniqueInput
}

/**
 * BuildInCommands findUniqueOrThrow
 */
export type BuildInCommandsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsInclude<ExtArgs> | null
  /**
   * Filter, which BuildInCommands to fetch.
   */
  where: Prisma.BuildInCommandsWhereUniqueInput
}

/**
 * BuildInCommands findFirst
 */
export type BuildInCommandsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsInclude<ExtArgs> | null
  /**
   * Filter, which BuildInCommands to fetch.
   */
  where?: Prisma.BuildInCommandsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuildInCommands to fetch.
   */
  orderBy?: Prisma.BuildInCommandsOrderByWithRelationInput | Prisma.BuildInCommandsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BuildInCommands.
   */
  cursor?: Prisma.BuildInCommandsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuildInCommands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuildInCommands.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BuildInCommands.
   */
  distinct?: Prisma.BuildInCommandsScalarFieldEnum | Prisma.BuildInCommandsScalarFieldEnum[]
}

/**
 * BuildInCommands findFirstOrThrow
 */
export type BuildInCommandsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsInclude<ExtArgs> | null
  /**
   * Filter, which BuildInCommands to fetch.
   */
  where?: Prisma.BuildInCommandsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuildInCommands to fetch.
   */
  orderBy?: Prisma.BuildInCommandsOrderByWithRelationInput | Prisma.BuildInCommandsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BuildInCommands.
   */
  cursor?: Prisma.BuildInCommandsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuildInCommands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuildInCommands.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BuildInCommands.
   */
  distinct?: Prisma.BuildInCommandsScalarFieldEnum | Prisma.BuildInCommandsScalarFieldEnum[]
}

/**
 * BuildInCommands findMany
 */
export type BuildInCommandsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsInclude<ExtArgs> | null
  /**
   * Filter, which BuildInCommands to fetch.
   */
  where?: Prisma.BuildInCommandsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuildInCommands to fetch.
   */
  orderBy?: Prisma.BuildInCommandsOrderByWithRelationInput | Prisma.BuildInCommandsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BuildInCommands.
   */
  cursor?: Prisma.BuildInCommandsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuildInCommands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuildInCommands.
   */
  skip?: number
  distinct?: Prisma.BuildInCommandsScalarFieldEnum | Prisma.BuildInCommandsScalarFieldEnum[]
}

/**
 * BuildInCommands create
 */
export type BuildInCommandsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsInclude<ExtArgs> | null
  /**
   * The data needed to create a BuildInCommands.
   */
  data: Prisma.XOR<Prisma.BuildInCommandsCreateInput, Prisma.BuildInCommandsUncheckedCreateInput>
}

/**
 * BuildInCommands createMany
 */
export type BuildInCommandsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BuildInCommands.
   */
  data: Prisma.BuildInCommandsCreateManyInput | Prisma.BuildInCommandsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BuildInCommands createManyAndReturn
 */
export type BuildInCommandsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * The data used to create many BuildInCommands.
   */
  data: Prisma.BuildInCommandsCreateManyInput | Prisma.BuildInCommandsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BuildInCommands update
 */
export type BuildInCommandsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsInclude<ExtArgs> | null
  /**
   * The data needed to update a BuildInCommands.
   */
  data: Prisma.XOR<Prisma.BuildInCommandsUpdateInput, Prisma.BuildInCommandsUncheckedUpdateInput>
  /**
   * Choose, which BuildInCommands to update.
   */
  where: Prisma.BuildInCommandsWhereUniqueInput
}

/**
 * BuildInCommands updateMany
 */
export type BuildInCommandsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BuildInCommands.
   */
  data: Prisma.XOR<Prisma.BuildInCommandsUpdateManyMutationInput, Prisma.BuildInCommandsUncheckedUpdateManyInput>
  /**
   * Filter which BuildInCommands to update
   */
  where?: Prisma.BuildInCommandsWhereInput
  /**
   * Limit how many BuildInCommands to update.
   */
  limit?: number
}

/**
 * BuildInCommands updateManyAndReturn
 */
export type BuildInCommandsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * The data used to update BuildInCommands.
   */
  data: Prisma.XOR<Prisma.BuildInCommandsUpdateManyMutationInput, Prisma.BuildInCommandsUncheckedUpdateManyInput>
  /**
   * Filter which BuildInCommands to update
   */
  where?: Prisma.BuildInCommandsWhereInput
  /**
   * Limit how many BuildInCommands to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BuildInCommands upsert
 */
export type BuildInCommandsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsInclude<ExtArgs> | null
  /**
   * The filter to search for the BuildInCommands to update in case it exists.
   */
  where: Prisma.BuildInCommandsWhereUniqueInput
  /**
   * In case the BuildInCommands found by the `where` argument doesn't exist, create a new BuildInCommands with this data.
   */
  create: Prisma.XOR<Prisma.BuildInCommandsCreateInput, Prisma.BuildInCommandsUncheckedCreateInput>
  /**
   * In case the BuildInCommands was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BuildInCommandsUpdateInput, Prisma.BuildInCommandsUncheckedUpdateInput>
}

/**
 * BuildInCommands delete
 */
export type BuildInCommandsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsInclude<ExtArgs> | null
  /**
   * Filter which BuildInCommands to delete.
   */
  where: Prisma.BuildInCommandsWhereUniqueInput
}

/**
 * BuildInCommands deleteMany
 */
export type BuildInCommandsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BuildInCommands to delete
   */
  where?: Prisma.BuildInCommandsWhereInput
  /**
   * Limit how many BuildInCommands to delete.
   */
  limit?: number
}

/**
 * BuildInCommands without action
 */
export type BuildInCommandsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuildInCommands
   */
  select?: Prisma.BuildInCommandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuildInCommands
   */
  omit?: Prisma.BuildInCommandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuildInCommandsInclude<ExtArgs> | null
}
