
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DisBot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model DisBot
 * 
 */
export type DisBotModel = runtime.Types.Result.DefaultSelection<Prisma.$DisBotPayload>

export type AggregateDisBot = {
  _count: DisBotCountAggregateOutputType | null
  _avg: DisBotAvgAggregateOutputType | null
  _sum: DisBotSumAggregateOutputType | null
  _min: DisBotMinAggregateOutputType | null
  _max: DisBotMaxAggregateOutputType | null
}

export type DisBotAvgAggregateOutputType = {
  Id: number | null
}

export type DisBotSumAggregateOutputType = {
  Id: number | null
}

export type DisBotMinAggregateOutputType = {
  Id: number | null
  SpotifyToken: string | null
  TwitchToken: string | null
  Version: string | null
  GetConf: string | null
}

export type DisBotMaxAggregateOutputType = {
  Id: number | null
  SpotifyToken: string | null
  TwitchToken: string | null
  Version: string | null
  GetConf: string | null
}

export type DisBotCountAggregateOutputType = {
  Id: number
  Logs: number
  SpotifyToken: number
  TwitchToken: number
  Version: number
  GetConf: number
  _all: number
}


export type DisBotAvgAggregateInputType = {
  Id?: true
}

export type DisBotSumAggregateInputType = {
  Id?: true
}

export type DisBotMinAggregateInputType = {
  Id?: true
  SpotifyToken?: true
  TwitchToken?: true
  Version?: true
  GetConf?: true
}

export type DisBotMaxAggregateInputType = {
  Id?: true
  SpotifyToken?: true
  TwitchToken?: true
  Version?: true
  GetConf?: true
}

export type DisBotCountAggregateInputType = {
  Id?: true
  Logs?: true
  SpotifyToken?: true
  TwitchToken?: true
  Version?: true
  GetConf?: true
  _all?: true
}

export type DisBotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DisBot to aggregate.
   */
  where?: Prisma.DisBotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DisBots to fetch.
   */
  orderBy?: Prisma.DisBotOrderByWithRelationInput | Prisma.DisBotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DisBotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DisBots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DisBots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DisBots
  **/
  _count?: true | DisBotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DisBotAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DisBotSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DisBotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DisBotMaxAggregateInputType
}

export type GetDisBotAggregateType<T extends DisBotAggregateArgs> = {
      [P in keyof T & keyof AggregateDisBot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDisBot[P]>
    : Prisma.GetScalarType<T[P], AggregateDisBot[P]>
}




export type DisBotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DisBotWhereInput
  orderBy?: Prisma.DisBotOrderByWithAggregationInput | Prisma.DisBotOrderByWithAggregationInput[]
  by: Prisma.DisBotScalarFieldEnum[] | Prisma.DisBotScalarFieldEnum
  having?: Prisma.DisBotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DisBotCountAggregateInputType | true
  _avg?: DisBotAvgAggregateInputType
  _sum?: DisBotSumAggregateInputType
  _min?: DisBotMinAggregateInputType
  _max?: DisBotMaxAggregateInputType
}

export type DisBotGroupByOutputType = {
  Id: number
  Logs: runtime.JsonValue[]
  SpotifyToken: string
  TwitchToken: string
  Version: string
  GetConf: string
  _count: DisBotCountAggregateOutputType | null
  _avg: DisBotAvgAggregateOutputType | null
  _sum: DisBotSumAggregateOutputType | null
  _min: DisBotMinAggregateOutputType | null
  _max: DisBotMaxAggregateOutputType | null
}

type GetDisBotGroupByPayload<T extends DisBotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DisBotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DisBotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DisBotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DisBotGroupByOutputType[P]>
      }
    >
  >



export type DisBotWhereInput = {
  AND?: Prisma.DisBotWhereInput | Prisma.DisBotWhereInput[]
  OR?: Prisma.DisBotWhereInput[]
  NOT?: Prisma.DisBotWhereInput | Prisma.DisBotWhereInput[]
  Id?: Prisma.IntFilter<"DisBot"> | number
  Logs?: Prisma.JsonNullableListFilter<"DisBot">
  SpotifyToken?: Prisma.StringFilter<"DisBot"> | string
  TwitchToken?: Prisma.StringFilter<"DisBot"> | string
  Version?: Prisma.StringFilter<"DisBot"> | string
  GetConf?: Prisma.StringFilter<"DisBot"> | string
}

export type DisBotOrderByWithRelationInput = {
  Id?: Prisma.SortOrder
  Logs?: Prisma.SortOrder
  SpotifyToken?: Prisma.SortOrder
  TwitchToken?: Prisma.SortOrder
  Version?: Prisma.SortOrder
  GetConf?: Prisma.SortOrder
}

export type DisBotWhereUniqueInput = Prisma.AtLeast<{
  Id?: number
  GetConf?: string
  AND?: Prisma.DisBotWhereInput | Prisma.DisBotWhereInput[]
  OR?: Prisma.DisBotWhereInput[]
  NOT?: Prisma.DisBotWhereInput | Prisma.DisBotWhereInput[]
  Logs?: Prisma.JsonNullableListFilter<"DisBot">
  SpotifyToken?: Prisma.StringFilter<"DisBot"> | string
  TwitchToken?: Prisma.StringFilter<"DisBot"> | string
  Version?: Prisma.StringFilter<"DisBot"> | string
}, "Id" | "GetConf">

export type DisBotOrderByWithAggregationInput = {
  Id?: Prisma.SortOrder
  Logs?: Prisma.SortOrder
  SpotifyToken?: Prisma.SortOrder
  TwitchToken?: Prisma.SortOrder
  Version?: Prisma.SortOrder
  GetConf?: Prisma.SortOrder
  _count?: Prisma.DisBotCountOrderByAggregateInput
  _avg?: Prisma.DisBotAvgOrderByAggregateInput
  _max?: Prisma.DisBotMaxOrderByAggregateInput
  _min?: Prisma.DisBotMinOrderByAggregateInput
  _sum?: Prisma.DisBotSumOrderByAggregateInput
}

export type DisBotScalarWhereWithAggregatesInput = {
  AND?: Prisma.DisBotScalarWhereWithAggregatesInput | Prisma.DisBotScalarWhereWithAggregatesInput[]
  OR?: Prisma.DisBotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DisBotScalarWhereWithAggregatesInput | Prisma.DisBotScalarWhereWithAggregatesInput[]
  Id?: Prisma.IntWithAggregatesFilter<"DisBot"> | number
  Logs?: Prisma.JsonNullableListFilter<"DisBot">
  SpotifyToken?: Prisma.StringWithAggregatesFilter<"DisBot"> | string
  TwitchToken?: Prisma.StringWithAggregatesFilter<"DisBot"> | string
  Version?: Prisma.StringWithAggregatesFilter<"DisBot"> | string
  GetConf?: Prisma.StringWithAggregatesFilter<"DisBot"> | string
}

export type DisBotCreateInput = {
  Logs?: Prisma.DisBotCreateLogsInput | runtime.InputJsonValue[]
  SpotifyToken: string
  TwitchToken: string
  Version: string
  GetConf: string
}

export type DisBotUncheckedCreateInput = {
  Id?: number
  Logs?: Prisma.DisBotCreateLogsInput | runtime.InputJsonValue[]
  SpotifyToken: string
  TwitchToken: string
  Version: string
  GetConf: string
}

export type DisBotUpdateInput = {
  Logs?: Prisma.DisBotUpdateLogsInput | runtime.InputJsonValue[]
  SpotifyToken?: Prisma.StringFieldUpdateOperationsInput | string
  TwitchToken?: Prisma.StringFieldUpdateOperationsInput | string
  Version?: Prisma.StringFieldUpdateOperationsInput | string
  GetConf?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DisBotUncheckedUpdateInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Logs?: Prisma.DisBotUpdateLogsInput | runtime.InputJsonValue[]
  SpotifyToken?: Prisma.StringFieldUpdateOperationsInput | string
  TwitchToken?: Prisma.StringFieldUpdateOperationsInput | string
  Version?: Prisma.StringFieldUpdateOperationsInput | string
  GetConf?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DisBotCreateManyInput = {
  Id?: number
  Logs?: Prisma.DisBotCreateLogsInput | runtime.InputJsonValue[]
  SpotifyToken: string
  TwitchToken: string
  Version: string
  GetConf: string
}

export type DisBotUpdateManyMutationInput = {
  Logs?: Prisma.DisBotUpdateLogsInput | runtime.InputJsonValue[]
  SpotifyToken?: Prisma.StringFieldUpdateOperationsInput | string
  TwitchToken?: Prisma.StringFieldUpdateOperationsInput | string
  Version?: Prisma.StringFieldUpdateOperationsInput | string
  GetConf?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DisBotUncheckedUpdateManyInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Logs?: Prisma.DisBotUpdateLogsInput | runtime.InputJsonValue[]
  SpotifyToken?: Prisma.StringFieldUpdateOperationsInput | string
  TwitchToken?: Prisma.StringFieldUpdateOperationsInput | string
  Version?: Prisma.StringFieldUpdateOperationsInput | string
  GetConf?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DisBotCountOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  Logs?: Prisma.SortOrder
  SpotifyToken?: Prisma.SortOrder
  TwitchToken?: Prisma.SortOrder
  Version?: Prisma.SortOrder
  GetConf?: Prisma.SortOrder
}

export type DisBotAvgOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type DisBotMaxOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  SpotifyToken?: Prisma.SortOrder
  TwitchToken?: Prisma.SortOrder
  Version?: Prisma.SortOrder
  GetConf?: Prisma.SortOrder
}

export type DisBotMinOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  SpotifyToken?: Prisma.SortOrder
  TwitchToken?: Prisma.SortOrder
  Version?: Prisma.SortOrder
  GetConf?: Prisma.SortOrder
}

export type DisBotSumOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type DisBotCreateLogsInput = {
  set: runtime.InputJsonValue[]
}

export type DisBotUpdateLogsInput = {
  set?: runtime.InputJsonValue[]
  push?: runtime.InputJsonValue | runtime.InputJsonValue[]
}



export type DisBotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  Logs?: boolean
  SpotifyToken?: boolean
  TwitchToken?: boolean
  Version?: boolean
  GetConf?: boolean
}, ExtArgs["result"]["disBot"]>

export type DisBotSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  Logs?: boolean
  SpotifyToken?: boolean
  TwitchToken?: boolean
  Version?: boolean
  GetConf?: boolean
}, ExtArgs["result"]["disBot"]>

export type DisBotSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  Logs?: boolean
  SpotifyToken?: boolean
  TwitchToken?: boolean
  Version?: boolean
  GetConf?: boolean
}, ExtArgs["result"]["disBot"]>

export type DisBotSelectScalar = {
  Id?: boolean
  Logs?: boolean
  SpotifyToken?: boolean
  TwitchToken?: boolean
  Version?: boolean
  GetConf?: boolean
}

export type DisBotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Id" | "Logs" | "SpotifyToken" | "TwitchToken" | "Version" | "GetConf", ExtArgs["result"]["disBot"]>

export type $DisBotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DisBot"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Id: number
    Logs: runtime.JsonValue[]
    SpotifyToken: string
    TwitchToken: string
    Version: string
    GetConf: string
  }, ExtArgs["result"]["disBot"]>
  composites: {}
}

export type DisBotGetPayload<S extends boolean | null | undefined | DisBotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DisBotPayload, S>

export type DisBotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DisBotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DisBotCountAggregateInputType | true
  }

export interface DisBotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DisBot'], meta: { name: 'DisBot' } }
  /**
   * Find zero or one DisBot that matches the filter.
   * @param {DisBotFindUniqueArgs} args - Arguments to find a DisBot
   * @example
   * // Get one DisBot
   * const disBot = await prisma.disBot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DisBotFindUniqueArgs>(args: Prisma.SelectSubset<T, DisBotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DisBotClient<runtime.Types.Result.GetResult<Prisma.$DisBotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DisBot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DisBotFindUniqueOrThrowArgs} args - Arguments to find a DisBot
   * @example
   * // Get one DisBot
   * const disBot = await prisma.disBot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DisBotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DisBotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DisBotClient<runtime.Types.Result.GetResult<Prisma.$DisBotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DisBot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DisBotFindFirstArgs} args - Arguments to find a DisBot
   * @example
   * // Get one DisBot
   * const disBot = await prisma.disBot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DisBotFindFirstArgs>(args?: Prisma.SelectSubset<T, DisBotFindFirstArgs<ExtArgs>>): Prisma.Prisma__DisBotClient<runtime.Types.Result.GetResult<Prisma.$DisBotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DisBot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DisBotFindFirstOrThrowArgs} args - Arguments to find a DisBot
   * @example
   * // Get one DisBot
   * const disBot = await prisma.disBot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DisBotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DisBotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DisBotClient<runtime.Types.Result.GetResult<Prisma.$DisBotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DisBots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DisBotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DisBots
   * const disBots = await prisma.disBot.findMany()
   * 
   * // Get first 10 DisBots
   * const disBots = await prisma.disBot.findMany({ take: 10 })
   * 
   * // Only select the `Id`
   * const disBotWithIdOnly = await prisma.disBot.findMany({ select: { Id: true } })
   * 
   */
  findMany<T extends DisBotFindManyArgs>(args?: Prisma.SelectSubset<T, DisBotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DisBotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DisBot.
   * @param {DisBotCreateArgs} args - Arguments to create a DisBot.
   * @example
   * // Create one DisBot
   * const DisBot = await prisma.disBot.create({
   *   data: {
   *     // ... data to create a DisBot
   *   }
   * })
   * 
   */
  create<T extends DisBotCreateArgs>(args: Prisma.SelectSubset<T, DisBotCreateArgs<ExtArgs>>): Prisma.Prisma__DisBotClient<runtime.Types.Result.GetResult<Prisma.$DisBotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DisBots.
   * @param {DisBotCreateManyArgs} args - Arguments to create many DisBots.
   * @example
   * // Create many DisBots
   * const disBot = await prisma.disBot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DisBotCreateManyArgs>(args?: Prisma.SelectSubset<T, DisBotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DisBots and returns the data saved in the database.
   * @param {DisBotCreateManyAndReturnArgs} args - Arguments to create many DisBots.
   * @example
   * // Create many DisBots
   * const disBot = await prisma.disBot.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DisBots and only return the `Id`
   * const disBotWithIdOnly = await prisma.disBot.createManyAndReturn({
   *   select: { Id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DisBotCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DisBotCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DisBotPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DisBot.
   * @param {DisBotDeleteArgs} args - Arguments to delete one DisBot.
   * @example
   * // Delete one DisBot
   * const DisBot = await prisma.disBot.delete({
   *   where: {
   *     // ... filter to delete one DisBot
   *   }
   * })
   * 
   */
  delete<T extends DisBotDeleteArgs>(args: Prisma.SelectSubset<T, DisBotDeleteArgs<ExtArgs>>): Prisma.Prisma__DisBotClient<runtime.Types.Result.GetResult<Prisma.$DisBotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DisBot.
   * @param {DisBotUpdateArgs} args - Arguments to update one DisBot.
   * @example
   * // Update one DisBot
   * const disBot = await prisma.disBot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DisBotUpdateArgs>(args: Prisma.SelectSubset<T, DisBotUpdateArgs<ExtArgs>>): Prisma.Prisma__DisBotClient<runtime.Types.Result.GetResult<Prisma.$DisBotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DisBots.
   * @param {DisBotDeleteManyArgs} args - Arguments to filter DisBots to delete.
   * @example
   * // Delete a few DisBots
   * const { count } = await prisma.disBot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DisBotDeleteManyArgs>(args?: Prisma.SelectSubset<T, DisBotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DisBots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DisBotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DisBots
   * const disBot = await prisma.disBot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DisBotUpdateManyArgs>(args: Prisma.SelectSubset<T, DisBotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DisBots and returns the data updated in the database.
   * @param {DisBotUpdateManyAndReturnArgs} args - Arguments to update many DisBots.
   * @example
   * // Update many DisBots
   * const disBot = await prisma.disBot.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DisBots and only return the `Id`
   * const disBotWithIdOnly = await prisma.disBot.updateManyAndReturn({
   *   select: { Id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DisBotUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DisBotUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DisBotPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DisBot.
   * @param {DisBotUpsertArgs} args - Arguments to update or create a DisBot.
   * @example
   * // Update or create a DisBot
   * const disBot = await prisma.disBot.upsert({
   *   create: {
   *     // ... data to create a DisBot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DisBot we want to update
   *   }
   * })
   */
  upsert<T extends DisBotUpsertArgs>(args: Prisma.SelectSubset<T, DisBotUpsertArgs<ExtArgs>>): Prisma.Prisma__DisBotClient<runtime.Types.Result.GetResult<Prisma.$DisBotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DisBots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DisBotCountArgs} args - Arguments to filter DisBots to count.
   * @example
   * // Count the number of DisBots
   * const count = await prisma.disBot.count({
   *   where: {
   *     // ... the filter for the DisBots we want to count
   *   }
   * })
  **/
  count<T extends DisBotCountArgs>(
    args?: Prisma.Subset<T, DisBotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DisBotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DisBot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DisBotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DisBotAggregateArgs>(args: Prisma.Subset<T, DisBotAggregateArgs>): Prisma.PrismaPromise<GetDisBotAggregateType<T>>

  /**
   * Group by DisBot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DisBotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DisBotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DisBotGroupByArgs['orderBy'] }
      : { orderBy?: DisBotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DisBotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDisBotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DisBot model
 */
readonly fields: DisBotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DisBot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DisBotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DisBot model
 */
export interface DisBotFieldRefs {
  readonly Id: Prisma.FieldRef<"DisBot", 'Int'>
  readonly Logs: Prisma.FieldRef<"DisBot", 'Json[]'>
  readonly SpotifyToken: Prisma.FieldRef<"DisBot", 'String'>
  readonly TwitchToken: Prisma.FieldRef<"DisBot", 'String'>
  readonly Version: Prisma.FieldRef<"DisBot", 'String'>
  readonly GetConf: Prisma.FieldRef<"DisBot", 'String'>
}
    

// Custom InputTypes
/**
 * DisBot findUnique
 */
export type DisBotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
  /**
   * Filter, which DisBot to fetch.
   */
  where: Prisma.DisBotWhereUniqueInput
}

/**
 * DisBot findUniqueOrThrow
 */
export type DisBotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
  /**
   * Filter, which DisBot to fetch.
   */
  where: Prisma.DisBotWhereUniqueInput
}

/**
 * DisBot findFirst
 */
export type DisBotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
  /**
   * Filter, which DisBot to fetch.
   */
  where?: Prisma.DisBotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DisBots to fetch.
   */
  orderBy?: Prisma.DisBotOrderByWithRelationInput | Prisma.DisBotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DisBots.
   */
  cursor?: Prisma.DisBotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DisBots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DisBots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DisBots.
   */
  distinct?: Prisma.DisBotScalarFieldEnum | Prisma.DisBotScalarFieldEnum[]
}

/**
 * DisBot findFirstOrThrow
 */
export type DisBotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
  /**
   * Filter, which DisBot to fetch.
   */
  where?: Prisma.DisBotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DisBots to fetch.
   */
  orderBy?: Prisma.DisBotOrderByWithRelationInput | Prisma.DisBotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DisBots.
   */
  cursor?: Prisma.DisBotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DisBots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DisBots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DisBots.
   */
  distinct?: Prisma.DisBotScalarFieldEnum | Prisma.DisBotScalarFieldEnum[]
}

/**
 * DisBot findMany
 */
export type DisBotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
  /**
   * Filter, which DisBots to fetch.
   */
  where?: Prisma.DisBotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DisBots to fetch.
   */
  orderBy?: Prisma.DisBotOrderByWithRelationInput | Prisma.DisBotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DisBots.
   */
  cursor?: Prisma.DisBotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DisBots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DisBots.
   */
  skip?: number
  distinct?: Prisma.DisBotScalarFieldEnum | Prisma.DisBotScalarFieldEnum[]
}

/**
 * DisBot create
 */
export type DisBotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
  /**
   * The data needed to create a DisBot.
   */
  data: Prisma.XOR<Prisma.DisBotCreateInput, Prisma.DisBotUncheckedCreateInput>
}

/**
 * DisBot createMany
 */
export type DisBotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DisBots.
   */
  data: Prisma.DisBotCreateManyInput | Prisma.DisBotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DisBot createManyAndReturn
 */
export type DisBotCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
  /**
   * The data used to create many DisBots.
   */
  data: Prisma.DisBotCreateManyInput | Prisma.DisBotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DisBot update
 */
export type DisBotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
  /**
   * The data needed to update a DisBot.
   */
  data: Prisma.XOR<Prisma.DisBotUpdateInput, Prisma.DisBotUncheckedUpdateInput>
  /**
   * Choose, which DisBot to update.
   */
  where: Prisma.DisBotWhereUniqueInput
}

/**
 * DisBot updateMany
 */
export type DisBotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DisBots.
   */
  data: Prisma.XOR<Prisma.DisBotUpdateManyMutationInput, Prisma.DisBotUncheckedUpdateManyInput>
  /**
   * Filter which DisBots to update
   */
  where?: Prisma.DisBotWhereInput
  /**
   * Limit how many DisBots to update.
   */
  limit?: number
}

/**
 * DisBot updateManyAndReturn
 */
export type DisBotUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
  /**
   * The data used to update DisBots.
   */
  data: Prisma.XOR<Prisma.DisBotUpdateManyMutationInput, Prisma.DisBotUncheckedUpdateManyInput>
  /**
   * Filter which DisBots to update
   */
  where?: Prisma.DisBotWhereInput
  /**
   * Limit how many DisBots to update.
   */
  limit?: number
}

/**
 * DisBot upsert
 */
export type DisBotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
  /**
   * The filter to search for the DisBot to update in case it exists.
   */
  where: Prisma.DisBotWhereUniqueInput
  /**
   * In case the DisBot found by the `where` argument doesn't exist, create a new DisBot with this data.
   */
  create: Prisma.XOR<Prisma.DisBotCreateInput, Prisma.DisBotUncheckedCreateInput>
  /**
   * In case the DisBot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DisBotUpdateInput, Prisma.DisBotUncheckedUpdateInput>
}

/**
 * DisBot delete
 */
export type DisBotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
  /**
   * Filter which DisBot to delete.
   */
  where: Prisma.DisBotWhereUniqueInput
}

/**
 * DisBot deleteMany
 */
export type DisBotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DisBots to delete
   */
  where?: Prisma.DisBotWhereInput
  /**
   * Limit how many DisBots to delete.
   */
  limit?: number
}

/**
 * DisBot without action
 */
export type DisBotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DisBot
   */
  select?: Prisma.DisBotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DisBot
   */
  omit?: Prisma.DisBotOmit<ExtArgs> | null
}
