
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ModerationScoutReportModalData` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ModerationScoutReportModalData
 * 
 */
export type ModerationScoutReportModalDataModel = runtime.Types.Result.DefaultSelection<Prisma.$ModerationScoutReportModalDataPayload>

export type AggregateModerationScoutReportModalData = {
  _count: ModerationScoutReportModalDataCountAggregateOutputType | null
  _avg: ModerationScoutReportModalDataAvgAggregateOutputType | null
  _sum: ModerationScoutReportModalDataSumAggregateOutputType | null
  _min: ModerationScoutReportModalDataMinAggregateOutputType | null
  _max: ModerationScoutReportModalDataMaxAggregateOutputType | null
}

export type ModerationScoutReportModalDataAvgAggregateOutputType = {
  Id: number | null
  Type: number | null
  MinLength: number | null
  MaxLength: number | null
}

export type ModerationScoutReportModalDataSumAggregateOutputType = {
  Id: number | null
  Type: number | null
  MinLength: number | null
  MaxLength: number | null
}

export type ModerationScoutReportModalDataMinAggregateOutputType = {
  Id: number | null
  UUID: string | null
  Name: string | null
  Placeholder: string | null
  Type: number | null
  MinLength: number | null
  MaxLength: number | null
  Required: boolean | null
  InteractionType: string | null
  ModerationScoutId: string | null
}

export type ModerationScoutReportModalDataMaxAggregateOutputType = {
  Id: number | null
  UUID: string | null
  Name: string | null
  Placeholder: string | null
  Type: number | null
  MinLength: number | null
  MaxLength: number | null
  Required: boolean | null
  InteractionType: string | null
  ModerationScoutId: string | null
}

export type ModerationScoutReportModalDataCountAggregateOutputType = {
  Id: number
  UUID: number
  Name: number
  Placeholder: number
  Type: number
  MinLength: number
  MaxLength: number
  Required: number
  InteractionType: number
  ModerationScoutId: number
  _all: number
}


export type ModerationScoutReportModalDataAvgAggregateInputType = {
  Id?: true
  Type?: true
  MinLength?: true
  MaxLength?: true
}

export type ModerationScoutReportModalDataSumAggregateInputType = {
  Id?: true
  Type?: true
  MinLength?: true
  MaxLength?: true
}

export type ModerationScoutReportModalDataMinAggregateInputType = {
  Id?: true
  UUID?: true
  Name?: true
  Placeholder?: true
  Type?: true
  MinLength?: true
  MaxLength?: true
  Required?: true
  InteractionType?: true
  ModerationScoutId?: true
}

export type ModerationScoutReportModalDataMaxAggregateInputType = {
  Id?: true
  UUID?: true
  Name?: true
  Placeholder?: true
  Type?: true
  MinLength?: true
  MaxLength?: true
  Required?: true
  InteractionType?: true
  ModerationScoutId?: true
}

export type ModerationScoutReportModalDataCountAggregateInputType = {
  Id?: true
  UUID?: true
  Name?: true
  Placeholder?: true
  Type?: true
  MinLength?: true
  MaxLength?: true
  Required?: true
  InteractionType?: true
  ModerationScoutId?: true
  _all?: true
}

export type ModerationScoutReportModalDataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModerationScoutReportModalData to aggregate.
   */
  where?: Prisma.ModerationScoutReportModalDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationScoutReportModalData to fetch.
   */
  orderBy?: Prisma.ModerationScoutReportModalDataOrderByWithRelationInput | Prisma.ModerationScoutReportModalDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ModerationScoutReportModalDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationScoutReportModalData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationScoutReportModalData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ModerationScoutReportModalData
  **/
  _count?: true | ModerationScoutReportModalDataCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ModerationScoutReportModalDataAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ModerationScoutReportModalDataSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ModerationScoutReportModalDataMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ModerationScoutReportModalDataMaxAggregateInputType
}

export type GetModerationScoutReportModalDataAggregateType<T extends ModerationScoutReportModalDataAggregateArgs> = {
      [P in keyof T & keyof AggregateModerationScoutReportModalData]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateModerationScoutReportModalData[P]>
    : Prisma.GetScalarType<T[P], AggregateModerationScoutReportModalData[P]>
}




export type ModerationScoutReportModalDataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ModerationScoutReportModalDataWhereInput
  orderBy?: Prisma.ModerationScoutReportModalDataOrderByWithAggregationInput | Prisma.ModerationScoutReportModalDataOrderByWithAggregationInput[]
  by: Prisma.ModerationScoutReportModalDataScalarFieldEnum[] | Prisma.ModerationScoutReportModalDataScalarFieldEnum
  having?: Prisma.ModerationScoutReportModalDataScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ModerationScoutReportModalDataCountAggregateInputType | true
  _avg?: ModerationScoutReportModalDataAvgAggregateInputType
  _sum?: ModerationScoutReportModalDataSumAggregateInputType
  _min?: ModerationScoutReportModalDataMinAggregateInputType
  _max?: ModerationScoutReportModalDataMaxAggregateInputType
}

export type ModerationScoutReportModalDataGroupByOutputType = {
  Id: number
  UUID: string
  Name: string
  Placeholder: string | null
  Type: number
  MinLength: number | null
  MaxLength: number | null
  Required: boolean
  InteractionType: string
  ModerationScoutId: string
  _count: ModerationScoutReportModalDataCountAggregateOutputType | null
  _avg: ModerationScoutReportModalDataAvgAggregateOutputType | null
  _sum: ModerationScoutReportModalDataSumAggregateOutputType | null
  _min: ModerationScoutReportModalDataMinAggregateOutputType | null
  _max: ModerationScoutReportModalDataMaxAggregateOutputType | null
}

type GetModerationScoutReportModalDataGroupByPayload<T extends ModerationScoutReportModalDataGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ModerationScoutReportModalDataGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ModerationScoutReportModalDataGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ModerationScoutReportModalDataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ModerationScoutReportModalDataGroupByOutputType[P]>
      }
    >
  >



export type ModerationScoutReportModalDataWhereInput = {
  AND?: Prisma.ModerationScoutReportModalDataWhereInput | Prisma.ModerationScoutReportModalDataWhereInput[]
  OR?: Prisma.ModerationScoutReportModalDataWhereInput[]
  NOT?: Prisma.ModerationScoutReportModalDataWhereInput | Prisma.ModerationScoutReportModalDataWhereInput[]
  Id?: Prisma.IntFilter<"ModerationScoutReportModalData"> | number
  UUID?: Prisma.StringFilter<"ModerationScoutReportModalData"> | string
  Name?: Prisma.StringFilter<"ModerationScoutReportModalData"> | string
  Placeholder?: Prisma.StringNullableFilter<"ModerationScoutReportModalData"> | string | null
  Type?: Prisma.IntFilter<"ModerationScoutReportModalData"> | number
  MinLength?: Prisma.IntNullableFilter<"ModerationScoutReportModalData"> | number | null
  MaxLength?: Prisma.IntNullableFilter<"ModerationScoutReportModalData"> | number | null
  Required?: Prisma.BoolFilter<"ModerationScoutReportModalData"> | boolean
  InteractionType?: Prisma.StringFilter<"ModerationScoutReportModalData"> | string
  ModerationScoutId?: Prisma.StringFilter<"ModerationScoutReportModalData"> | string
  ModerationScout?: Prisma.XOR<Prisma.ModerationScoutScalarRelationFilter, Prisma.ModerationScoutWhereInput>
}

export type ModerationScoutReportModalDataOrderByWithRelationInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  Name?: Prisma.SortOrder
  Placeholder?: Prisma.SortOrderInput | Prisma.SortOrder
  Type?: Prisma.SortOrder
  MinLength?: Prisma.SortOrderInput | Prisma.SortOrder
  MaxLength?: Prisma.SortOrderInput | Prisma.SortOrder
  Required?: Prisma.SortOrder
  InteractionType?: Prisma.SortOrder
  ModerationScoutId?: Prisma.SortOrder
  ModerationScout?: Prisma.ModerationScoutOrderByWithRelationInput
}

export type ModerationScoutReportModalDataWhereUniqueInput = Prisma.AtLeast<{
  Id?: number
  UUID?: string
  AND?: Prisma.ModerationScoutReportModalDataWhereInput | Prisma.ModerationScoutReportModalDataWhereInput[]
  OR?: Prisma.ModerationScoutReportModalDataWhereInput[]
  NOT?: Prisma.ModerationScoutReportModalDataWhereInput | Prisma.ModerationScoutReportModalDataWhereInput[]
  Name?: Prisma.StringFilter<"ModerationScoutReportModalData"> | string
  Placeholder?: Prisma.StringNullableFilter<"ModerationScoutReportModalData"> | string | null
  Type?: Prisma.IntFilter<"ModerationScoutReportModalData"> | number
  MinLength?: Prisma.IntNullableFilter<"ModerationScoutReportModalData"> | number | null
  MaxLength?: Prisma.IntNullableFilter<"ModerationScoutReportModalData"> | number | null
  Required?: Prisma.BoolFilter<"ModerationScoutReportModalData"> | boolean
  InteractionType?: Prisma.StringFilter<"ModerationScoutReportModalData"> | string
  ModerationScoutId?: Prisma.StringFilter<"ModerationScoutReportModalData"> | string
  ModerationScout?: Prisma.XOR<Prisma.ModerationScoutScalarRelationFilter, Prisma.ModerationScoutWhereInput>
}, "Id" | "UUID">

export type ModerationScoutReportModalDataOrderByWithAggregationInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  Name?: Prisma.SortOrder
  Placeholder?: Prisma.SortOrderInput | Prisma.SortOrder
  Type?: Prisma.SortOrder
  MinLength?: Prisma.SortOrderInput | Prisma.SortOrder
  MaxLength?: Prisma.SortOrderInput | Prisma.SortOrder
  Required?: Prisma.SortOrder
  InteractionType?: Prisma.SortOrder
  ModerationScoutId?: Prisma.SortOrder
  _count?: Prisma.ModerationScoutReportModalDataCountOrderByAggregateInput
  _avg?: Prisma.ModerationScoutReportModalDataAvgOrderByAggregateInput
  _max?: Prisma.ModerationScoutReportModalDataMaxOrderByAggregateInput
  _min?: Prisma.ModerationScoutReportModalDataMinOrderByAggregateInput
  _sum?: Prisma.ModerationScoutReportModalDataSumOrderByAggregateInput
}

export type ModerationScoutReportModalDataScalarWhereWithAggregatesInput = {
  AND?: Prisma.ModerationScoutReportModalDataScalarWhereWithAggregatesInput | Prisma.ModerationScoutReportModalDataScalarWhereWithAggregatesInput[]
  OR?: Prisma.ModerationScoutReportModalDataScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ModerationScoutReportModalDataScalarWhereWithAggregatesInput | Prisma.ModerationScoutReportModalDataScalarWhereWithAggregatesInput[]
  Id?: Prisma.IntWithAggregatesFilter<"ModerationScoutReportModalData"> | number
  UUID?: Prisma.StringWithAggregatesFilter<"ModerationScoutReportModalData"> | string
  Name?: Prisma.StringWithAggregatesFilter<"ModerationScoutReportModalData"> | string
  Placeholder?: Prisma.StringNullableWithAggregatesFilter<"ModerationScoutReportModalData"> | string | null
  Type?: Prisma.IntWithAggregatesFilter<"ModerationScoutReportModalData"> | number
  MinLength?: Prisma.IntNullableWithAggregatesFilter<"ModerationScoutReportModalData"> | number | null
  MaxLength?: Prisma.IntNullableWithAggregatesFilter<"ModerationScoutReportModalData"> | number | null
  Required?: Prisma.BoolWithAggregatesFilter<"ModerationScoutReportModalData"> | boolean
  InteractionType?: Prisma.StringWithAggregatesFilter<"ModerationScoutReportModalData"> | string
  ModerationScoutId?: Prisma.StringWithAggregatesFilter<"ModerationScoutReportModalData"> | string
}

export type ModerationScoutReportModalDataCreateInput = {
  Name: string
  Placeholder?: string | null
  Type: number
  MinLength?: number | null
  MaxLength?: number | null
  Required: boolean
  InteractionType: string
  ModerationScoutId: string
  ModerationScout: Prisma.ModerationScoutCreateNestedOneWithoutModerationScoutReportModalDataInput
}

export type ModerationScoutReportModalDataUncheckedCreateInput = {
  Id?: number
  UUID: string
  Name: string
  Placeholder?: string | null
  Type: number
  MinLength?: number | null
  MaxLength?: number | null
  Required: boolean
  InteractionType: string
  ModerationScoutId: string
}

export type ModerationScoutReportModalDataUpdateInput = {
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  Placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Type?: Prisma.IntFieldUpdateOperationsInput | number
  MinLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  MaxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  InteractionType?: Prisma.StringFieldUpdateOperationsInput | string
  ModerationScoutId?: Prisma.StringFieldUpdateOperationsInput | string
  ModerationScout?: Prisma.ModerationScoutUpdateOneRequiredWithoutModerationScoutReportModalDataNestedInput
}

export type ModerationScoutReportModalDataUncheckedUpdateInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  Placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Type?: Prisma.IntFieldUpdateOperationsInput | number
  MinLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  MaxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  InteractionType?: Prisma.StringFieldUpdateOperationsInput | string
  ModerationScoutId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ModerationScoutReportModalDataCreateManyInput = {
  Id?: number
  UUID: string
  Name: string
  Placeholder?: string | null
  Type: number
  MinLength?: number | null
  MaxLength?: number | null
  Required: boolean
  InteractionType: string
  ModerationScoutId: string
}

export type ModerationScoutReportModalDataUpdateManyMutationInput = {
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  Placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Type?: Prisma.IntFieldUpdateOperationsInput | number
  MinLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  MaxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  InteractionType?: Prisma.StringFieldUpdateOperationsInput | string
  ModerationScoutId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ModerationScoutReportModalDataUncheckedUpdateManyInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  Placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Type?: Prisma.IntFieldUpdateOperationsInput | number
  MinLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  MaxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  InteractionType?: Prisma.StringFieldUpdateOperationsInput | string
  ModerationScoutId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ModerationScoutReportModalDataNullableScalarRelationFilter = {
  is?: Prisma.ModerationScoutReportModalDataWhereInput | null
  isNot?: Prisma.ModerationScoutReportModalDataWhereInput | null
}

export type ModerationScoutReportModalDataCountOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  Name?: Prisma.SortOrder
  Placeholder?: Prisma.SortOrder
  Type?: Prisma.SortOrder
  MinLength?: Prisma.SortOrder
  MaxLength?: Prisma.SortOrder
  Required?: Prisma.SortOrder
  InteractionType?: Prisma.SortOrder
  ModerationScoutId?: Prisma.SortOrder
}

export type ModerationScoutReportModalDataAvgOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  Type?: Prisma.SortOrder
  MinLength?: Prisma.SortOrder
  MaxLength?: Prisma.SortOrder
}

export type ModerationScoutReportModalDataMaxOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  Name?: Prisma.SortOrder
  Placeholder?: Prisma.SortOrder
  Type?: Prisma.SortOrder
  MinLength?: Prisma.SortOrder
  MaxLength?: Prisma.SortOrder
  Required?: Prisma.SortOrder
  InteractionType?: Prisma.SortOrder
  ModerationScoutId?: Prisma.SortOrder
}

export type ModerationScoutReportModalDataMinOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  Name?: Prisma.SortOrder
  Placeholder?: Prisma.SortOrder
  Type?: Prisma.SortOrder
  MinLength?: Prisma.SortOrder
  MaxLength?: Prisma.SortOrder
  Required?: Prisma.SortOrder
  InteractionType?: Prisma.SortOrder
  ModerationScoutId?: Prisma.SortOrder
}

export type ModerationScoutReportModalDataSumOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  Type?: Prisma.SortOrder
  MinLength?: Prisma.SortOrder
  MaxLength?: Prisma.SortOrder
}

export type ModerationScoutReportModalDataCreateNestedOneWithoutModerationScoutInput = {
  create?: Prisma.XOR<Prisma.ModerationScoutReportModalDataCreateWithoutModerationScoutInput, Prisma.ModerationScoutReportModalDataUncheckedCreateWithoutModerationScoutInput>
  connectOrCreate?: Prisma.ModerationScoutReportModalDataCreateOrConnectWithoutModerationScoutInput
  connect?: Prisma.ModerationScoutReportModalDataWhereUniqueInput
}

export type ModerationScoutReportModalDataUncheckedCreateNestedOneWithoutModerationScoutInput = {
  create?: Prisma.XOR<Prisma.ModerationScoutReportModalDataCreateWithoutModerationScoutInput, Prisma.ModerationScoutReportModalDataUncheckedCreateWithoutModerationScoutInput>
  connectOrCreate?: Prisma.ModerationScoutReportModalDataCreateOrConnectWithoutModerationScoutInput
  connect?: Prisma.ModerationScoutReportModalDataWhereUniqueInput
}

export type ModerationScoutReportModalDataUpdateOneWithoutModerationScoutNestedInput = {
  create?: Prisma.XOR<Prisma.ModerationScoutReportModalDataCreateWithoutModerationScoutInput, Prisma.ModerationScoutReportModalDataUncheckedCreateWithoutModerationScoutInput>
  connectOrCreate?: Prisma.ModerationScoutReportModalDataCreateOrConnectWithoutModerationScoutInput
  upsert?: Prisma.ModerationScoutReportModalDataUpsertWithoutModerationScoutInput
  disconnect?: Prisma.ModerationScoutReportModalDataWhereInput | boolean
  delete?: Prisma.ModerationScoutReportModalDataWhereInput | boolean
  connect?: Prisma.ModerationScoutReportModalDataWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ModerationScoutReportModalDataUpdateToOneWithWhereWithoutModerationScoutInput, Prisma.ModerationScoutReportModalDataUpdateWithoutModerationScoutInput>, Prisma.ModerationScoutReportModalDataUncheckedUpdateWithoutModerationScoutInput>
}

export type ModerationScoutReportModalDataUncheckedUpdateOneWithoutModerationScoutNestedInput = {
  create?: Prisma.XOR<Prisma.ModerationScoutReportModalDataCreateWithoutModerationScoutInput, Prisma.ModerationScoutReportModalDataUncheckedCreateWithoutModerationScoutInput>
  connectOrCreate?: Prisma.ModerationScoutReportModalDataCreateOrConnectWithoutModerationScoutInput
  upsert?: Prisma.ModerationScoutReportModalDataUpsertWithoutModerationScoutInput
  disconnect?: Prisma.ModerationScoutReportModalDataWhereInput | boolean
  delete?: Prisma.ModerationScoutReportModalDataWhereInput | boolean
  connect?: Prisma.ModerationScoutReportModalDataWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ModerationScoutReportModalDataUpdateToOneWithWhereWithoutModerationScoutInput, Prisma.ModerationScoutReportModalDataUpdateWithoutModerationScoutInput>, Prisma.ModerationScoutReportModalDataUncheckedUpdateWithoutModerationScoutInput>
}

export type ModerationScoutReportModalDataCreateWithoutModerationScoutInput = {
  Name: string
  Placeholder?: string | null
  Type: number
  MinLength?: number | null
  MaxLength?: number | null
  Required: boolean
  InteractionType: string
  ModerationScoutId: string
}

export type ModerationScoutReportModalDataUncheckedCreateWithoutModerationScoutInput = {
  Id?: number
  Name: string
  Placeholder?: string | null
  Type: number
  MinLength?: number | null
  MaxLength?: number | null
  Required: boolean
  InteractionType: string
  ModerationScoutId: string
}

export type ModerationScoutReportModalDataCreateOrConnectWithoutModerationScoutInput = {
  where: Prisma.ModerationScoutReportModalDataWhereUniqueInput
  create: Prisma.XOR<Prisma.ModerationScoutReportModalDataCreateWithoutModerationScoutInput, Prisma.ModerationScoutReportModalDataUncheckedCreateWithoutModerationScoutInput>
}

export type ModerationScoutReportModalDataUpsertWithoutModerationScoutInput = {
  update: Prisma.XOR<Prisma.ModerationScoutReportModalDataUpdateWithoutModerationScoutInput, Prisma.ModerationScoutReportModalDataUncheckedUpdateWithoutModerationScoutInput>
  create: Prisma.XOR<Prisma.ModerationScoutReportModalDataCreateWithoutModerationScoutInput, Prisma.ModerationScoutReportModalDataUncheckedCreateWithoutModerationScoutInput>
  where?: Prisma.ModerationScoutReportModalDataWhereInput
}

export type ModerationScoutReportModalDataUpdateToOneWithWhereWithoutModerationScoutInput = {
  where?: Prisma.ModerationScoutReportModalDataWhereInput
  data: Prisma.XOR<Prisma.ModerationScoutReportModalDataUpdateWithoutModerationScoutInput, Prisma.ModerationScoutReportModalDataUncheckedUpdateWithoutModerationScoutInput>
}

export type ModerationScoutReportModalDataUpdateWithoutModerationScoutInput = {
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  Placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Type?: Prisma.IntFieldUpdateOperationsInput | number
  MinLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  MaxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  InteractionType?: Prisma.StringFieldUpdateOperationsInput | string
  ModerationScoutId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ModerationScoutReportModalDataUncheckedUpdateWithoutModerationScoutInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  Name?: Prisma.StringFieldUpdateOperationsInput | string
  Placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Type?: Prisma.IntFieldUpdateOperationsInput | number
  MinLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  MaxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  Required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  InteractionType?: Prisma.StringFieldUpdateOperationsInput | string
  ModerationScoutId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ModerationScoutReportModalDataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UUID?: boolean
  Name?: boolean
  Placeholder?: boolean
  Type?: boolean
  MinLength?: boolean
  MaxLength?: boolean
  Required?: boolean
  InteractionType?: boolean
  ModerationScoutId?: boolean
  ModerationScout?: boolean | Prisma.ModerationScoutDefaultArgs<ExtArgs>
}, ExtArgs["result"]["moderationScoutReportModalData"]>

export type ModerationScoutReportModalDataSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UUID?: boolean
  Name?: boolean
  Placeholder?: boolean
  Type?: boolean
  MinLength?: boolean
  MaxLength?: boolean
  Required?: boolean
  InteractionType?: boolean
  ModerationScoutId?: boolean
  ModerationScout?: boolean | Prisma.ModerationScoutDefaultArgs<ExtArgs>
}, ExtArgs["result"]["moderationScoutReportModalData"]>

export type ModerationScoutReportModalDataSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UUID?: boolean
  Name?: boolean
  Placeholder?: boolean
  Type?: boolean
  MinLength?: boolean
  MaxLength?: boolean
  Required?: boolean
  InteractionType?: boolean
  ModerationScoutId?: boolean
  ModerationScout?: boolean | Prisma.ModerationScoutDefaultArgs<ExtArgs>
}, ExtArgs["result"]["moderationScoutReportModalData"]>

export type ModerationScoutReportModalDataSelectScalar = {
  Id?: boolean
  UUID?: boolean
  Name?: boolean
  Placeholder?: boolean
  Type?: boolean
  MinLength?: boolean
  MaxLength?: boolean
  Required?: boolean
  InteractionType?: boolean
  ModerationScoutId?: boolean
}

export type ModerationScoutReportModalDataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Id" | "UUID" | "Name" | "Placeholder" | "Type" | "MinLength" | "MaxLength" | "Required" | "InteractionType" | "ModerationScoutId", ExtArgs["result"]["moderationScoutReportModalData"]>
export type ModerationScoutReportModalDataInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ModerationScout?: boolean | Prisma.ModerationScoutDefaultArgs<ExtArgs>
}
export type ModerationScoutReportModalDataIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ModerationScout?: boolean | Prisma.ModerationScoutDefaultArgs<ExtArgs>
}
export type ModerationScoutReportModalDataIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ModerationScout?: boolean | Prisma.ModerationScoutDefaultArgs<ExtArgs>
}

export type $ModerationScoutReportModalDataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ModerationScoutReportModalData"
  objects: {
    ModerationScout: Prisma.$ModerationScoutPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Id: number
    UUID: string
    Name: string
    Placeholder: string | null
    Type: number
    MinLength: number | null
    MaxLength: number | null
    Required: boolean
    InteractionType: string
    ModerationScoutId: string
  }, ExtArgs["result"]["moderationScoutReportModalData"]>
  composites: {}
}

export type ModerationScoutReportModalDataGetPayload<S extends boolean | null | undefined | ModerationScoutReportModalDataDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload, S>

export type ModerationScoutReportModalDataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ModerationScoutReportModalDataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ModerationScoutReportModalDataCountAggregateInputType | true
  }

export interface ModerationScoutReportModalDataDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ModerationScoutReportModalData'], meta: { name: 'ModerationScoutReportModalData' } }
  /**
   * Find zero or one ModerationScoutReportModalData that matches the filter.
   * @param {ModerationScoutReportModalDataFindUniqueArgs} args - Arguments to find a ModerationScoutReportModalData
   * @example
   * // Get one ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ModerationScoutReportModalDataFindUniqueArgs>(args: Prisma.SelectSubset<T, ModerationScoutReportModalDataFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ModerationScoutReportModalDataClient<runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ModerationScoutReportModalData that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ModerationScoutReportModalDataFindUniqueOrThrowArgs} args - Arguments to find a ModerationScoutReportModalData
   * @example
   * // Get one ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ModerationScoutReportModalDataFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ModerationScoutReportModalDataFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModerationScoutReportModalDataClient<runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModerationScoutReportModalData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationScoutReportModalDataFindFirstArgs} args - Arguments to find a ModerationScoutReportModalData
   * @example
   * // Get one ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ModerationScoutReportModalDataFindFirstArgs>(args?: Prisma.SelectSubset<T, ModerationScoutReportModalDataFindFirstArgs<ExtArgs>>): Prisma.Prisma__ModerationScoutReportModalDataClient<runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModerationScoutReportModalData that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationScoutReportModalDataFindFirstOrThrowArgs} args - Arguments to find a ModerationScoutReportModalData
   * @example
   * // Get one ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ModerationScoutReportModalDataFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ModerationScoutReportModalDataFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModerationScoutReportModalDataClient<runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ModerationScoutReportModalData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationScoutReportModalDataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.findMany()
   * 
   * // Get first 10 ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.findMany({ take: 10 })
   * 
   * // Only select the `Id`
   * const moderationScoutReportModalDataWithIdOnly = await prisma.moderationScoutReportModalData.findMany({ select: { Id: true } })
   * 
   */
  findMany<T extends ModerationScoutReportModalDataFindManyArgs>(args?: Prisma.SelectSubset<T, ModerationScoutReportModalDataFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ModerationScoutReportModalData.
   * @param {ModerationScoutReportModalDataCreateArgs} args - Arguments to create a ModerationScoutReportModalData.
   * @example
   * // Create one ModerationScoutReportModalData
   * const ModerationScoutReportModalData = await prisma.moderationScoutReportModalData.create({
   *   data: {
   *     // ... data to create a ModerationScoutReportModalData
   *   }
   * })
   * 
   */
  create<T extends ModerationScoutReportModalDataCreateArgs>(args: Prisma.SelectSubset<T, ModerationScoutReportModalDataCreateArgs<ExtArgs>>): Prisma.Prisma__ModerationScoutReportModalDataClient<runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ModerationScoutReportModalData.
   * @param {ModerationScoutReportModalDataCreateManyArgs} args - Arguments to create many ModerationScoutReportModalData.
   * @example
   * // Create many ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ModerationScoutReportModalDataCreateManyArgs>(args?: Prisma.SelectSubset<T, ModerationScoutReportModalDataCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ModerationScoutReportModalData and returns the data saved in the database.
   * @param {ModerationScoutReportModalDataCreateManyAndReturnArgs} args - Arguments to create many ModerationScoutReportModalData.
   * @example
   * // Create many ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ModerationScoutReportModalData and only return the `Id`
   * const moderationScoutReportModalDataWithIdOnly = await prisma.moderationScoutReportModalData.createManyAndReturn({
   *   select: { Id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ModerationScoutReportModalDataCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ModerationScoutReportModalDataCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ModerationScoutReportModalData.
   * @param {ModerationScoutReportModalDataDeleteArgs} args - Arguments to delete one ModerationScoutReportModalData.
   * @example
   * // Delete one ModerationScoutReportModalData
   * const ModerationScoutReportModalData = await prisma.moderationScoutReportModalData.delete({
   *   where: {
   *     // ... filter to delete one ModerationScoutReportModalData
   *   }
   * })
   * 
   */
  delete<T extends ModerationScoutReportModalDataDeleteArgs>(args: Prisma.SelectSubset<T, ModerationScoutReportModalDataDeleteArgs<ExtArgs>>): Prisma.Prisma__ModerationScoutReportModalDataClient<runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ModerationScoutReportModalData.
   * @param {ModerationScoutReportModalDataUpdateArgs} args - Arguments to update one ModerationScoutReportModalData.
   * @example
   * // Update one ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ModerationScoutReportModalDataUpdateArgs>(args: Prisma.SelectSubset<T, ModerationScoutReportModalDataUpdateArgs<ExtArgs>>): Prisma.Prisma__ModerationScoutReportModalDataClient<runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ModerationScoutReportModalData.
   * @param {ModerationScoutReportModalDataDeleteManyArgs} args - Arguments to filter ModerationScoutReportModalData to delete.
   * @example
   * // Delete a few ModerationScoutReportModalData
   * const { count } = await prisma.moderationScoutReportModalData.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ModerationScoutReportModalDataDeleteManyArgs>(args?: Prisma.SelectSubset<T, ModerationScoutReportModalDataDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModerationScoutReportModalData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationScoutReportModalDataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ModerationScoutReportModalDataUpdateManyArgs>(args: Prisma.SelectSubset<T, ModerationScoutReportModalDataUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModerationScoutReportModalData and returns the data updated in the database.
   * @param {ModerationScoutReportModalDataUpdateManyAndReturnArgs} args - Arguments to update many ModerationScoutReportModalData.
   * @example
   * // Update many ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ModerationScoutReportModalData and only return the `Id`
   * const moderationScoutReportModalDataWithIdOnly = await prisma.moderationScoutReportModalData.updateManyAndReturn({
   *   select: { Id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ModerationScoutReportModalDataUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ModerationScoutReportModalDataUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ModerationScoutReportModalData.
   * @param {ModerationScoutReportModalDataUpsertArgs} args - Arguments to update or create a ModerationScoutReportModalData.
   * @example
   * // Update or create a ModerationScoutReportModalData
   * const moderationScoutReportModalData = await prisma.moderationScoutReportModalData.upsert({
   *   create: {
   *     // ... data to create a ModerationScoutReportModalData
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ModerationScoutReportModalData we want to update
   *   }
   * })
   */
  upsert<T extends ModerationScoutReportModalDataUpsertArgs>(args: Prisma.SelectSubset<T, ModerationScoutReportModalDataUpsertArgs<ExtArgs>>): Prisma.Prisma__ModerationScoutReportModalDataClient<runtime.Types.Result.GetResult<Prisma.$ModerationScoutReportModalDataPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ModerationScoutReportModalData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationScoutReportModalDataCountArgs} args - Arguments to filter ModerationScoutReportModalData to count.
   * @example
   * // Count the number of ModerationScoutReportModalData
   * const count = await prisma.moderationScoutReportModalData.count({
   *   where: {
   *     // ... the filter for the ModerationScoutReportModalData we want to count
   *   }
   * })
  **/
  count<T extends ModerationScoutReportModalDataCountArgs>(
    args?: Prisma.Subset<T, ModerationScoutReportModalDataCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ModerationScoutReportModalDataCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ModerationScoutReportModalData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationScoutReportModalDataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ModerationScoutReportModalDataAggregateArgs>(args: Prisma.Subset<T, ModerationScoutReportModalDataAggregateArgs>): Prisma.PrismaPromise<GetModerationScoutReportModalDataAggregateType<T>>

  /**
   * Group by ModerationScoutReportModalData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationScoutReportModalDataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ModerationScoutReportModalDataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ModerationScoutReportModalDataGroupByArgs['orderBy'] }
      : { orderBy?: ModerationScoutReportModalDataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ModerationScoutReportModalDataGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetModerationScoutReportModalDataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ModerationScoutReportModalData model
 */
readonly fields: ModerationScoutReportModalDataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ModerationScoutReportModalData.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ModerationScoutReportModalDataClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ModerationScout<T extends Prisma.ModerationScoutDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ModerationScoutDefaultArgs<ExtArgs>>): Prisma.Prisma__ModerationScoutClient<runtime.Types.Result.GetResult<Prisma.$ModerationScoutPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ModerationScoutReportModalData model
 */
export interface ModerationScoutReportModalDataFieldRefs {
  readonly Id: Prisma.FieldRef<"ModerationScoutReportModalData", 'Int'>
  readonly UUID: Prisma.FieldRef<"ModerationScoutReportModalData", 'String'>
  readonly Name: Prisma.FieldRef<"ModerationScoutReportModalData", 'String'>
  readonly Placeholder: Prisma.FieldRef<"ModerationScoutReportModalData", 'String'>
  readonly Type: Prisma.FieldRef<"ModerationScoutReportModalData", 'Int'>
  readonly MinLength: Prisma.FieldRef<"ModerationScoutReportModalData", 'Int'>
  readonly MaxLength: Prisma.FieldRef<"ModerationScoutReportModalData", 'Int'>
  readonly Required: Prisma.FieldRef<"ModerationScoutReportModalData", 'Boolean'>
  readonly InteractionType: Prisma.FieldRef<"ModerationScoutReportModalData", 'String'>
  readonly ModerationScoutId: Prisma.FieldRef<"ModerationScoutReportModalData", 'String'>
}
    

// Custom InputTypes
/**
 * ModerationScoutReportModalData findUnique
 */
export type ModerationScoutReportModalDataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataInclude<ExtArgs> | null
  /**
   * Filter, which ModerationScoutReportModalData to fetch.
   */
  where: Prisma.ModerationScoutReportModalDataWhereUniqueInput
}

/**
 * ModerationScoutReportModalData findUniqueOrThrow
 */
export type ModerationScoutReportModalDataFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataInclude<ExtArgs> | null
  /**
   * Filter, which ModerationScoutReportModalData to fetch.
   */
  where: Prisma.ModerationScoutReportModalDataWhereUniqueInput
}

/**
 * ModerationScoutReportModalData findFirst
 */
export type ModerationScoutReportModalDataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataInclude<ExtArgs> | null
  /**
   * Filter, which ModerationScoutReportModalData to fetch.
   */
  where?: Prisma.ModerationScoutReportModalDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationScoutReportModalData to fetch.
   */
  orderBy?: Prisma.ModerationScoutReportModalDataOrderByWithRelationInput | Prisma.ModerationScoutReportModalDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModerationScoutReportModalData.
   */
  cursor?: Prisma.ModerationScoutReportModalDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationScoutReportModalData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationScoutReportModalData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModerationScoutReportModalData.
   */
  distinct?: Prisma.ModerationScoutReportModalDataScalarFieldEnum | Prisma.ModerationScoutReportModalDataScalarFieldEnum[]
}

/**
 * ModerationScoutReportModalData findFirstOrThrow
 */
export type ModerationScoutReportModalDataFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataInclude<ExtArgs> | null
  /**
   * Filter, which ModerationScoutReportModalData to fetch.
   */
  where?: Prisma.ModerationScoutReportModalDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationScoutReportModalData to fetch.
   */
  orderBy?: Prisma.ModerationScoutReportModalDataOrderByWithRelationInput | Prisma.ModerationScoutReportModalDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModerationScoutReportModalData.
   */
  cursor?: Prisma.ModerationScoutReportModalDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationScoutReportModalData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationScoutReportModalData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModerationScoutReportModalData.
   */
  distinct?: Prisma.ModerationScoutReportModalDataScalarFieldEnum | Prisma.ModerationScoutReportModalDataScalarFieldEnum[]
}

/**
 * ModerationScoutReportModalData findMany
 */
export type ModerationScoutReportModalDataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataInclude<ExtArgs> | null
  /**
   * Filter, which ModerationScoutReportModalData to fetch.
   */
  where?: Prisma.ModerationScoutReportModalDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationScoutReportModalData to fetch.
   */
  orderBy?: Prisma.ModerationScoutReportModalDataOrderByWithRelationInput | Prisma.ModerationScoutReportModalDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ModerationScoutReportModalData.
   */
  cursor?: Prisma.ModerationScoutReportModalDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationScoutReportModalData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationScoutReportModalData.
   */
  skip?: number
  distinct?: Prisma.ModerationScoutReportModalDataScalarFieldEnum | Prisma.ModerationScoutReportModalDataScalarFieldEnum[]
}

/**
 * ModerationScoutReportModalData create
 */
export type ModerationScoutReportModalDataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataInclude<ExtArgs> | null
  /**
   * The data needed to create a ModerationScoutReportModalData.
   */
  data: Prisma.XOR<Prisma.ModerationScoutReportModalDataCreateInput, Prisma.ModerationScoutReportModalDataUncheckedCreateInput>
}

/**
 * ModerationScoutReportModalData createMany
 */
export type ModerationScoutReportModalDataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ModerationScoutReportModalData.
   */
  data: Prisma.ModerationScoutReportModalDataCreateManyInput | Prisma.ModerationScoutReportModalDataCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ModerationScoutReportModalData createManyAndReturn
 */
export type ModerationScoutReportModalDataCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * The data used to create many ModerationScoutReportModalData.
   */
  data: Prisma.ModerationScoutReportModalDataCreateManyInput | Prisma.ModerationScoutReportModalDataCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ModerationScoutReportModalData update
 */
export type ModerationScoutReportModalDataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataInclude<ExtArgs> | null
  /**
   * The data needed to update a ModerationScoutReportModalData.
   */
  data: Prisma.XOR<Prisma.ModerationScoutReportModalDataUpdateInput, Prisma.ModerationScoutReportModalDataUncheckedUpdateInput>
  /**
   * Choose, which ModerationScoutReportModalData to update.
   */
  where: Prisma.ModerationScoutReportModalDataWhereUniqueInput
}

/**
 * ModerationScoutReportModalData updateMany
 */
export type ModerationScoutReportModalDataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ModerationScoutReportModalData.
   */
  data: Prisma.XOR<Prisma.ModerationScoutReportModalDataUpdateManyMutationInput, Prisma.ModerationScoutReportModalDataUncheckedUpdateManyInput>
  /**
   * Filter which ModerationScoutReportModalData to update
   */
  where?: Prisma.ModerationScoutReportModalDataWhereInput
  /**
   * Limit how many ModerationScoutReportModalData to update.
   */
  limit?: number
}

/**
 * ModerationScoutReportModalData updateManyAndReturn
 */
export type ModerationScoutReportModalDataUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * The data used to update ModerationScoutReportModalData.
   */
  data: Prisma.XOR<Prisma.ModerationScoutReportModalDataUpdateManyMutationInput, Prisma.ModerationScoutReportModalDataUncheckedUpdateManyInput>
  /**
   * Filter which ModerationScoutReportModalData to update
   */
  where?: Prisma.ModerationScoutReportModalDataWhereInput
  /**
   * Limit how many ModerationScoutReportModalData to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ModerationScoutReportModalData upsert
 */
export type ModerationScoutReportModalDataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataInclude<ExtArgs> | null
  /**
   * The filter to search for the ModerationScoutReportModalData to update in case it exists.
   */
  where: Prisma.ModerationScoutReportModalDataWhereUniqueInput
  /**
   * In case the ModerationScoutReportModalData found by the `where` argument doesn't exist, create a new ModerationScoutReportModalData with this data.
   */
  create: Prisma.XOR<Prisma.ModerationScoutReportModalDataCreateInput, Prisma.ModerationScoutReportModalDataUncheckedCreateInput>
  /**
   * In case the ModerationScoutReportModalData was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ModerationScoutReportModalDataUpdateInput, Prisma.ModerationScoutReportModalDataUncheckedUpdateInput>
}

/**
 * ModerationScoutReportModalData delete
 */
export type ModerationScoutReportModalDataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataInclude<ExtArgs> | null
  /**
   * Filter which ModerationScoutReportModalData to delete.
   */
  where: Prisma.ModerationScoutReportModalDataWhereUniqueInput
}

/**
 * ModerationScoutReportModalData deleteMany
 */
export type ModerationScoutReportModalDataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModerationScoutReportModalData to delete
   */
  where?: Prisma.ModerationScoutReportModalDataWhereInput
  /**
   * Limit how many ModerationScoutReportModalData to delete.
   */
  limit?: number
}

/**
 * ModerationScoutReportModalData without action
 */
export type ModerationScoutReportModalDataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationScoutReportModalData
   */
  select?: Prisma.ModerationScoutReportModalDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationScoutReportModalData
   */
  omit?: Prisma.ModerationScoutReportModalDataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationScoutReportModalDataInclude<ExtArgs> | null
}
