
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SyncedChannelLinkMessages` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model SyncedChannelLinkMessages
 * 
 */
export type SyncedChannelLinkMessagesModel = runtime.Types.Result.DefaultSelection<Prisma.$SyncedChannelLinkMessagesPayload>

export type AggregateSyncedChannelLinkMessages = {
  _count: SyncedChannelLinkMessagesCountAggregateOutputType | null
  _avg: SyncedChannelLinkMessagesAvgAggregateOutputType | null
  _sum: SyncedChannelLinkMessagesSumAggregateOutputType | null
  _min: SyncedChannelLinkMessagesMinAggregateOutputType | null
  _max: SyncedChannelLinkMessagesMaxAggregateOutputType | null
}

export type SyncedChannelLinkMessagesAvgAggregateOutputType = {
  Id: number | null
}

export type SyncedChannelLinkMessagesSumAggregateOutputType = {
  Id: number | null
}

export type SyncedChannelLinkMessagesMinAggregateOutputType = {
  Id: number | null
  GuildId: string | null
  UserMessageId: string | null
  WebhookMessageId: string | null
  WebhookUrl: string | null
  ChannelId: string | null
  ChannelLinkId: string | null
}

export type SyncedChannelLinkMessagesMaxAggregateOutputType = {
  Id: number | null
  GuildId: string | null
  UserMessageId: string | null
  WebhookMessageId: string | null
  WebhookUrl: string | null
  ChannelId: string | null
  ChannelLinkId: string | null
}

export type SyncedChannelLinkMessagesCountAggregateOutputType = {
  Id: number
  GuildId: number
  UserMessageId: number
  WebhookMessageId: number
  WebhookUrl: number
  ChannelId: number
  ChannelLinkId: number
  _all: number
}


export type SyncedChannelLinkMessagesAvgAggregateInputType = {
  Id?: true
}

export type SyncedChannelLinkMessagesSumAggregateInputType = {
  Id?: true
}

export type SyncedChannelLinkMessagesMinAggregateInputType = {
  Id?: true
  GuildId?: true
  UserMessageId?: true
  WebhookMessageId?: true
  WebhookUrl?: true
  ChannelId?: true
  ChannelLinkId?: true
}

export type SyncedChannelLinkMessagesMaxAggregateInputType = {
  Id?: true
  GuildId?: true
  UserMessageId?: true
  WebhookMessageId?: true
  WebhookUrl?: true
  ChannelId?: true
  ChannelLinkId?: true
}

export type SyncedChannelLinkMessagesCountAggregateInputType = {
  Id?: true
  GuildId?: true
  UserMessageId?: true
  WebhookMessageId?: true
  WebhookUrl?: true
  ChannelId?: true
  ChannelLinkId?: true
  _all?: true
}

export type SyncedChannelLinkMessagesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SyncedChannelLinkMessages to aggregate.
   */
  where?: Prisma.SyncedChannelLinkMessagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncedChannelLinkMessages to fetch.
   */
  orderBy?: Prisma.SyncedChannelLinkMessagesOrderByWithRelationInput | Prisma.SyncedChannelLinkMessagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncedChannelLinkMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncedChannelLinkMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SyncedChannelLinkMessages
  **/
  _count?: true | SyncedChannelLinkMessagesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SyncedChannelLinkMessagesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SyncedChannelLinkMessagesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SyncedChannelLinkMessagesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SyncedChannelLinkMessagesMaxAggregateInputType
}

export type GetSyncedChannelLinkMessagesAggregateType<T extends SyncedChannelLinkMessagesAggregateArgs> = {
      [P in keyof T & keyof AggregateSyncedChannelLinkMessages]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSyncedChannelLinkMessages[P]>
    : Prisma.GetScalarType<T[P], AggregateSyncedChannelLinkMessages[P]>
}




export type SyncedChannelLinkMessagesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SyncedChannelLinkMessagesWhereInput
  orderBy?: Prisma.SyncedChannelLinkMessagesOrderByWithAggregationInput | Prisma.SyncedChannelLinkMessagesOrderByWithAggregationInput[]
  by: Prisma.SyncedChannelLinkMessagesScalarFieldEnum[] | Prisma.SyncedChannelLinkMessagesScalarFieldEnum
  having?: Prisma.SyncedChannelLinkMessagesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SyncedChannelLinkMessagesCountAggregateInputType | true
  _avg?: SyncedChannelLinkMessagesAvgAggregateInputType
  _sum?: SyncedChannelLinkMessagesSumAggregateInputType
  _min?: SyncedChannelLinkMessagesMinAggregateInputType
  _max?: SyncedChannelLinkMessagesMaxAggregateInputType
}

export type SyncedChannelLinkMessagesGroupByOutputType = {
  Id: number
  GuildId: string
  UserMessageId: string
  WebhookMessageId: string
  WebhookUrl: string
  ChannelId: string
  ChannelLinkId: string
  _count: SyncedChannelLinkMessagesCountAggregateOutputType | null
  _avg: SyncedChannelLinkMessagesAvgAggregateOutputType | null
  _sum: SyncedChannelLinkMessagesSumAggregateOutputType | null
  _min: SyncedChannelLinkMessagesMinAggregateOutputType | null
  _max: SyncedChannelLinkMessagesMaxAggregateOutputType | null
}

type GetSyncedChannelLinkMessagesGroupByPayload<T extends SyncedChannelLinkMessagesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SyncedChannelLinkMessagesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SyncedChannelLinkMessagesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SyncedChannelLinkMessagesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SyncedChannelLinkMessagesGroupByOutputType[P]>
      }
    >
  >



export type SyncedChannelLinkMessagesWhereInput = {
  AND?: Prisma.SyncedChannelLinkMessagesWhereInput | Prisma.SyncedChannelLinkMessagesWhereInput[]
  OR?: Prisma.SyncedChannelLinkMessagesWhereInput[]
  NOT?: Prisma.SyncedChannelLinkMessagesWhereInput | Prisma.SyncedChannelLinkMessagesWhereInput[]
  Id?: Prisma.IntFilter<"SyncedChannelLinkMessages"> | number
  GuildId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  UserMessageId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  WebhookMessageId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  WebhookUrl?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  ChannelId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  ChannelLinkId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  ChannelLinks?: Prisma.XOR<Prisma.GuildChannelLinksScalarRelationFilter, Prisma.GuildChannelLinksWhereInput>
}

export type SyncedChannelLinkMessagesOrderByWithRelationInput = {
  Id?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  UserMessageId?: Prisma.SortOrder
  WebhookMessageId?: Prisma.SortOrder
  WebhookUrl?: Prisma.SortOrder
  ChannelId?: Prisma.SortOrder
  ChannelLinkId?: Prisma.SortOrder
  ChannelLinks?: Prisma.GuildChannelLinksOrderByWithRelationInput
}

export type SyncedChannelLinkMessagesWhereUniqueInput = Prisma.AtLeast<{
  Id?: number
  AND?: Prisma.SyncedChannelLinkMessagesWhereInput | Prisma.SyncedChannelLinkMessagesWhereInput[]
  OR?: Prisma.SyncedChannelLinkMessagesWhereInput[]
  NOT?: Prisma.SyncedChannelLinkMessagesWhereInput | Prisma.SyncedChannelLinkMessagesWhereInput[]
  GuildId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  UserMessageId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  WebhookMessageId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  WebhookUrl?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  ChannelId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  ChannelLinkId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  ChannelLinks?: Prisma.XOR<Prisma.GuildChannelLinksScalarRelationFilter, Prisma.GuildChannelLinksWhereInput>
}, "Id">

export type SyncedChannelLinkMessagesOrderByWithAggregationInput = {
  Id?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  UserMessageId?: Prisma.SortOrder
  WebhookMessageId?: Prisma.SortOrder
  WebhookUrl?: Prisma.SortOrder
  ChannelId?: Prisma.SortOrder
  ChannelLinkId?: Prisma.SortOrder
  _count?: Prisma.SyncedChannelLinkMessagesCountOrderByAggregateInput
  _avg?: Prisma.SyncedChannelLinkMessagesAvgOrderByAggregateInput
  _max?: Prisma.SyncedChannelLinkMessagesMaxOrderByAggregateInput
  _min?: Prisma.SyncedChannelLinkMessagesMinOrderByAggregateInput
  _sum?: Prisma.SyncedChannelLinkMessagesSumOrderByAggregateInput
}

export type SyncedChannelLinkMessagesScalarWhereWithAggregatesInput = {
  AND?: Prisma.SyncedChannelLinkMessagesScalarWhereWithAggregatesInput | Prisma.SyncedChannelLinkMessagesScalarWhereWithAggregatesInput[]
  OR?: Prisma.SyncedChannelLinkMessagesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SyncedChannelLinkMessagesScalarWhereWithAggregatesInput | Prisma.SyncedChannelLinkMessagesScalarWhereWithAggregatesInput[]
  Id?: Prisma.IntWithAggregatesFilter<"SyncedChannelLinkMessages"> | number
  GuildId?: Prisma.StringWithAggregatesFilter<"SyncedChannelLinkMessages"> | string
  UserMessageId?: Prisma.StringWithAggregatesFilter<"SyncedChannelLinkMessages"> | string
  WebhookMessageId?: Prisma.StringWithAggregatesFilter<"SyncedChannelLinkMessages"> | string
  WebhookUrl?: Prisma.StringWithAggregatesFilter<"SyncedChannelLinkMessages"> | string
  ChannelId?: Prisma.StringWithAggregatesFilter<"SyncedChannelLinkMessages"> | string
  ChannelLinkId?: Prisma.StringWithAggregatesFilter<"SyncedChannelLinkMessages"> | string
}

export type SyncedChannelLinkMessagesCreateInput = {
  GuildId: string
  UserMessageId: string
  WebhookMessageId: string
  WebhookUrl: string
  ChannelId: string
  ChannelLinks: Prisma.GuildChannelLinksCreateNestedOneWithoutSyncedChannelLinkMessageInput
}

export type SyncedChannelLinkMessagesUncheckedCreateInput = {
  Id?: number
  GuildId: string
  UserMessageId: string
  WebhookMessageId: string
  WebhookUrl: string
  ChannelId: string
  ChannelLinkId: string
}

export type SyncedChannelLinkMessagesUpdateInput = {
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  UserMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookUrl?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelLinks?: Prisma.GuildChannelLinksUpdateOneRequiredWithoutSyncedChannelLinkMessageNestedInput
}

export type SyncedChannelLinkMessagesUncheckedUpdateInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  UserMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookUrl?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelLinkId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SyncedChannelLinkMessagesCreateManyInput = {
  Id?: number
  GuildId: string
  UserMessageId: string
  WebhookMessageId: string
  WebhookUrl: string
  ChannelId: string
  ChannelLinkId: string
}

export type SyncedChannelLinkMessagesUpdateManyMutationInput = {
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  UserMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookUrl?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SyncedChannelLinkMessagesUncheckedUpdateManyInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  UserMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookUrl?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelLinkId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SyncedChannelLinkMessagesListRelationFilter = {
  every?: Prisma.SyncedChannelLinkMessagesWhereInput
  some?: Prisma.SyncedChannelLinkMessagesWhereInput
  none?: Prisma.SyncedChannelLinkMessagesWhereInput
}

export type SyncedChannelLinkMessagesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SyncedChannelLinkMessagesCountOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  UserMessageId?: Prisma.SortOrder
  WebhookMessageId?: Prisma.SortOrder
  WebhookUrl?: Prisma.SortOrder
  ChannelId?: Prisma.SortOrder
  ChannelLinkId?: Prisma.SortOrder
}

export type SyncedChannelLinkMessagesAvgOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type SyncedChannelLinkMessagesMaxOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  UserMessageId?: Prisma.SortOrder
  WebhookMessageId?: Prisma.SortOrder
  WebhookUrl?: Prisma.SortOrder
  ChannelId?: Prisma.SortOrder
  ChannelLinkId?: Prisma.SortOrder
}

export type SyncedChannelLinkMessagesMinOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  UserMessageId?: Prisma.SortOrder
  WebhookMessageId?: Prisma.SortOrder
  WebhookUrl?: Prisma.SortOrder
  ChannelId?: Prisma.SortOrder
  ChannelLinkId?: Prisma.SortOrder
}

export type SyncedChannelLinkMessagesSumOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type SyncedChannelLinkMessagesCreateNestedManyWithoutChannelLinksInput = {
  create?: Prisma.XOR<Prisma.SyncedChannelLinkMessagesCreateWithoutChannelLinksInput, Prisma.SyncedChannelLinkMessagesUncheckedCreateWithoutChannelLinksInput> | Prisma.SyncedChannelLinkMessagesCreateWithoutChannelLinksInput[] | Prisma.SyncedChannelLinkMessagesUncheckedCreateWithoutChannelLinksInput[]
  connectOrCreate?: Prisma.SyncedChannelLinkMessagesCreateOrConnectWithoutChannelLinksInput | Prisma.SyncedChannelLinkMessagesCreateOrConnectWithoutChannelLinksInput[]
  createMany?: Prisma.SyncedChannelLinkMessagesCreateManyChannelLinksInputEnvelope
  connect?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput | Prisma.SyncedChannelLinkMessagesWhereUniqueInput[]
}

export type SyncedChannelLinkMessagesUncheckedCreateNestedManyWithoutChannelLinksInput = {
  create?: Prisma.XOR<Prisma.SyncedChannelLinkMessagesCreateWithoutChannelLinksInput, Prisma.SyncedChannelLinkMessagesUncheckedCreateWithoutChannelLinksInput> | Prisma.SyncedChannelLinkMessagesCreateWithoutChannelLinksInput[] | Prisma.SyncedChannelLinkMessagesUncheckedCreateWithoutChannelLinksInput[]
  connectOrCreate?: Prisma.SyncedChannelLinkMessagesCreateOrConnectWithoutChannelLinksInput | Prisma.SyncedChannelLinkMessagesCreateOrConnectWithoutChannelLinksInput[]
  createMany?: Prisma.SyncedChannelLinkMessagesCreateManyChannelLinksInputEnvelope
  connect?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput | Prisma.SyncedChannelLinkMessagesWhereUniqueInput[]
}

export type SyncedChannelLinkMessagesUpdateManyWithoutChannelLinksNestedInput = {
  create?: Prisma.XOR<Prisma.SyncedChannelLinkMessagesCreateWithoutChannelLinksInput, Prisma.SyncedChannelLinkMessagesUncheckedCreateWithoutChannelLinksInput> | Prisma.SyncedChannelLinkMessagesCreateWithoutChannelLinksInput[] | Prisma.SyncedChannelLinkMessagesUncheckedCreateWithoutChannelLinksInput[]
  connectOrCreate?: Prisma.SyncedChannelLinkMessagesCreateOrConnectWithoutChannelLinksInput | Prisma.SyncedChannelLinkMessagesCreateOrConnectWithoutChannelLinksInput[]
  upsert?: Prisma.SyncedChannelLinkMessagesUpsertWithWhereUniqueWithoutChannelLinksInput | Prisma.SyncedChannelLinkMessagesUpsertWithWhereUniqueWithoutChannelLinksInput[]
  createMany?: Prisma.SyncedChannelLinkMessagesCreateManyChannelLinksInputEnvelope
  set?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput | Prisma.SyncedChannelLinkMessagesWhereUniqueInput[]
  disconnect?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput | Prisma.SyncedChannelLinkMessagesWhereUniqueInput[]
  delete?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput | Prisma.SyncedChannelLinkMessagesWhereUniqueInput[]
  connect?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput | Prisma.SyncedChannelLinkMessagesWhereUniqueInput[]
  update?: Prisma.SyncedChannelLinkMessagesUpdateWithWhereUniqueWithoutChannelLinksInput | Prisma.SyncedChannelLinkMessagesUpdateWithWhereUniqueWithoutChannelLinksInput[]
  updateMany?: Prisma.SyncedChannelLinkMessagesUpdateManyWithWhereWithoutChannelLinksInput | Prisma.SyncedChannelLinkMessagesUpdateManyWithWhereWithoutChannelLinksInput[]
  deleteMany?: Prisma.SyncedChannelLinkMessagesScalarWhereInput | Prisma.SyncedChannelLinkMessagesScalarWhereInput[]
}

export type SyncedChannelLinkMessagesUncheckedUpdateManyWithoutChannelLinksNestedInput = {
  create?: Prisma.XOR<Prisma.SyncedChannelLinkMessagesCreateWithoutChannelLinksInput, Prisma.SyncedChannelLinkMessagesUncheckedCreateWithoutChannelLinksInput> | Prisma.SyncedChannelLinkMessagesCreateWithoutChannelLinksInput[] | Prisma.SyncedChannelLinkMessagesUncheckedCreateWithoutChannelLinksInput[]
  connectOrCreate?: Prisma.SyncedChannelLinkMessagesCreateOrConnectWithoutChannelLinksInput | Prisma.SyncedChannelLinkMessagesCreateOrConnectWithoutChannelLinksInput[]
  upsert?: Prisma.SyncedChannelLinkMessagesUpsertWithWhereUniqueWithoutChannelLinksInput | Prisma.SyncedChannelLinkMessagesUpsertWithWhereUniqueWithoutChannelLinksInput[]
  createMany?: Prisma.SyncedChannelLinkMessagesCreateManyChannelLinksInputEnvelope
  set?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput | Prisma.SyncedChannelLinkMessagesWhereUniqueInput[]
  disconnect?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput | Prisma.SyncedChannelLinkMessagesWhereUniqueInput[]
  delete?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput | Prisma.SyncedChannelLinkMessagesWhereUniqueInput[]
  connect?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput | Prisma.SyncedChannelLinkMessagesWhereUniqueInput[]
  update?: Prisma.SyncedChannelLinkMessagesUpdateWithWhereUniqueWithoutChannelLinksInput | Prisma.SyncedChannelLinkMessagesUpdateWithWhereUniqueWithoutChannelLinksInput[]
  updateMany?: Prisma.SyncedChannelLinkMessagesUpdateManyWithWhereWithoutChannelLinksInput | Prisma.SyncedChannelLinkMessagesUpdateManyWithWhereWithoutChannelLinksInput[]
  deleteMany?: Prisma.SyncedChannelLinkMessagesScalarWhereInput | Prisma.SyncedChannelLinkMessagesScalarWhereInput[]
}

export type SyncedChannelLinkMessagesCreateWithoutChannelLinksInput = {
  GuildId: string
  UserMessageId: string
  WebhookMessageId: string
  WebhookUrl: string
  ChannelId: string
}

export type SyncedChannelLinkMessagesUncheckedCreateWithoutChannelLinksInput = {
  Id?: number
  GuildId: string
  UserMessageId: string
  WebhookMessageId: string
  WebhookUrl: string
  ChannelId: string
}

export type SyncedChannelLinkMessagesCreateOrConnectWithoutChannelLinksInput = {
  where: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
  create: Prisma.XOR<Prisma.SyncedChannelLinkMessagesCreateWithoutChannelLinksInput, Prisma.SyncedChannelLinkMessagesUncheckedCreateWithoutChannelLinksInput>
}

export type SyncedChannelLinkMessagesCreateManyChannelLinksInputEnvelope = {
  data: Prisma.SyncedChannelLinkMessagesCreateManyChannelLinksInput | Prisma.SyncedChannelLinkMessagesCreateManyChannelLinksInput[]
  skipDuplicates?: boolean
}

export type SyncedChannelLinkMessagesUpsertWithWhereUniqueWithoutChannelLinksInput = {
  where: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
  update: Prisma.XOR<Prisma.SyncedChannelLinkMessagesUpdateWithoutChannelLinksInput, Prisma.SyncedChannelLinkMessagesUncheckedUpdateWithoutChannelLinksInput>
  create: Prisma.XOR<Prisma.SyncedChannelLinkMessagesCreateWithoutChannelLinksInput, Prisma.SyncedChannelLinkMessagesUncheckedCreateWithoutChannelLinksInput>
}

export type SyncedChannelLinkMessagesUpdateWithWhereUniqueWithoutChannelLinksInput = {
  where: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
  data: Prisma.XOR<Prisma.SyncedChannelLinkMessagesUpdateWithoutChannelLinksInput, Prisma.SyncedChannelLinkMessagesUncheckedUpdateWithoutChannelLinksInput>
}

export type SyncedChannelLinkMessagesUpdateManyWithWhereWithoutChannelLinksInput = {
  where: Prisma.SyncedChannelLinkMessagesScalarWhereInput
  data: Prisma.XOR<Prisma.SyncedChannelLinkMessagesUpdateManyMutationInput, Prisma.SyncedChannelLinkMessagesUncheckedUpdateManyWithoutChannelLinksInput>
}

export type SyncedChannelLinkMessagesScalarWhereInput = {
  AND?: Prisma.SyncedChannelLinkMessagesScalarWhereInput | Prisma.SyncedChannelLinkMessagesScalarWhereInput[]
  OR?: Prisma.SyncedChannelLinkMessagesScalarWhereInput[]
  NOT?: Prisma.SyncedChannelLinkMessagesScalarWhereInput | Prisma.SyncedChannelLinkMessagesScalarWhereInput[]
  Id?: Prisma.IntFilter<"SyncedChannelLinkMessages"> | number
  GuildId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  UserMessageId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  WebhookMessageId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  WebhookUrl?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  ChannelId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
  ChannelLinkId?: Prisma.StringFilter<"SyncedChannelLinkMessages"> | string
}

export type SyncedChannelLinkMessagesCreateManyChannelLinksInput = {
  Id?: number
  GuildId: string
  UserMessageId: string
  WebhookMessageId: string
  WebhookUrl: string
  ChannelId: string
}

export type SyncedChannelLinkMessagesUpdateWithoutChannelLinksInput = {
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  UserMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookUrl?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SyncedChannelLinkMessagesUncheckedUpdateWithoutChannelLinksInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  UserMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookUrl?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SyncedChannelLinkMessagesUncheckedUpdateManyWithoutChannelLinksInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  UserMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookMessageId?: Prisma.StringFieldUpdateOperationsInput | string
  WebhookUrl?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type SyncedChannelLinkMessagesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  GuildId?: boolean
  UserMessageId?: boolean
  WebhookMessageId?: boolean
  WebhookUrl?: boolean
  ChannelId?: boolean
  ChannelLinkId?: boolean
  ChannelLinks?: boolean | Prisma.GuildChannelLinksDefaultArgs<ExtArgs>
}, ExtArgs["result"]["syncedChannelLinkMessages"]>

export type SyncedChannelLinkMessagesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  GuildId?: boolean
  UserMessageId?: boolean
  WebhookMessageId?: boolean
  WebhookUrl?: boolean
  ChannelId?: boolean
  ChannelLinkId?: boolean
  ChannelLinks?: boolean | Prisma.GuildChannelLinksDefaultArgs<ExtArgs>
}, ExtArgs["result"]["syncedChannelLinkMessages"]>

export type SyncedChannelLinkMessagesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  GuildId?: boolean
  UserMessageId?: boolean
  WebhookMessageId?: boolean
  WebhookUrl?: boolean
  ChannelId?: boolean
  ChannelLinkId?: boolean
  ChannelLinks?: boolean | Prisma.GuildChannelLinksDefaultArgs<ExtArgs>
}, ExtArgs["result"]["syncedChannelLinkMessages"]>

export type SyncedChannelLinkMessagesSelectScalar = {
  Id?: boolean
  GuildId?: boolean
  UserMessageId?: boolean
  WebhookMessageId?: boolean
  WebhookUrl?: boolean
  ChannelId?: boolean
  ChannelLinkId?: boolean
}

export type SyncedChannelLinkMessagesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Id" | "GuildId" | "UserMessageId" | "WebhookMessageId" | "WebhookUrl" | "ChannelId" | "ChannelLinkId", ExtArgs["result"]["syncedChannelLinkMessages"]>
export type SyncedChannelLinkMessagesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ChannelLinks?: boolean | Prisma.GuildChannelLinksDefaultArgs<ExtArgs>
}
export type SyncedChannelLinkMessagesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ChannelLinks?: boolean | Prisma.GuildChannelLinksDefaultArgs<ExtArgs>
}
export type SyncedChannelLinkMessagesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ChannelLinks?: boolean | Prisma.GuildChannelLinksDefaultArgs<ExtArgs>
}

export type $SyncedChannelLinkMessagesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SyncedChannelLinkMessages"
  objects: {
    ChannelLinks: Prisma.$GuildChannelLinksPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Id: number
    GuildId: string
    UserMessageId: string
    WebhookMessageId: string
    WebhookUrl: string
    ChannelId: string
    ChannelLinkId: string
  }, ExtArgs["result"]["syncedChannelLinkMessages"]>
  composites: {}
}

export type SyncedChannelLinkMessagesGetPayload<S extends boolean | null | undefined | SyncedChannelLinkMessagesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload, S>

export type SyncedChannelLinkMessagesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SyncedChannelLinkMessagesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SyncedChannelLinkMessagesCountAggregateInputType | true
  }

export interface SyncedChannelLinkMessagesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SyncedChannelLinkMessages'], meta: { name: 'SyncedChannelLinkMessages' } }
  /**
   * Find zero or one SyncedChannelLinkMessages that matches the filter.
   * @param {SyncedChannelLinkMessagesFindUniqueArgs} args - Arguments to find a SyncedChannelLinkMessages
   * @example
   * // Get one SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SyncedChannelLinkMessagesFindUniqueArgs>(args: Prisma.SelectSubset<T, SyncedChannelLinkMessagesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SyncedChannelLinkMessagesClient<runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SyncedChannelLinkMessages that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SyncedChannelLinkMessagesFindUniqueOrThrowArgs} args - Arguments to find a SyncedChannelLinkMessages
   * @example
   * // Get one SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SyncedChannelLinkMessagesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SyncedChannelLinkMessagesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SyncedChannelLinkMessagesClient<runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SyncedChannelLinkMessages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncedChannelLinkMessagesFindFirstArgs} args - Arguments to find a SyncedChannelLinkMessages
   * @example
   * // Get one SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SyncedChannelLinkMessagesFindFirstArgs>(args?: Prisma.SelectSubset<T, SyncedChannelLinkMessagesFindFirstArgs<ExtArgs>>): Prisma.Prisma__SyncedChannelLinkMessagesClient<runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SyncedChannelLinkMessages that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncedChannelLinkMessagesFindFirstOrThrowArgs} args - Arguments to find a SyncedChannelLinkMessages
   * @example
   * // Get one SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SyncedChannelLinkMessagesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SyncedChannelLinkMessagesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SyncedChannelLinkMessagesClient<runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SyncedChannelLinkMessages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncedChannelLinkMessagesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.findMany()
   * 
   * // Get first 10 SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.findMany({ take: 10 })
   * 
   * // Only select the `Id`
   * const syncedChannelLinkMessagesWithIdOnly = await prisma.syncedChannelLinkMessages.findMany({ select: { Id: true } })
   * 
   */
  findMany<T extends SyncedChannelLinkMessagesFindManyArgs>(args?: Prisma.SelectSubset<T, SyncedChannelLinkMessagesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SyncedChannelLinkMessages.
   * @param {SyncedChannelLinkMessagesCreateArgs} args - Arguments to create a SyncedChannelLinkMessages.
   * @example
   * // Create one SyncedChannelLinkMessages
   * const SyncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.create({
   *   data: {
   *     // ... data to create a SyncedChannelLinkMessages
   *   }
   * })
   * 
   */
  create<T extends SyncedChannelLinkMessagesCreateArgs>(args: Prisma.SelectSubset<T, SyncedChannelLinkMessagesCreateArgs<ExtArgs>>): Prisma.Prisma__SyncedChannelLinkMessagesClient<runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SyncedChannelLinkMessages.
   * @param {SyncedChannelLinkMessagesCreateManyArgs} args - Arguments to create many SyncedChannelLinkMessages.
   * @example
   * // Create many SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SyncedChannelLinkMessagesCreateManyArgs>(args?: Prisma.SelectSubset<T, SyncedChannelLinkMessagesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SyncedChannelLinkMessages and returns the data saved in the database.
   * @param {SyncedChannelLinkMessagesCreateManyAndReturnArgs} args - Arguments to create many SyncedChannelLinkMessages.
   * @example
   * // Create many SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SyncedChannelLinkMessages and only return the `Id`
   * const syncedChannelLinkMessagesWithIdOnly = await prisma.syncedChannelLinkMessages.createManyAndReturn({
   *   select: { Id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SyncedChannelLinkMessagesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SyncedChannelLinkMessagesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SyncedChannelLinkMessages.
   * @param {SyncedChannelLinkMessagesDeleteArgs} args - Arguments to delete one SyncedChannelLinkMessages.
   * @example
   * // Delete one SyncedChannelLinkMessages
   * const SyncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.delete({
   *   where: {
   *     // ... filter to delete one SyncedChannelLinkMessages
   *   }
   * })
   * 
   */
  delete<T extends SyncedChannelLinkMessagesDeleteArgs>(args: Prisma.SelectSubset<T, SyncedChannelLinkMessagesDeleteArgs<ExtArgs>>): Prisma.Prisma__SyncedChannelLinkMessagesClient<runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SyncedChannelLinkMessages.
   * @param {SyncedChannelLinkMessagesUpdateArgs} args - Arguments to update one SyncedChannelLinkMessages.
   * @example
   * // Update one SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SyncedChannelLinkMessagesUpdateArgs>(args: Prisma.SelectSubset<T, SyncedChannelLinkMessagesUpdateArgs<ExtArgs>>): Prisma.Prisma__SyncedChannelLinkMessagesClient<runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SyncedChannelLinkMessages.
   * @param {SyncedChannelLinkMessagesDeleteManyArgs} args - Arguments to filter SyncedChannelLinkMessages to delete.
   * @example
   * // Delete a few SyncedChannelLinkMessages
   * const { count } = await prisma.syncedChannelLinkMessages.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SyncedChannelLinkMessagesDeleteManyArgs>(args?: Prisma.SelectSubset<T, SyncedChannelLinkMessagesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SyncedChannelLinkMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncedChannelLinkMessagesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SyncedChannelLinkMessagesUpdateManyArgs>(args: Prisma.SelectSubset<T, SyncedChannelLinkMessagesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SyncedChannelLinkMessages and returns the data updated in the database.
   * @param {SyncedChannelLinkMessagesUpdateManyAndReturnArgs} args - Arguments to update many SyncedChannelLinkMessages.
   * @example
   * // Update many SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SyncedChannelLinkMessages and only return the `Id`
   * const syncedChannelLinkMessagesWithIdOnly = await prisma.syncedChannelLinkMessages.updateManyAndReturn({
   *   select: { Id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SyncedChannelLinkMessagesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SyncedChannelLinkMessagesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SyncedChannelLinkMessages.
   * @param {SyncedChannelLinkMessagesUpsertArgs} args - Arguments to update or create a SyncedChannelLinkMessages.
   * @example
   * // Update or create a SyncedChannelLinkMessages
   * const syncedChannelLinkMessages = await prisma.syncedChannelLinkMessages.upsert({
   *   create: {
   *     // ... data to create a SyncedChannelLinkMessages
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SyncedChannelLinkMessages we want to update
   *   }
   * })
   */
  upsert<T extends SyncedChannelLinkMessagesUpsertArgs>(args: Prisma.SelectSubset<T, SyncedChannelLinkMessagesUpsertArgs<ExtArgs>>): Prisma.Prisma__SyncedChannelLinkMessagesClient<runtime.Types.Result.GetResult<Prisma.$SyncedChannelLinkMessagesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SyncedChannelLinkMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncedChannelLinkMessagesCountArgs} args - Arguments to filter SyncedChannelLinkMessages to count.
   * @example
   * // Count the number of SyncedChannelLinkMessages
   * const count = await prisma.syncedChannelLinkMessages.count({
   *   where: {
   *     // ... the filter for the SyncedChannelLinkMessages we want to count
   *   }
   * })
  **/
  count<T extends SyncedChannelLinkMessagesCountArgs>(
    args?: Prisma.Subset<T, SyncedChannelLinkMessagesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SyncedChannelLinkMessagesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SyncedChannelLinkMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncedChannelLinkMessagesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SyncedChannelLinkMessagesAggregateArgs>(args: Prisma.Subset<T, SyncedChannelLinkMessagesAggregateArgs>): Prisma.PrismaPromise<GetSyncedChannelLinkMessagesAggregateType<T>>

  /**
   * Group by SyncedChannelLinkMessages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncedChannelLinkMessagesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SyncedChannelLinkMessagesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SyncedChannelLinkMessagesGroupByArgs['orderBy'] }
      : { orderBy?: SyncedChannelLinkMessagesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SyncedChannelLinkMessagesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSyncedChannelLinkMessagesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SyncedChannelLinkMessages model
 */
readonly fields: SyncedChannelLinkMessagesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SyncedChannelLinkMessages.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SyncedChannelLinkMessagesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ChannelLinks<T extends Prisma.GuildChannelLinksDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuildChannelLinksDefaultArgs<ExtArgs>>): Prisma.Prisma__GuildChannelLinksClient<runtime.Types.Result.GetResult<Prisma.$GuildChannelLinksPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SyncedChannelLinkMessages model
 */
export interface SyncedChannelLinkMessagesFieldRefs {
  readonly Id: Prisma.FieldRef<"SyncedChannelLinkMessages", 'Int'>
  readonly GuildId: Prisma.FieldRef<"SyncedChannelLinkMessages", 'String'>
  readonly UserMessageId: Prisma.FieldRef<"SyncedChannelLinkMessages", 'String'>
  readonly WebhookMessageId: Prisma.FieldRef<"SyncedChannelLinkMessages", 'String'>
  readonly WebhookUrl: Prisma.FieldRef<"SyncedChannelLinkMessages", 'String'>
  readonly ChannelId: Prisma.FieldRef<"SyncedChannelLinkMessages", 'String'>
  readonly ChannelLinkId: Prisma.FieldRef<"SyncedChannelLinkMessages", 'String'>
}
    

// Custom InputTypes
/**
 * SyncedChannelLinkMessages findUnique
 */
export type SyncedChannelLinkMessagesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesInclude<ExtArgs> | null
  /**
   * Filter, which SyncedChannelLinkMessages to fetch.
   */
  where: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
}

/**
 * SyncedChannelLinkMessages findUniqueOrThrow
 */
export type SyncedChannelLinkMessagesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesInclude<ExtArgs> | null
  /**
   * Filter, which SyncedChannelLinkMessages to fetch.
   */
  where: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
}

/**
 * SyncedChannelLinkMessages findFirst
 */
export type SyncedChannelLinkMessagesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesInclude<ExtArgs> | null
  /**
   * Filter, which SyncedChannelLinkMessages to fetch.
   */
  where?: Prisma.SyncedChannelLinkMessagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncedChannelLinkMessages to fetch.
   */
  orderBy?: Prisma.SyncedChannelLinkMessagesOrderByWithRelationInput | Prisma.SyncedChannelLinkMessagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SyncedChannelLinkMessages.
   */
  cursor?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncedChannelLinkMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncedChannelLinkMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SyncedChannelLinkMessages.
   */
  distinct?: Prisma.SyncedChannelLinkMessagesScalarFieldEnum | Prisma.SyncedChannelLinkMessagesScalarFieldEnum[]
}

/**
 * SyncedChannelLinkMessages findFirstOrThrow
 */
export type SyncedChannelLinkMessagesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesInclude<ExtArgs> | null
  /**
   * Filter, which SyncedChannelLinkMessages to fetch.
   */
  where?: Prisma.SyncedChannelLinkMessagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncedChannelLinkMessages to fetch.
   */
  orderBy?: Prisma.SyncedChannelLinkMessagesOrderByWithRelationInput | Prisma.SyncedChannelLinkMessagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SyncedChannelLinkMessages.
   */
  cursor?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncedChannelLinkMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncedChannelLinkMessages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SyncedChannelLinkMessages.
   */
  distinct?: Prisma.SyncedChannelLinkMessagesScalarFieldEnum | Prisma.SyncedChannelLinkMessagesScalarFieldEnum[]
}

/**
 * SyncedChannelLinkMessages findMany
 */
export type SyncedChannelLinkMessagesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesInclude<ExtArgs> | null
  /**
   * Filter, which SyncedChannelLinkMessages to fetch.
   */
  where?: Prisma.SyncedChannelLinkMessagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncedChannelLinkMessages to fetch.
   */
  orderBy?: Prisma.SyncedChannelLinkMessagesOrderByWithRelationInput | Prisma.SyncedChannelLinkMessagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SyncedChannelLinkMessages.
   */
  cursor?: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncedChannelLinkMessages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncedChannelLinkMessages.
   */
  skip?: number
  distinct?: Prisma.SyncedChannelLinkMessagesScalarFieldEnum | Prisma.SyncedChannelLinkMessagesScalarFieldEnum[]
}

/**
 * SyncedChannelLinkMessages create
 */
export type SyncedChannelLinkMessagesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesInclude<ExtArgs> | null
  /**
   * The data needed to create a SyncedChannelLinkMessages.
   */
  data: Prisma.XOR<Prisma.SyncedChannelLinkMessagesCreateInput, Prisma.SyncedChannelLinkMessagesUncheckedCreateInput>
}

/**
 * SyncedChannelLinkMessages createMany
 */
export type SyncedChannelLinkMessagesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SyncedChannelLinkMessages.
   */
  data: Prisma.SyncedChannelLinkMessagesCreateManyInput | Prisma.SyncedChannelLinkMessagesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SyncedChannelLinkMessages createManyAndReturn
 */
export type SyncedChannelLinkMessagesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * The data used to create many SyncedChannelLinkMessages.
   */
  data: Prisma.SyncedChannelLinkMessagesCreateManyInput | Prisma.SyncedChannelLinkMessagesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SyncedChannelLinkMessages update
 */
export type SyncedChannelLinkMessagesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesInclude<ExtArgs> | null
  /**
   * The data needed to update a SyncedChannelLinkMessages.
   */
  data: Prisma.XOR<Prisma.SyncedChannelLinkMessagesUpdateInput, Prisma.SyncedChannelLinkMessagesUncheckedUpdateInput>
  /**
   * Choose, which SyncedChannelLinkMessages to update.
   */
  where: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
}

/**
 * SyncedChannelLinkMessages updateMany
 */
export type SyncedChannelLinkMessagesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SyncedChannelLinkMessages.
   */
  data: Prisma.XOR<Prisma.SyncedChannelLinkMessagesUpdateManyMutationInput, Prisma.SyncedChannelLinkMessagesUncheckedUpdateManyInput>
  /**
   * Filter which SyncedChannelLinkMessages to update
   */
  where?: Prisma.SyncedChannelLinkMessagesWhereInput
  /**
   * Limit how many SyncedChannelLinkMessages to update.
   */
  limit?: number
}

/**
 * SyncedChannelLinkMessages updateManyAndReturn
 */
export type SyncedChannelLinkMessagesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * The data used to update SyncedChannelLinkMessages.
   */
  data: Prisma.XOR<Prisma.SyncedChannelLinkMessagesUpdateManyMutationInput, Prisma.SyncedChannelLinkMessagesUncheckedUpdateManyInput>
  /**
   * Filter which SyncedChannelLinkMessages to update
   */
  where?: Prisma.SyncedChannelLinkMessagesWhereInput
  /**
   * Limit how many SyncedChannelLinkMessages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SyncedChannelLinkMessages upsert
 */
export type SyncedChannelLinkMessagesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesInclude<ExtArgs> | null
  /**
   * The filter to search for the SyncedChannelLinkMessages to update in case it exists.
   */
  where: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
  /**
   * In case the SyncedChannelLinkMessages found by the `where` argument doesn't exist, create a new SyncedChannelLinkMessages with this data.
   */
  create: Prisma.XOR<Prisma.SyncedChannelLinkMessagesCreateInput, Prisma.SyncedChannelLinkMessagesUncheckedCreateInput>
  /**
   * In case the SyncedChannelLinkMessages was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SyncedChannelLinkMessagesUpdateInput, Prisma.SyncedChannelLinkMessagesUncheckedUpdateInput>
}

/**
 * SyncedChannelLinkMessages delete
 */
export type SyncedChannelLinkMessagesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesInclude<ExtArgs> | null
  /**
   * Filter which SyncedChannelLinkMessages to delete.
   */
  where: Prisma.SyncedChannelLinkMessagesWhereUniqueInput
}

/**
 * SyncedChannelLinkMessages deleteMany
 */
export type SyncedChannelLinkMessagesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SyncedChannelLinkMessages to delete
   */
  where?: Prisma.SyncedChannelLinkMessagesWhereInput
  /**
   * Limit how many SyncedChannelLinkMessages to delete.
   */
  limit?: number
}

/**
 * SyncedChannelLinkMessages without action
 */
export type SyncedChannelLinkMessagesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncedChannelLinkMessages
   */
  select?: Prisma.SyncedChannelLinkMessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncedChannelLinkMessages
   */
  omit?: Prisma.SyncedChannelLinkMessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncedChannelLinkMessagesInclude<ExtArgs> | null
}
