
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TempVoiceChannels` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TempVoiceChannels
 * 
 */
export type TempVoiceChannelsModel = runtime.Types.Result.DefaultSelection<Prisma.$TempVoiceChannelsPayload>

export type AggregateTempVoiceChannels = {
  _count: TempVoiceChannelsCountAggregateOutputType | null
  _avg: TempVoiceChannelsAvgAggregateOutputType | null
  _sum: TempVoiceChannelsSumAggregateOutputType | null
  _min: TempVoiceChannelsMinAggregateOutputType | null
  _max: TempVoiceChannelsMaxAggregateOutputType | null
}

export type TempVoiceChannelsAvgAggregateOutputType = {
  Id: number | null
}

export type TempVoiceChannelsSumAggregateOutputType = {
  Id: number | null
}

export type TempVoiceChannelsMinAggregateOutputType = {
  Id: number | null
  GuildId: string | null
  ChannelId: string | null
  OwnerId: string | null
  TempVoiceConfigId: string | null
}

export type TempVoiceChannelsMaxAggregateOutputType = {
  Id: number | null
  GuildId: string | null
  ChannelId: string | null
  OwnerId: string | null
  TempVoiceConfigId: string | null
}

export type TempVoiceChannelsCountAggregateOutputType = {
  Id: number
  GuildId: number
  ChannelId: number
  OwnerId: number
  TempVoiceConfigId: number
  _all: number
}


export type TempVoiceChannelsAvgAggregateInputType = {
  Id?: true
}

export type TempVoiceChannelsSumAggregateInputType = {
  Id?: true
}

export type TempVoiceChannelsMinAggregateInputType = {
  Id?: true
  GuildId?: true
  ChannelId?: true
  OwnerId?: true
  TempVoiceConfigId?: true
}

export type TempVoiceChannelsMaxAggregateInputType = {
  Id?: true
  GuildId?: true
  ChannelId?: true
  OwnerId?: true
  TempVoiceConfigId?: true
}

export type TempVoiceChannelsCountAggregateInputType = {
  Id?: true
  GuildId?: true
  ChannelId?: true
  OwnerId?: true
  TempVoiceConfigId?: true
  _all?: true
}

export type TempVoiceChannelsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoiceChannels to aggregate.
   */
  where?: Prisma.TempVoiceChannelsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceChannelsOrderByWithRelationInput | Prisma.TempVoiceChannelsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TempVoiceChannelsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TempVoiceChannels
  **/
  _count?: true | TempVoiceChannelsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TempVoiceChannelsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TempVoiceChannelsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TempVoiceChannelsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TempVoiceChannelsMaxAggregateInputType
}

export type GetTempVoiceChannelsAggregateType<T extends TempVoiceChannelsAggregateArgs> = {
      [P in keyof T & keyof AggregateTempVoiceChannels]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTempVoiceChannels[P]>
    : Prisma.GetScalarType<T[P], AggregateTempVoiceChannels[P]>
}




export type TempVoiceChannelsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempVoiceChannelsWhereInput
  orderBy?: Prisma.TempVoiceChannelsOrderByWithAggregationInput | Prisma.TempVoiceChannelsOrderByWithAggregationInput[]
  by: Prisma.TempVoiceChannelsScalarFieldEnum[] | Prisma.TempVoiceChannelsScalarFieldEnum
  having?: Prisma.TempVoiceChannelsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TempVoiceChannelsCountAggregateInputType | true
  _avg?: TempVoiceChannelsAvgAggregateInputType
  _sum?: TempVoiceChannelsSumAggregateInputType
  _min?: TempVoiceChannelsMinAggregateInputType
  _max?: TempVoiceChannelsMaxAggregateInputType
}

export type TempVoiceChannelsGroupByOutputType = {
  Id: number
  GuildId: string
  ChannelId: string
  OwnerId: string
  TempVoiceConfigId: string
  _count: TempVoiceChannelsCountAggregateOutputType | null
  _avg: TempVoiceChannelsAvgAggregateOutputType | null
  _sum: TempVoiceChannelsSumAggregateOutputType | null
  _min: TempVoiceChannelsMinAggregateOutputType | null
  _max: TempVoiceChannelsMaxAggregateOutputType | null
}

type GetTempVoiceChannelsGroupByPayload<T extends TempVoiceChannelsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TempVoiceChannelsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TempVoiceChannelsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TempVoiceChannelsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TempVoiceChannelsGroupByOutputType[P]>
      }
    >
  >



export type TempVoiceChannelsWhereInput = {
  AND?: Prisma.TempVoiceChannelsWhereInput | Prisma.TempVoiceChannelsWhereInput[]
  OR?: Prisma.TempVoiceChannelsWhereInput[]
  NOT?: Prisma.TempVoiceChannelsWhereInput | Prisma.TempVoiceChannelsWhereInput[]
  Id?: Prisma.IntFilter<"TempVoiceChannels"> | number
  GuildId?: Prisma.StringFilter<"TempVoiceChannels"> | string
  ChannelId?: Prisma.StringFilter<"TempVoiceChannels"> | string
  OwnerId?: Prisma.StringFilter<"TempVoiceChannels"> | string
  TempVoiceConfigId?: Prisma.StringFilter<"TempVoiceChannels"> | string
  TempVoiceChannelMembers?: Prisma.XOR<Prisma.TempVoiceChannelMemberNullableScalarRelationFilter, Prisma.TempVoiceChannelMemberWhereInput> | null
  TempVoiceConfig?: Prisma.XOR<Prisma.TempVoiceConfigScalarRelationFilter, Prisma.TempVoiceConfigWhereInput>
}

export type TempVoiceChannelsOrderByWithRelationInput = {
  Id?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  ChannelId?: Prisma.SortOrder
  OwnerId?: Prisma.SortOrder
  TempVoiceConfigId?: Prisma.SortOrder
  TempVoiceChannelMembers?: Prisma.TempVoiceChannelMemberOrderByWithRelationInput
  TempVoiceConfig?: Prisma.TempVoiceConfigOrderByWithRelationInput
}

export type TempVoiceChannelsWhereUniqueInput = Prisma.AtLeast<{
  Id?: number
  ChannelId?: string
  OwnerId?: string
  AND?: Prisma.TempVoiceChannelsWhereInput | Prisma.TempVoiceChannelsWhereInput[]
  OR?: Prisma.TempVoiceChannelsWhereInput[]
  NOT?: Prisma.TempVoiceChannelsWhereInput | Prisma.TempVoiceChannelsWhereInput[]
  GuildId?: Prisma.StringFilter<"TempVoiceChannels"> | string
  TempVoiceConfigId?: Prisma.StringFilter<"TempVoiceChannels"> | string
  TempVoiceChannelMembers?: Prisma.XOR<Prisma.TempVoiceChannelMemberNullableScalarRelationFilter, Prisma.TempVoiceChannelMemberWhereInput> | null
  TempVoiceConfig?: Prisma.XOR<Prisma.TempVoiceConfigScalarRelationFilter, Prisma.TempVoiceConfigWhereInput>
}, "Id" | "ChannelId" | "OwnerId">

export type TempVoiceChannelsOrderByWithAggregationInput = {
  Id?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  ChannelId?: Prisma.SortOrder
  OwnerId?: Prisma.SortOrder
  TempVoiceConfigId?: Prisma.SortOrder
  _count?: Prisma.TempVoiceChannelsCountOrderByAggregateInput
  _avg?: Prisma.TempVoiceChannelsAvgOrderByAggregateInput
  _max?: Prisma.TempVoiceChannelsMaxOrderByAggregateInput
  _min?: Prisma.TempVoiceChannelsMinOrderByAggregateInput
  _sum?: Prisma.TempVoiceChannelsSumOrderByAggregateInput
}

export type TempVoiceChannelsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TempVoiceChannelsScalarWhereWithAggregatesInput | Prisma.TempVoiceChannelsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TempVoiceChannelsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TempVoiceChannelsScalarWhereWithAggregatesInput | Prisma.TempVoiceChannelsScalarWhereWithAggregatesInput[]
  Id?: Prisma.IntWithAggregatesFilter<"TempVoiceChannels"> | number
  GuildId?: Prisma.StringWithAggregatesFilter<"TempVoiceChannels"> | string
  ChannelId?: Prisma.StringWithAggregatesFilter<"TempVoiceChannels"> | string
  OwnerId?: Prisma.StringWithAggregatesFilter<"TempVoiceChannels"> | string
  TempVoiceConfigId?: Prisma.StringWithAggregatesFilter<"TempVoiceChannels"> | string
}

export type TempVoiceChannelsCreateInput = {
  GuildId: string
  ChannelId: string
  OwnerId: string
  TempVoiceChannelMembers?: Prisma.TempVoiceChannelMemberCreateNestedOneWithoutTempVoiceChannelsInput
  TempVoiceConfig: Prisma.TempVoiceConfigCreateNestedOneWithoutTempVoiceChannelsInput
}

export type TempVoiceChannelsUncheckedCreateInput = {
  Id?: number
  GuildId: string
  ChannelId: string
  OwnerId: string
  TempVoiceConfigId: string
  TempVoiceChannelMembers?: Prisma.TempVoiceChannelMemberUncheckedCreateNestedOneWithoutTempVoiceChannelsInput
}

export type TempVoiceChannelsUpdateInput = {
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  OwnerId?: Prisma.StringFieldUpdateOperationsInput | string
  TempVoiceChannelMembers?: Prisma.TempVoiceChannelMemberUpdateOneWithoutTempVoiceChannelsNestedInput
  TempVoiceConfig?: Prisma.TempVoiceConfigUpdateOneRequiredWithoutTempVoiceChannelsNestedInput
}

export type TempVoiceChannelsUncheckedUpdateInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  OwnerId?: Prisma.StringFieldUpdateOperationsInput | string
  TempVoiceConfigId?: Prisma.StringFieldUpdateOperationsInput | string
  TempVoiceChannelMembers?: Prisma.TempVoiceChannelMemberUncheckedUpdateOneWithoutTempVoiceChannelsNestedInput
}

export type TempVoiceChannelsCreateManyInput = {
  Id?: number
  GuildId: string
  ChannelId: string
  OwnerId: string
  TempVoiceConfigId: string
}

export type TempVoiceChannelsUpdateManyMutationInput = {
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  OwnerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TempVoiceChannelsUncheckedUpdateManyInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  OwnerId?: Prisma.StringFieldUpdateOperationsInput | string
  TempVoiceConfigId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TempVoiceChannelsListRelationFilter = {
  every?: Prisma.TempVoiceChannelsWhereInput
  some?: Prisma.TempVoiceChannelsWhereInput
  none?: Prisma.TempVoiceChannelsWhereInput
}

export type TempVoiceChannelsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TempVoiceChannelsCountOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  ChannelId?: Prisma.SortOrder
  OwnerId?: Prisma.SortOrder
  TempVoiceConfigId?: Prisma.SortOrder
}

export type TempVoiceChannelsAvgOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type TempVoiceChannelsMaxOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  ChannelId?: Prisma.SortOrder
  OwnerId?: Prisma.SortOrder
  TempVoiceConfigId?: Prisma.SortOrder
}

export type TempVoiceChannelsMinOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  ChannelId?: Prisma.SortOrder
  OwnerId?: Prisma.SortOrder
  TempVoiceConfigId?: Prisma.SortOrder
}

export type TempVoiceChannelsSumOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type TempVoiceChannelsScalarRelationFilter = {
  is?: Prisma.TempVoiceChannelsWhereInput
  isNot?: Prisma.TempVoiceChannelsWhereInput
}

export type TempVoiceChannelsCreateNestedManyWithoutTempVoiceConfigInput = {
  create?: Prisma.XOR<Prisma.TempVoiceChannelsCreateWithoutTempVoiceConfigInput, Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceConfigInput> | Prisma.TempVoiceChannelsCreateWithoutTempVoiceConfigInput[] | Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceConfigInput[]
  connectOrCreate?: Prisma.TempVoiceChannelsCreateOrConnectWithoutTempVoiceConfigInput | Prisma.TempVoiceChannelsCreateOrConnectWithoutTempVoiceConfigInput[]
  createMany?: Prisma.TempVoiceChannelsCreateManyTempVoiceConfigInputEnvelope
  connect?: Prisma.TempVoiceChannelsWhereUniqueInput | Prisma.TempVoiceChannelsWhereUniqueInput[]
}

export type TempVoiceChannelsUncheckedCreateNestedManyWithoutTempVoiceConfigInput = {
  create?: Prisma.XOR<Prisma.TempVoiceChannelsCreateWithoutTempVoiceConfigInput, Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceConfigInput> | Prisma.TempVoiceChannelsCreateWithoutTempVoiceConfigInput[] | Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceConfigInput[]
  connectOrCreate?: Prisma.TempVoiceChannelsCreateOrConnectWithoutTempVoiceConfigInput | Prisma.TempVoiceChannelsCreateOrConnectWithoutTempVoiceConfigInput[]
  createMany?: Prisma.TempVoiceChannelsCreateManyTempVoiceConfigInputEnvelope
  connect?: Prisma.TempVoiceChannelsWhereUniqueInput | Prisma.TempVoiceChannelsWhereUniqueInput[]
}

export type TempVoiceChannelsUpdateManyWithoutTempVoiceConfigNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceChannelsCreateWithoutTempVoiceConfigInput, Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceConfigInput> | Prisma.TempVoiceChannelsCreateWithoutTempVoiceConfigInput[] | Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceConfigInput[]
  connectOrCreate?: Prisma.TempVoiceChannelsCreateOrConnectWithoutTempVoiceConfigInput | Prisma.TempVoiceChannelsCreateOrConnectWithoutTempVoiceConfigInput[]
  upsert?: Prisma.TempVoiceChannelsUpsertWithWhereUniqueWithoutTempVoiceConfigInput | Prisma.TempVoiceChannelsUpsertWithWhereUniqueWithoutTempVoiceConfigInput[]
  createMany?: Prisma.TempVoiceChannelsCreateManyTempVoiceConfigInputEnvelope
  set?: Prisma.TempVoiceChannelsWhereUniqueInput | Prisma.TempVoiceChannelsWhereUniqueInput[]
  disconnect?: Prisma.TempVoiceChannelsWhereUniqueInput | Prisma.TempVoiceChannelsWhereUniqueInput[]
  delete?: Prisma.TempVoiceChannelsWhereUniqueInput | Prisma.TempVoiceChannelsWhereUniqueInput[]
  connect?: Prisma.TempVoiceChannelsWhereUniqueInput | Prisma.TempVoiceChannelsWhereUniqueInput[]
  update?: Prisma.TempVoiceChannelsUpdateWithWhereUniqueWithoutTempVoiceConfigInput | Prisma.TempVoiceChannelsUpdateWithWhereUniqueWithoutTempVoiceConfigInput[]
  updateMany?: Prisma.TempVoiceChannelsUpdateManyWithWhereWithoutTempVoiceConfigInput | Prisma.TempVoiceChannelsUpdateManyWithWhereWithoutTempVoiceConfigInput[]
  deleteMany?: Prisma.TempVoiceChannelsScalarWhereInput | Prisma.TempVoiceChannelsScalarWhereInput[]
}

export type TempVoiceChannelsUncheckedUpdateManyWithoutTempVoiceConfigNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceChannelsCreateWithoutTempVoiceConfigInput, Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceConfigInput> | Prisma.TempVoiceChannelsCreateWithoutTempVoiceConfigInput[] | Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceConfigInput[]
  connectOrCreate?: Prisma.TempVoiceChannelsCreateOrConnectWithoutTempVoiceConfigInput | Prisma.TempVoiceChannelsCreateOrConnectWithoutTempVoiceConfigInput[]
  upsert?: Prisma.TempVoiceChannelsUpsertWithWhereUniqueWithoutTempVoiceConfigInput | Prisma.TempVoiceChannelsUpsertWithWhereUniqueWithoutTempVoiceConfigInput[]
  createMany?: Prisma.TempVoiceChannelsCreateManyTempVoiceConfigInputEnvelope
  set?: Prisma.TempVoiceChannelsWhereUniqueInput | Prisma.TempVoiceChannelsWhereUniqueInput[]
  disconnect?: Prisma.TempVoiceChannelsWhereUniqueInput | Prisma.TempVoiceChannelsWhereUniqueInput[]
  delete?: Prisma.TempVoiceChannelsWhereUniqueInput | Prisma.TempVoiceChannelsWhereUniqueInput[]
  connect?: Prisma.TempVoiceChannelsWhereUniqueInput | Prisma.TempVoiceChannelsWhereUniqueInput[]
  update?: Prisma.TempVoiceChannelsUpdateWithWhereUniqueWithoutTempVoiceConfigInput | Prisma.TempVoiceChannelsUpdateWithWhereUniqueWithoutTempVoiceConfigInput[]
  updateMany?: Prisma.TempVoiceChannelsUpdateManyWithWhereWithoutTempVoiceConfigInput | Prisma.TempVoiceChannelsUpdateManyWithWhereWithoutTempVoiceConfigInput[]
  deleteMany?: Prisma.TempVoiceChannelsScalarWhereInput | Prisma.TempVoiceChannelsScalarWhereInput[]
}

export type TempVoiceChannelsCreateNestedOneWithoutTempVoiceChannelMembersInput = {
  create?: Prisma.XOR<Prisma.TempVoiceChannelsCreateWithoutTempVoiceChannelMembersInput, Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceChannelMembersInput>
  connectOrCreate?: Prisma.TempVoiceChannelsCreateOrConnectWithoutTempVoiceChannelMembersInput
  connect?: Prisma.TempVoiceChannelsWhereUniqueInput
}

export type TempVoiceChannelsUpdateOneRequiredWithoutTempVoiceChannelMembersNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceChannelsCreateWithoutTempVoiceChannelMembersInput, Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceChannelMembersInput>
  connectOrCreate?: Prisma.TempVoiceChannelsCreateOrConnectWithoutTempVoiceChannelMembersInput
  upsert?: Prisma.TempVoiceChannelsUpsertWithoutTempVoiceChannelMembersInput
  connect?: Prisma.TempVoiceChannelsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TempVoiceChannelsUpdateToOneWithWhereWithoutTempVoiceChannelMembersInput, Prisma.TempVoiceChannelsUpdateWithoutTempVoiceChannelMembersInput>, Prisma.TempVoiceChannelsUncheckedUpdateWithoutTempVoiceChannelMembersInput>
}

export type TempVoiceChannelsCreateWithoutTempVoiceConfigInput = {
  GuildId: string
  ChannelId: string
  OwnerId: string
  TempVoiceChannelMembers?: Prisma.TempVoiceChannelMemberCreateNestedOneWithoutTempVoiceChannelsInput
}

export type TempVoiceChannelsUncheckedCreateWithoutTempVoiceConfigInput = {
  Id?: number
  GuildId: string
  ChannelId: string
  OwnerId: string
  TempVoiceChannelMembers?: Prisma.TempVoiceChannelMemberUncheckedCreateNestedOneWithoutTempVoiceChannelsInput
}

export type TempVoiceChannelsCreateOrConnectWithoutTempVoiceConfigInput = {
  where: Prisma.TempVoiceChannelsWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceChannelsCreateWithoutTempVoiceConfigInput, Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceConfigInput>
}

export type TempVoiceChannelsCreateManyTempVoiceConfigInputEnvelope = {
  data: Prisma.TempVoiceChannelsCreateManyTempVoiceConfigInput | Prisma.TempVoiceChannelsCreateManyTempVoiceConfigInput[]
  skipDuplicates?: boolean
}

export type TempVoiceChannelsUpsertWithWhereUniqueWithoutTempVoiceConfigInput = {
  where: Prisma.TempVoiceChannelsWhereUniqueInput
  update: Prisma.XOR<Prisma.TempVoiceChannelsUpdateWithoutTempVoiceConfigInput, Prisma.TempVoiceChannelsUncheckedUpdateWithoutTempVoiceConfigInput>
  create: Prisma.XOR<Prisma.TempVoiceChannelsCreateWithoutTempVoiceConfigInput, Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceConfigInput>
}

export type TempVoiceChannelsUpdateWithWhereUniqueWithoutTempVoiceConfigInput = {
  where: Prisma.TempVoiceChannelsWhereUniqueInput
  data: Prisma.XOR<Prisma.TempVoiceChannelsUpdateWithoutTempVoiceConfigInput, Prisma.TempVoiceChannelsUncheckedUpdateWithoutTempVoiceConfigInput>
}

export type TempVoiceChannelsUpdateManyWithWhereWithoutTempVoiceConfigInput = {
  where: Prisma.TempVoiceChannelsScalarWhereInput
  data: Prisma.XOR<Prisma.TempVoiceChannelsUpdateManyMutationInput, Prisma.TempVoiceChannelsUncheckedUpdateManyWithoutTempVoiceConfigInput>
}

export type TempVoiceChannelsScalarWhereInput = {
  AND?: Prisma.TempVoiceChannelsScalarWhereInput | Prisma.TempVoiceChannelsScalarWhereInput[]
  OR?: Prisma.TempVoiceChannelsScalarWhereInput[]
  NOT?: Prisma.TempVoiceChannelsScalarWhereInput | Prisma.TempVoiceChannelsScalarWhereInput[]
  Id?: Prisma.IntFilter<"TempVoiceChannels"> | number
  GuildId?: Prisma.StringFilter<"TempVoiceChannels"> | string
  ChannelId?: Prisma.StringFilter<"TempVoiceChannels"> | string
  OwnerId?: Prisma.StringFilter<"TempVoiceChannels"> | string
  TempVoiceConfigId?: Prisma.StringFilter<"TempVoiceChannels"> | string
}

export type TempVoiceChannelsCreateWithoutTempVoiceChannelMembersInput = {
  GuildId: string
  ChannelId: string
  OwnerId: string
  TempVoiceConfig: Prisma.TempVoiceConfigCreateNestedOneWithoutTempVoiceChannelsInput
}

export type TempVoiceChannelsUncheckedCreateWithoutTempVoiceChannelMembersInput = {
  Id?: number
  GuildId: string
  ChannelId: string
  OwnerId: string
  TempVoiceConfigId: string
}

export type TempVoiceChannelsCreateOrConnectWithoutTempVoiceChannelMembersInput = {
  where: Prisma.TempVoiceChannelsWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceChannelsCreateWithoutTempVoiceChannelMembersInput, Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceChannelMembersInput>
}

export type TempVoiceChannelsUpsertWithoutTempVoiceChannelMembersInput = {
  update: Prisma.XOR<Prisma.TempVoiceChannelsUpdateWithoutTempVoiceChannelMembersInput, Prisma.TempVoiceChannelsUncheckedUpdateWithoutTempVoiceChannelMembersInput>
  create: Prisma.XOR<Prisma.TempVoiceChannelsCreateWithoutTempVoiceChannelMembersInput, Prisma.TempVoiceChannelsUncheckedCreateWithoutTempVoiceChannelMembersInput>
  where?: Prisma.TempVoiceChannelsWhereInput
}

export type TempVoiceChannelsUpdateToOneWithWhereWithoutTempVoiceChannelMembersInput = {
  where?: Prisma.TempVoiceChannelsWhereInput
  data: Prisma.XOR<Prisma.TempVoiceChannelsUpdateWithoutTempVoiceChannelMembersInput, Prisma.TempVoiceChannelsUncheckedUpdateWithoutTempVoiceChannelMembersInput>
}

export type TempVoiceChannelsUpdateWithoutTempVoiceChannelMembersInput = {
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  OwnerId?: Prisma.StringFieldUpdateOperationsInput | string
  TempVoiceConfig?: Prisma.TempVoiceConfigUpdateOneRequiredWithoutTempVoiceChannelsNestedInput
}

export type TempVoiceChannelsUncheckedUpdateWithoutTempVoiceChannelMembersInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  OwnerId?: Prisma.StringFieldUpdateOperationsInput | string
  TempVoiceConfigId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TempVoiceChannelsCreateManyTempVoiceConfigInput = {
  Id?: number
  GuildId: string
  ChannelId: string
  OwnerId: string
}

export type TempVoiceChannelsUpdateWithoutTempVoiceConfigInput = {
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  OwnerId?: Prisma.StringFieldUpdateOperationsInput | string
  TempVoiceChannelMembers?: Prisma.TempVoiceChannelMemberUpdateOneWithoutTempVoiceChannelsNestedInput
}

export type TempVoiceChannelsUncheckedUpdateWithoutTempVoiceConfigInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  OwnerId?: Prisma.StringFieldUpdateOperationsInput | string
  TempVoiceChannelMembers?: Prisma.TempVoiceChannelMemberUncheckedUpdateOneWithoutTempVoiceChannelsNestedInput
}

export type TempVoiceChannelsUncheckedUpdateManyWithoutTempVoiceConfigInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  ChannelId?: Prisma.StringFieldUpdateOperationsInput | string
  OwnerId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type TempVoiceChannelsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  GuildId?: boolean
  ChannelId?: boolean
  OwnerId?: boolean
  TempVoiceConfigId?: boolean
  TempVoiceChannelMembers?: boolean | Prisma.TempVoiceChannels$TempVoiceChannelMembersArgs<ExtArgs>
  TempVoiceConfig?: boolean | Prisma.TempVoiceConfigDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceChannels"]>

export type TempVoiceChannelsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  GuildId?: boolean
  ChannelId?: boolean
  OwnerId?: boolean
  TempVoiceConfigId?: boolean
  TempVoiceConfig?: boolean | Prisma.TempVoiceConfigDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceChannels"]>

export type TempVoiceChannelsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  GuildId?: boolean
  ChannelId?: boolean
  OwnerId?: boolean
  TempVoiceConfigId?: boolean
  TempVoiceConfig?: boolean | Prisma.TempVoiceConfigDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoiceChannels"]>

export type TempVoiceChannelsSelectScalar = {
  Id?: boolean
  GuildId?: boolean
  ChannelId?: boolean
  OwnerId?: boolean
  TempVoiceConfigId?: boolean
}

export type TempVoiceChannelsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Id" | "GuildId" | "ChannelId" | "OwnerId" | "TempVoiceConfigId", ExtArgs["result"]["tempVoiceChannels"]>
export type TempVoiceChannelsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  TempVoiceChannelMembers?: boolean | Prisma.TempVoiceChannels$TempVoiceChannelMembersArgs<ExtArgs>
  TempVoiceConfig?: boolean | Prisma.TempVoiceConfigDefaultArgs<ExtArgs>
}
export type TempVoiceChannelsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  TempVoiceConfig?: boolean | Prisma.TempVoiceConfigDefaultArgs<ExtArgs>
}
export type TempVoiceChannelsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  TempVoiceConfig?: boolean | Prisma.TempVoiceConfigDefaultArgs<ExtArgs>
}

export type $TempVoiceChannelsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TempVoiceChannels"
  objects: {
    TempVoiceChannelMembers: Prisma.$TempVoiceChannelMemberPayload<ExtArgs> | null
    TempVoiceConfig: Prisma.$TempVoiceConfigPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Id: number
    GuildId: string
    ChannelId: string
    OwnerId: string
    TempVoiceConfigId: string
  }, ExtArgs["result"]["tempVoiceChannels"]>
  composites: {}
}

export type TempVoiceChannelsGetPayload<S extends boolean | null | undefined | TempVoiceChannelsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload, S>

export type TempVoiceChannelsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TempVoiceChannelsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TempVoiceChannelsCountAggregateInputType | true
  }

export interface TempVoiceChannelsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TempVoiceChannels'], meta: { name: 'TempVoiceChannels' } }
  /**
   * Find zero or one TempVoiceChannels that matches the filter.
   * @param {TempVoiceChannelsFindUniqueArgs} args - Arguments to find a TempVoiceChannels
   * @example
   * // Get one TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TempVoiceChannelsFindUniqueArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelsClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TempVoiceChannels that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TempVoiceChannelsFindUniqueOrThrowArgs} args - Arguments to find a TempVoiceChannels
   * @example
   * // Get one TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TempVoiceChannelsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelsClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoiceChannels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelsFindFirstArgs} args - Arguments to find a TempVoiceChannels
   * @example
   * // Get one TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TempVoiceChannelsFindFirstArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelsClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoiceChannels that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelsFindFirstOrThrowArgs} args - Arguments to find a TempVoiceChannels
   * @example
   * // Get one TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TempVoiceChannelsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelsClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TempVoiceChannels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.findMany()
   * 
   * // Get first 10 TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.findMany({ take: 10 })
   * 
   * // Only select the `Id`
   * const tempVoiceChannelsWithIdOnly = await prisma.tempVoiceChannels.findMany({ select: { Id: true } })
   * 
   */
  findMany<T extends TempVoiceChannelsFindManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TempVoiceChannels.
   * @param {TempVoiceChannelsCreateArgs} args - Arguments to create a TempVoiceChannels.
   * @example
   * // Create one TempVoiceChannels
   * const TempVoiceChannels = await prisma.tempVoiceChannels.create({
   *   data: {
   *     // ... data to create a TempVoiceChannels
   *   }
   * })
   * 
   */
  create<T extends TempVoiceChannelsCreateArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelsCreateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelsClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TempVoiceChannels.
   * @param {TempVoiceChannelsCreateManyArgs} args - Arguments to create many TempVoiceChannels.
   * @example
   * // Create many TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TempVoiceChannelsCreateManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TempVoiceChannels and returns the data saved in the database.
   * @param {TempVoiceChannelsCreateManyAndReturnArgs} args - Arguments to create many TempVoiceChannels.
   * @example
   * // Create many TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TempVoiceChannels and only return the `Id`
   * const tempVoiceChannelsWithIdOnly = await prisma.tempVoiceChannels.createManyAndReturn({
   *   select: { Id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TempVoiceChannelsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TempVoiceChannels.
   * @param {TempVoiceChannelsDeleteArgs} args - Arguments to delete one TempVoiceChannels.
   * @example
   * // Delete one TempVoiceChannels
   * const TempVoiceChannels = await prisma.tempVoiceChannels.delete({
   *   where: {
   *     // ... filter to delete one TempVoiceChannels
   *   }
   * })
   * 
   */
  delete<T extends TempVoiceChannelsDeleteArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelsDeleteArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelsClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TempVoiceChannels.
   * @param {TempVoiceChannelsUpdateArgs} args - Arguments to update one TempVoiceChannels.
   * @example
   * // Update one TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TempVoiceChannelsUpdateArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelsUpdateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelsClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TempVoiceChannels.
   * @param {TempVoiceChannelsDeleteManyArgs} args - Arguments to filter TempVoiceChannels to delete.
   * @example
   * // Delete a few TempVoiceChannels
   * const { count } = await prisma.tempVoiceChannels.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TempVoiceChannelsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceChannelsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoiceChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TempVoiceChannelsUpdateManyArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoiceChannels and returns the data updated in the database.
   * @param {TempVoiceChannelsUpdateManyAndReturnArgs} args - Arguments to update many TempVoiceChannels.
   * @example
   * // Update many TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TempVoiceChannels and only return the `Id`
   * const tempVoiceChannelsWithIdOnly = await prisma.tempVoiceChannels.updateManyAndReturn({
   *   select: { Id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TempVoiceChannelsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TempVoiceChannels.
   * @param {TempVoiceChannelsUpsertArgs} args - Arguments to update or create a TempVoiceChannels.
   * @example
   * // Update or create a TempVoiceChannels
   * const tempVoiceChannels = await prisma.tempVoiceChannels.upsert({
   *   create: {
   *     // ... data to create a TempVoiceChannels
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TempVoiceChannels we want to update
   *   }
   * })
   */
  upsert<T extends TempVoiceChannelsUpsertArgs>(args: Prisma.SelectSubset<T, TempVoiceChannelsUpsertArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelsClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TempVoiceChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelsCountArgs} args - Arguments to filter TempVoiceChannels to count.
   * @example
   * // Count the number of TempVoiceChannels
   * const count = await prisma.tempVoiceChannels.count({
   *   where: {
   *     // ... the filter for the TempVoiceChannels we want to count
   *   }
   * })
  **/
  count<T extends TempVoiceChannelsCountArgs>(
    args?: Prisma.Subset<T, TempVoiceChannelsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TempVoiceChannelsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TempVoiceChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TempVoiceChannelsAggregateArgs>(args: Prisma.Subset<T, TempVoiceChannelsAggregateArgs>): Prisma.PrismaPromise<GetTempVoiceChannelsAggregateType<T>>

  /**
   * Group by TempVoiceChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceChannelsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TempVoiceChannelsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TempVoiceChannelsGroupByArgs['orderBy'] }
      : { orderBy?: TempVoiceChannelsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TempVoiceChannelsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTempVoiceChannelsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TempVoiceChannels model
 */
readonly fields: TempVoiceChannelsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TempVoiceChannels.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TempVoiceChannelsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  TempVoiceChannelMembers<T extends Prisma.TempVoiceChannels$TempVoiceChannelMembersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempVoiceChannels$TempVoiceChannelMembersArgs<ExtArgs>>): Prisma.Prisma__TempVoiceChannelMemberClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceChannelMemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  TempVoiceConfig<T extends Prisma.TempVoiceConfigDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempVoiceConfigDefaultArgs<ExtArgs>>): Prisma.Prisma__TempVoiceConfigClient<runtime.Types.Result.GetResult<Prisma.$TempVoiceConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TempVoiceChannels model
 */
export interface TempVoiceChannelsFieldRefs {
  readonly Id: Prisma.FieldRef<"TempVoiceChannels", 'Int'>
  readonly GuildId: Prisma.FieldRef<"TempVoiceChannels", 'String'>
  readonly ChannelId: Prisma.FieldRef<"TempVoiceChannels", 'String'>
  readonly OwnerId: Prisma.FieldRef<"TempVoiceChannels", 'String'>
  readonly TempVoiceConfigId: Prisma.FieldRef<"TempVoiceChannels", 'String'>
}
    

// Custom InputTypes
/**
 * TempVoiceChannels findUnique
 */
export type TempVoiceChannelsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceChannels to fetch.
   */
  where: Prisma.TempVoiceChannelsWhereUniqueInput
}

/**
 * TempVoiceChannels findUniqueOrThrow
 */
export type TempVoiceChannelsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceChannels to fetch.
   */
  where: Prisma.TempVoiceChannelsWhereUniqueInput
}

/**
 * TempVoiceChannels findFirst
 */
export type TempVoiceChannelsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceChannels to fetch.
   */
  where?: Prisma.TempVoiceChannelsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceChannelsOrderByWithRelationInput | Prisma.TempVoiceChannelsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoiceChannels.
   */
  cursor?: Prisma.TempVoiceChannelsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoiceChannels.
   */
  distinct?: Prisma.TempVoiceChannelsScalarFieldEnum | Prisma.TempVoiceChannelsScalarFieldEnum[]
}

/**
 * TempVoiceChannels findFirstOrThrow
 */
export type TempVoiceChannelsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceChannels to fetch.
   */
  where?: Prisma.TempVoiceChannelsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceChannelsOrderByWithRelationInput | Prisma.TempVoiceChannelsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoiceChannels.
   */
  cursor?: Prisma.TempVoiceChannelsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoiceChannels.
   */
  distinct?: Prisma.TempVoiceChannelsScalarFieldEnum | Prisma.TempVoiceChannelsScalarFieldEnum[]
}

/**
 * TempVoiceChannels findMany
 */
export type TempVoiceChannelsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsInclude<ExtArgs> | null
  /**
   * Filter, which TempVoiceChannels to fetch.
   */
  where?: Prisma.TempVoiceChannelsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoiceChannels to fetch.
   */
  orderBy?: Prisma.TempVoiceChannelsOrderByWithRelationInput | Prisma.TempVoiceChannelsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TempVoiceChannels.
   */
  cursor?: Prisma.TempVoiceChannelsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoiceChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoiceChannels.
   */
  skip?: number
  distinct?: Prisma.TempVoiceChannelsScalarFieldEnum | Prisma.TempVoiceChannelsScalarFieldEnum[]
}

/**
 * TempVoiceChannels create
 */
export type TempVoiceChannelsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsInclude<ExtArgs> | null
  /**
   * The data needed to create a TempVoiceChannels.
   */
  data: Prisma.XOR<Prisma.TempVoiceChannelsCreateInput, Prisma.TempVoiceChannelsUncheckedCreateInput>
}

/**
 * TempVoiceChannels createMany
 */
export type TempVoiceChannelsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TempVoiceChannels.
   */
  data: Prisma.TempVoiceChannelsCreateManyInput | Prisma.TempVoiceChannelsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TempVoiceChannels createManyAndReturn
 */
export type TempVoiceChannelsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * The data used to create many TempVoiceChannels.
   */
  data: Prisma.TempVoiceChannelsCreateManyInput | Prisma.TempVoiceChannelsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoiceChannels update
 */
export type TempVoiceChannelsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsInclude<ExtArgs> | null
  /**
   * The data needed to update a TempVoiceChannels.
   */
  data: Prisma.XOR<Prisma.TempVoiceChannelsUpdateInput, Prisma.TempVoiceChannelsUncheckedUpdateInput>
  /**
   * Choose, which TempVoiceChannels to update.
   */
  where: Prisma.TempVoiceChannelsWhereUniqueInput
}

/**
 * TempVoiceChannels updateMany
 */
export type TempVoiceChannelsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TempVoiceChannels.
   */
  data: Prisma.XOR<Prisma.TempVoiceChannelsUpdateManyMutationInput, Prisma.TempVoiceChannelsUncheckedUpdateManyInput>
  /**
   * Filter which TempVoiceChannels to update
   */
  where?: Prisma.TempVoiceChannelsWhereInput
  /**
   * Limit how many TempVoiceChannels to update.
   */
  limit?: number
}

/**
 * TempVoiceChannels updateManyAndReturn
 */
export type TempVoiceChannelsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * The data used to update TempVoiceChannels.
   */
  data: Prisma.XOR<Prisma.TempVoiceChannelsUpdateManyMutationInput, Prisma.TempVoiceChannelsUncheckedUpdateManyInput>
  /**
   * Filter which TempVoiceChannels to update
   */
  where?: Prisma.TempVoiceChannelsWhereInput
  /**
   * Limit how many TempVoiceChannels to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoiceChannels upsert
 */
export type TempVoiceChannelsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsInclude<ExtArgs> | null
  /**
   * The filter to search for the TempVoiceChannels to update in case it exists.
   */
  where: Prisma.TempVoiceChannelsWhereUniqueInput
  /**
   * In case the TempVoiceChannels found by the `where` argument doesn't exist, create a new TempVoiceChannels with this data.
   */
  create: Prisma.XOR<Prisma.TempVoiceChannelsCreateInput, Prisma.TempVoiceChannelsUncheckedCreateInput>
  /**
   * In case the TempVoiceChannels was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TempVoiceChannelsUpdateInput, Prisma.TempVoiceChannelsUncheckedUpdateInput>
}

/**
 * TempVoiceChannels delete
 */
export type TempVoiceChannelsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsInclude<ExtArgs> | null
  /**
   * Filter which TempVoiceChannels to delete.
   */
  where: Prisma.TempVoiceChannelsWhereUniqueInput
}

/**
 * TempVoiceChannels deleteMany
 */
export type TempVoiceChannelsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoiceChannels to delete
   */
  where?: Prisma.TempVoiceChannelsWhereInput
  /**
   * Limit how many TempVoiceChannels to delete.
   */
  limit?: number
}

/**
 * TempVoiceChannels.TempVoiceChannelMembers
 */
export type TempVoiceChannels$TempVoiceChannelMembersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannelMember
   */
  select?: Prisma.TempVoiceChannelMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannelMember
   */
  omit?: Prisma.TempVoiceChannelMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelMemberInclude<ExtArgs> | null
  where?: Prisma.TempVoiceChannelMemberWhereInput
}

/**
 * TempVoiceChannels without action
 */
export type TempVoiceChannelsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceChannels
   */
  select?: Prisma.TempVoiceChannelsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceChannels
   */
  omit?: Prisma.TempVoiceChannelsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceChannelsInclude<ExtArgs> | null
}
