
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TempVoice` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TempVoice
 * 
 */
export type TempVoiceModel = runtime.Types.Result.DefaultSelection<Prisma.$TempVoicePayload>

export type AggregateTempVoice = {
  _count: TempVoiceCountAggregateOutputType | null
  _avg: TempVoiceAvgAggregateOutputType | null
  _sum: TempVoiceSumAggregateOutputType | null
  _min: TempVoiceMinAggregateOutputType | null
  _max: TempVoiceMaxAggregateOutputType | null
}

export type TempVoiceAvgAggregateOutputType = {
  Id: number | null
}

export type TempVoiceSumAggregateOutputType = {
  Id: number | null
}

export type TempVoiceMinAggregateOutputType = {
  Id: number | null
  UserInviteMessageTemplateId: string | null
  TempVoiceLogChannelId: string | null
  GuildId: string | null
}

export type TempVoiceMaxAggregateOutputType = {
  Id: number | null
  UserInviteMessageTemplateId: string | null
  TempVoiceLogChannelId: string | null
  GuildId: string | null
}

export type TempVoiceCountAggregateOutputType = {
  Id: number
  UserInviteMessageTemplateId: number
  ModeratorUserIds: number
  TempVoiceLogChannelId: number
  GuildId: number
  _all: number
}


export type TempVoiceAvgAggregateInputType = {
  Id?: true
}

export type TempVoiceSumAggregateInputType = {
  Id?: true
}

export type TempVoiceMinAggregateInputType = {
  Id?: true
  UserInviteMessageTemplateId?: true
  TempVoiceLogChannelId?: true
  GuildId?: true
}

export type TempVoiceMaxAggregateInputType = {
  Id?: true
  UserInviteMessageTemplateId?: true
  TempVoiceLogChannelId?: true
  GuildId?: true
}

export type TempVoiceCountAggregateInputType = {
  Id?: true
  UserInviteMessageTemplateId?: true
  ModeratorUserIds?: true
  TempVoiceLogChannelId?: true
  GuildId?: true
  _all?: true
}

export type TempVoiceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoice to aggregate.
   */
  where?: Prisma.TempVoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoices to fetch.
   */
  orderBy?: Prisma.TempVoiceOrderByWithRelationInput | Prisma.TempVoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TempVoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TempVoices
  **/
  _count?: true | TempVoiceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TempVoiceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TempVoiceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TempVoiceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TempVoiceMaxAggregateInputType
}

export type GetTempVoiceAggregateType<T extends TempVoiceAggregateArgs> = {
      [P in keyof T & keyof AggregateTempVoice]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTempVoice[P]>
    : Prisma.GetScalarType<T[P], AggregateTempVoice[P]>
}




export type TempVoiceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempVoiceWhereInput
  orderBy?: Prisma.TempVoiceOrderByWithAggregationInput | Prisma.TempVoiceOrderByWithAggregationInput[]
  by: Prisma.TempVoiceScalarFieldEnum[] | Prisma.TempVoiceScalarFieldEnum
  having?: Prisma.TempVoiceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TempVoiceCountAggregateInputType | true
  _avg?: TempVoiceAvgAggregateInputType
  _sum?: TempVoiceSumAggregateInputType
  _min?: TempVoiceMinAggregateInputType
  _max?: TempVoiceMaxAggregateInputType
}

export type TempVoiceGroupByOutputType = {
  Id: number
  UserInviteMessageTemplateId: string | null
  ModeratorUserIds: string[]
  TempVoiceLogChannelId: string | null
  GuildId: string
  _count: TempVoiceCountAggregateOutputType | null
  _avg: TempVoiceAvgAggregateOutputType | null
  _sum: TempVoiceSumAggregateOutputType | null
  _min: TempVoiceMinAggregateOutputType | null
  _max: TempVoiceMaxAggregateOutputType | null
}

type GetTempVoiceGroupByPayload<T extends TempVoiceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TempVoiceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TempVoiceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TempVoiceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TempVoiceGroupByOutputType[P]>
      }
    >
  >



export type TempVoiceWhereInput = {
  AND?: Prisma.TempVoiceWhereInput | Prisma.TempVoiceWhereInput[]
  OR?: Prisma.TempVoiceWhereInput[]
  NOT?: Prisma.TempVoiceWhereInput | Prisma.TempVoiceWhereInput[]
  Id?: Prisma.IntFilter<"TempVoice"> | number
  UserInviteMessageTemplateId?: Prisma.StringNullableFilter<"TempVoice"> | string | null
  ModeratorUserIds?: Prisma.StringNullableListFilter<"TempVoice">
  TempVoiceLogChannelId?: Prisma.StringNullableFilter<"TempVoice"> | string | null
  GuildId?: Prisma.StringFilter<"TempVoice"> | string
  Guilds?: Prisma.XOR<Prisma.GuildsScalarRelationFilter, Prisma.GuildsWhereInput>
  TempVoiceConfigs?: Prisma.TempVoiceConfigListRelationFilter
  TempVoicePresets?: Prisma.TempVoicePresetListRelationFilter
}

export type TempVoiceOrderByWithRelationInput = {
  Id?: Prisma.SortOrder
  UserInviteMessageTemplateId?: Prisma.SortOrderInput | Prisma.SortOrder
  ModeratorUserIds?: Prisma.SortOrder
  TempVoiceLogChannelId?: Prisma.SortOrderInput | Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  Guilds?: Prisma.GuildsOrderByWithRelationInput
  TempVoiceConfigs?: Prisma.TempVoiceConfigOrderByRelationAggregateInput
  TempVoicePresets?: Prisma.TempVoicePresetOrderByRelationAggregateInput
}

export type TempVoiceWhereUniqueInput = Prisma.AtLeast<{
  Id?: number
  GuildId?: string
  AND?: Prisma.TempVoiceWhereInput | Prisma.TempVoiceWhereInput[]
  OR?: Prisma.TempVoiceWhereInput[]
  NOT?: Prisma.TempVoiceWhereInput | Prisma.TempVoiceWhereInput[]
  UserInviteMessageTemplateId?: Prisma.StringNullableFilter<"TempVoice"> | string | null
  ModeratorUserIds?: Prisma.StringNullableListFilter<"TempVoice">
  TempVoiceLogChannelId?: Prisma.StringNullableFilter<"TempVoice"> | string | null
  Guilds?: Prisma.XOR<Prisma.GuildsScalarRelationFilter, Prisma.GuildsWhereInput>
  TempVoiceConfigs?: Prisma.TempVoiceConfigListRelationFilter
  TempVoicePresets?: Prisma.TempVoicePresetListRelationFilter
}, "Id" | "GuildId">

export type TempVoiceOrderByWithAggregationInput = {
  Id?: Prisma.SortOrder
  UserInviteMessageTemplateId?: Prisma.SortOrderInput | Prisma.SortOrder
  ModeratorUserIds?: Prisma.SortOrder
  TempVoiceLogChannelId?: Prisma.SortOrderInput | Prisma.SortOrder
  GuildId?: Prisma.SortOrder
  _count?: Prisma.TempVoiceCountOrderByAggregateInput
  _avg?: Prisma.TempVoiceAvgOrderByAggregateInput
  _max?: Prisma.TempVoiceMaxOrderByAggregateInput
  _min?: Prisma.TempVoiceMinOrderByAggregateInput
  _sum?: Prisma.TempVoiceSumOrderByAggregateInput
}

export type TempVoiceScalarWhereWithAggregatesInput = {
  AND?: Prisma.TempVoiceScalarWhereWithAggregatesInput | Prisma.TempVoiceScalarWhereWithAggregatesInput[]
  OR?: Prisma.TempVoiceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TempVoiceScalarWhereWithAggregatesInput | Prisma.TempVoiceScalarWhereWithAggregatesInput[]
  Id?: Prisma.IntWithAggregatesFilter<"TempVoice"> | number
  UserInviteMessageTemplateId?: Prisma.StringNullableWithAggregatesFilter<"TempVoice"> | string | null
  ModeratorUserIds?: Prisma.StringNullableListFilter<"TempVoice">
  TempVoiceLogChannelId?: Prisma.StringNullableWithAggregatesFilter<"TempVoice"> | string | null
  GuildId?: Prisma.StringWithAggregatesFilter<"TempVoice"> | string
}

export type TempVoiceCreateInput = {
  UserInviteMessageTemplateId?: string | null
  ModeratorUserIds?: Prisma.TempVoiceCreateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: string | null
  Guilds: Prisma.GuildsCreateNestedOneWithoutTempVoicesInput
  TempVoiceConfigs?: Prisma.TempVoiceConfigCreateNestedManyWithoutTempVoiceInput
  TempVoicePresets?: Prisma.TempVoicePresetCreateNestedManyWithoutTempVoiceInput
}

export type TempVoiceUncheckedCreateInput = {
  Id?: number
  UserInviteMessageTemplateId?: string | null
  ModeratorUserIds?: Prisma.TempVoiceCreateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: string | null
  GuildId: string
  TempVoiceConfigs?: Prisma.TempVoiceConfigUncheckedCreateNestedManyWithoutTempVoiceInput
  TempVoicePresets?: Prisma.TempVoicePresetUncheckedCreateNestedManyWithoutTempVoiceInput
}

export type TempVoiceUpdateInput = {
  UserInviteMessageTemplateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ModeratorUserIds?: Prisma.TempVoiceUpdateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Guilds?: Prisma.GuildsUpdateOneRequiredWithoutTempVoicesNestedInput
  TempVoiceConfigs?: Prisma.TempVoiceConfigUpdateManyWithoutTempVoiceNestedInput
  TempVoicePresets?: Prisma.TempVoicePresetUpdateManyWithoutTempVoiceNestedInput
}

export type TempVoiceUncheckedUpdateInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UserInviteMessageTemplateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ModeratorUserIds?: Prisma.TempVoiceUpdateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  TempVoiceConfigs?: Prisma.TempVoiceConfigUncheckedUpdateManyWithoutTempVoiceNestedInput
  TempVoicePresets?: Prisma.TempVoicePresetUncheckedUpdateManyWithoutTempVoiceNestedInput
}

export type TempVoiceCreateManyInput = {
  Id?: number
  UserInviteMessageTemplateId?: string | null
  ModeratorUserIds?: Prisma.TempVoiceCreateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: string | null
  GuildId: string
}

export type TempVoiceUpdateManyMutationInput = {
  UserInviteMessageTemplateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ModeratorUserIds?: Prisma.TempVoiceUpdateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TempVoiceUncheckedUpdateManyInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UserInviteMessageTemplateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ModeratorUserIds?: Prisma.TempVoiceUpdateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TempVoiceNullableScalarRelationFilter = {
  is?: Prisma.TempVoiceWhereInput | null
  isNot?: Prisma.TempVoiceWhereInput | null
}

export type TempVoiceCountOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UserInviteMessageTemplateId?: Prisma.SortOrder
  ModeratorUserIds?: Prisma.SortOrder
  TempVoiceLogChannelId?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
}

export type TempVoiceAvgOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type TempVoiceMaxOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UserInviteMessageTemplateId?: Prisma.SortOrder
  TempVoiceLogChannelId?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
}

export type TempVoiceMinOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UserInviteMessageTemplateId?: Prisma.SortOrder
  TempVoiceLogChannelId?: Prisma.SortOrder
  GuildId?: Prisma.SortOrder
}

export type TempVoiceSumOrderByAggregateInput = {
  Id?: Prisma.SortOrder
}

export type TempVoiceScalarRelationFilter = {
  is?: Prisma.TempVoiceWhereInput
  isNot?: Prisma.TempVoiceWhereInput
}

export type TempVoiceCreateNestedOneWithoutGuildsInput = {
  create?: Prisma.XOR<Prisma.TempVoiceCreateWithoutGuildsInput, Prisma.TempVoiceUncheckedCreateWithoutGuildsInput>
  connectOrCreate?: Prisma.TempVoiceCreateOrConnectWithoutGuildsInput
  connect?: Prisma.TempVoiceWhereUniqueInput
}

export type TempVoiceUncheckedCreateNestedOneWithoutGuildsInput = {
  create?: Prisma.XOR<Prisma.TempVoiceCreateWithoutGuildsInput, Prisma.TempVoiceUncheckedCreateWithoutGuildsInput>
  connectOrCreate?: Prisma.TempVoiceCreateOrConnectWithoutGuildsInput
  connect?: Prisma.TempVoiceWhereUniqueInput
}

export type TempVoiceUpdateOneWithoutGuildsNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceCreateWithoutGuildsInput, Prisma.TempVoiceUncheckedCreateWithoutGuildsInput>
  connectOrCreate?: Prisma.TempVoiceCreateOrConnectWithoutGuildsInput
  upsert?: Prisma.TempVoiceUpsertWithoutGuildsInput
  disconnect?: Prisma.TempVoiceWhereInput | boolean
  delete?: Prisma.TempVoiceWhereInput | boolean
  connect?: Prisma.TempVoiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TempVoiceUpdateToOneWithWhereWithoutGuildsInput, Prisma.TempVoiceUpdateWithoutGuildsInput>, Prisma.TempVoiceUncheckedUpdateWithoutGuildsInput>
}

export type TempVoiceUncheckedUpdateOneWithoutGuildsNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceCreateWithoutGuildsInput, Prisma.TempVoiceUncheckedCreateWithoutGuildsInput>
  connectOrCreate?: Prisma.TempVoiceCreateOrConnectWithoutGuildsInput
  upsert?: Prisma.TempVoiceUpsertWithoutGuildsInput
  disconnect?: Prisma.TempVoiceWhereInput | boolean
  delete?: Prisma.TempVoiceWhereInput | boolean
  connect?: Prisma.TempVoiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TempVoiceUpdateToOneWithWhereWithoutGuildsInput, Prisma.TempVoiceUpdateWithoutGuildsInput>, Prisma.TempVoiceUncheckedUpdateWithoutGuildsInput>
}

export type TempVoiceCreateModeratorUserIdsInput = {
  set: string[]
}

export type TempVoiceUpdateModeratorUserIdsInput = {
  set?: string[]
  push?: string | string[]
}

export type TempVoiceCreateNestedOneWithoutTempVoiceConfigsInput = {
  create?: Prisma.XOR<Prisma.TempVoiceCreateWithoutTempVoiceConfigsInput, Prisma.TempVoiceUncheckedCreateWithoutTempVoiceConfigsInput>
  connectOrCreate?: Prisma.TempVoiceCreateOrConnectWithoutTempVoiceConfigsInput
  connect?: Prisma.TempVoiceWhereUniqueInput
}

export type TempVoiceUpdateOneRequiredWithoutTempVoiceConfigsNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceCreateWithoutTempVoiceConfigsInput, Prisma.TempVoiceUncheckedCreateWithoutTempVoiceConfigsInput>
  connectOrCreate?: Prisma.TempVoiceCreateOrConnectWithoutTempVoiceConfigsInput
  upsert?: Prisma.TempVoiceUpsertWithoutTempVoiceConfigsInput
  connect?: Prisma.TempVoiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TempVoiceUpdateToOneWithWhereWithoutTempVoiceConfigsInput, Prisma.TempVoiceUpdateWithoutTempVoiceConfigsInput>, Prisma.TempVoiceUncheckedUpdateWithoutTempVoiceConfigsInput>
}

export type TempVoiceCreateNestedOneWithoutTempVoicePresetsInput = {
  create?: Prisma.XOR<Prisma.TempVoiceCreateWithoutTempVoicePresetsInput, Prisma.TempVoiceUncheckedCreateWithoutTempVoicePresetsInput>
  connectOrCreate?: Prisma.TempVoiceCreateOrConnectWithoutTempVoicePresetsInput
  connect?: Prisma.TempVoiceWhereUniqueInput
}

export type TempVoiceUpdateOneRequiredWithoutTempVoicePresetsNestedInput = {
  create?: Prisma.XOR<Prisma.TempVoiceCreateWithoutTempVoicePresetsInput, Prisma.TempVoiceUncheckedCreateWithoutTempVoicePresetsInput>
  connectOrCreate?: Prisma.TempVoiceCreateOrConnectWithoutTempVoicePresetsInput
  upsert?: Prisma.TempVoiceUpsertWithoutTempVoicePresetsInput
  connect?: Prisma.TempVoiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TempVoiceUpdateToOneWithWhereWithoutTempVoicePresetsInput, Prisma.TempVoiceUpdateWithoutTempVoicePresetsInput>, Prisma.TempVoiceUncheckedUpdateWithoutTempVoicePresetsInput>
}

export type TempVoiceCreateWithoutGuildsInput = {
  UserInviteMessageTemplateId?: string | null
  ModeratorUserIds?: Prisma.TempVoiceCreateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: string | null
  TempVoiceConfigs?: Prisma.TempVoiceConfigCreateNestedManyWithoutTempVoiceInput
  TempVoicePresets?: Prisma.TempVoicePresetCreateNestedManyWithoutTempVoiceInput
}

export type TempVoiceUncheckedCreateWithoutGuildsInput = {
  Id?: number
  UserInviteMessageTemplateId?: string | null
  ModeratorUserIds?: Prisma.TempVoiceCreateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: string | null
  TempVoiceConfigs?: Prisma.TempVoiceConfigUncheckedCreateNestedManyWithoutTempVoiceInput
  TempVoicePresets?: Prisma.TempVoicePresetUncheckedCreateNestedManyWithoutTempVoiceInput
}

export type TempVoiceCreateOrConnectWithoutGuildsInput = {
  where: Prisma.TempVoiceWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceCreateWithoutGuildsInput, Prisma.TempVoiceUncheckedCreateWithoutGuildsInput>
}

export type TempVoiceUpsertWithoutGuildsInput = {
  update: Prisma.XOR<Prisma.TempVoiceUpdateWithoutGuildsInput, Prisma.TempVoiceUncheckedUpdateWithoutGuildsInput>
  create: Prisma.XOR<Prisma.TempVoiceCreateWithoutGuildsInput, Prisma.TempVoiceUncheckedCreateWithoutGuildsInput>
  where?: Prisma.TempVoiceWhereInput
}

export type TempVoiceUpdateToOneWithWhereWithoutGuildsInput = {
  where?: Prisma.TempVoiceWhereInput
  data: Prisma.XOR<Prisma.TempVoiceUpdateWithoutGuildsInput, Prisma.TempVoiceUncheckedUpdateWithoutGuildsInput>
}

export type TempVoiceUpdateWithoutGuildsInput = {
  UserInviteMessageTemplateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ModeratorUserIds?: Prisma.TempVoiceUpdateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  TempVoiceConfigs?: Prisma.TempVoiceConfigUpdateManyWithoutTempVoiceNestedInput
  TempVoicePresets?: Prisma.TempVoicePresetUpdateManyWithoutTempVoiceNestedInput
}

export type TempVoiceUncheckedUpdateWithoutGuildsInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UserInviteMessageTemplateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ModeratorUserIds?: Prisma.TempVoiceUpdateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  TempVoiceConfigs?: Prisma.TempVoiceConfigUncheckedUpdateManyWithoutTempVoiceNestedInput
  TempVoicePresets?: Prisma.TempVoicePresetUncheckedUpdateManyWithoutTempVoiceNestedInput
}

export type TempVoiceCreateWithoutTempVoiceConfigsInput = {
  UserInviteMessageTemplateId?: string | null
  ModeratorUserIds?: Prisma.TempVoiceCreateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: string | null
  Guilds: Prisma.GuildsCreateNestedOneWithoutTempVoicesInput
  TempVoicePresets?: Prisma.TempVoicePresetCreateNestedManyWithoutTempVoiceInput
}

export type TempVoiceUncheckedCreateWithoutTempVoiceConfigsInput = {
  Id?: number
  UserInviteMessageTemplateId?: string | null
  ModeratorUserIds?: Prisma.TempVoiceCreateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: string | null
  GuildId: string
  TempVoicePresets?: Prisma.TempVoicePresetUncheckedCreateNestedManyWithoutTempVoiceInput
}

export type TempVoiceCreateOrConnectWithoutTempVoiceConfigsInput = {
  where: Prisma.TempVoiceWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceCreateWithoutTempVoiceConfigsInput, Prisma.TempVoiceUncheckedCreateWithoutTempVoiceConfigsInput>
}

export type TempVoiceUpsertWithoutTempVoiceConfigsInput = {
  update: Prisma.XOR<Prisma.TempVoiceUpdateWithoutTempVoiceConfigsInput, Prisma.TempVoiceUncheckedUpdateWithoutTempVoiceConfigsInput>
  create: Prisma.XOR<Prisma.TempVoiceCreateWithoutTempVoiceConfigsInput, Prisma.TempVoiceUncheckedCreateWithoutTempVoiceConfigsInput>
  where?: Prisma.TempVoiceWhereInput
}

export type TempVoiceUpdateToOneWithWhereWithoutTempVoiceConfigsInput = {
  where?: Prisma.TempVoiceWhereInput
  data: Prisma.XOR<Prisma.TempVoiceUpdateWithoutTempVoiceConfigsInput, Prisma.TempVoiceUncheckedUpdateWithoutTempVoiceConfigsInput>
}

export type TempVoiceUpdateWithoutTempVoiceConfigsInput = {
  UserInviteMessageTemplateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ModeratorUserIds?: Prisma.TempVoiceUpdateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Guilds?: Prisma.GuildsUpdateOneRequiredWithoutTempVoicesNestedInput
  TempVoicePresets?: Prisma.TempVoicePresetUpdateManyWithoutTempVoiceNestedInput
}

export type TempVoiceUncheckedUpdateWithoutTempVoiceConfigsInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UserInviteMessageTemplateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ModeratorUserIds?: Prisma.TempVoiceUpdateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  TempVoicePresets?: Prisma.TempVoicePresetUncheckedUpdateManyWithoutTempVoiceNestedInput
}

export type TempVoiceCreateWithoutTempVoicePresetsInput = {
  UserInviteMessageTemplateId?: string | null
  ModeratorUserIds?: Prisma.TempVoiceCreateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: string | null
  Guilds: Prisma.GuildsCreateNestedOneWithoutTempVoicesInput
  TempVoiceConfigs?: Prisma.TempVoiceConfigCreateNestedManyWithoutTempVoiceInput
}

export type TempVoiceUncheckedCreateWithoutTempVoicePresetsInput = {
  Id?: number
  UserInviteMessageTemplateId?: string | null
  ModeratorUserIds?: Prisma.TempVoiceCreateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: string | null
  GuildId: string
  TempVoiceConfigs?: Prisma.TempVoiceConfigUncheckedCreateNestedManyWithoutTempVoiceInput
}

export type TempVoiceCreateOrConnectWithoutTempVoicePresetsInput = {
  where: Prisma.TempVoiceWhereUniqueInput
  create: Prisma.XOR<Prisma.TempVoiceCreateWithoutTempVoicePresetsInput, Prisma.TempVoiceUncheckedCreateWithoutTempVoicePresetsInput>
}

export type TempVoiceUpsertWithoutTempVoicePresetsInput = {
  update: Prisma.XOR<Prisma.TempVoiceUpdateWithoutTempVoicePresetsInput, Prisma.TempVoiceUncheckedUpdateWithoutTempVoicePresetsInput>
  create: Prisma.XOR<Prisma.TempVoiceCreateWithoutTempVoicePresetsInput, Prisma.TempVoiceUncheckedCreateWithoutTempVoicePresetsInput>
  where?: Prisma.TempVoiceWhereInput
}

export type TempVoiceUpdateToOneWithWhereWithoutTempVoicePresetsInput = {
  where?: Prisma.TempVoiceWhereInput
  data: Prisma.XOR<Prisma.TempVoiceUpdateWithoutTempVoicePresetsInput, Prisma.TempVoiceUncheckedUpdateWithoutTempVoicePresetsInput>
}

export type TempVoiceUpdateWithoutTempVoicePresetsInput = {
  UserInviteMessageTemplateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ModeratorUserIds?: Prisma.TempVoiceUpdateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Guilds?: Prisma.GuildsUpdateOneRequiredWithoutTempVoicesNestedInput
  TempVoiceConfigs?: Prisma.TempVoiceConfigUpdateManyWithoutTempVoiceNestedInput
}

export type TempVoiceUncheckedUpdateWithoutTempVoicePresetsInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UserInviteMessageTemplateId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ModeratorUserIds?: Prisma.TempVoiceUpdateModeratorUserIdsInput | string[]
  TempVoiceLogChannelId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  GuildId?: Prisma.StringFieldUpdateOperationsInput | string
  TempVoiceConfigs?: Prisma.TempVoiceConfigUncheckedUpdateManyWithoutTempVoiceNestedInput
}


/**
 * Count Type TempVoiceCountOutputType
 */

export type TempVoiceCountOutputType = {
  TempVoiceConfigs: number
  TempVoicePresets: number
}

export type TempVoiceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  TempVoiceConfigs?: boolean | TempVoiceCountOutputTypeCountTempVoiceConfigsArgs
  TempVoicePresets?: boolean | TempVoiceCountOutputTypeCountTempVoicePresetsArgs
}

/**
 * TempVoiceCountOutputType without action
 */
export type TempVoiceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceCountOutputType
   */
  select?: Prisma.TempVoiceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TempVoiceCountOutputType without action
 */
export type TempVoiceCountOutputTypeCountTempVoiceConfigsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempVoiceConfigWhereInput
}

/**
 * TempVoiceCountOutputType without action
 */
export type TempVoiceCountOutputTypeCountTempVoicePresetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TempVoicePresetWhereInput
}


export type TempVoiceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UserInviteMessageTemplateId?: boolean
  ModeratorUserIds?: boolean
  TempVoiceLogChannelId?: boolean
  GuildId?: boolean
  Guilds?: boolean | Prisma.GuildsDefaultArgs<ExtArgs>
  TempVoiceConfigs?: boolean | Prisma.TempVoice$TempVoiceConfigsArgs<ExtArgs>
  TempVoicePresets?: boolean | Prisma.TempVoice$TempVoicePresetsArgs<ExtArgs>
  _count?: boolean | Prisma.TempVoiceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoice"]>

export type TempVoiceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UserInviteMessageTemplateId?: boolean
  ModeratorUserIds?: boolean
  TempVoiceLogChannelId?: boolean
  GuildId?: boolean
  Guilds?: boolean | Prisma.GuildsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoice"]>

export type TempVoiceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UserInviteMessageTemplateId?: boolean
  ModeratorUserIds?: boolean
  TempVoiceLogChannelId?: boolean
  GuildId?: boolean
  Guilds?: boolean | Prisma.GuildsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tempVoice"]>

export type TempVoiceSelectScalar = {
  Id?: boolean
  UserInviteMessageTemplateId?: boolean
  ModeratorUserIds?: boolean
  TempVoiceLogChannelId?: boolean
  GuildId?: boolean
}

export type TempVoiceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Id" | "UserInviteMessageTemplateId" | "ModeratorUserIds" | "TempVoiceLogChannelId" | "GuildId", ExtArgs["result"]["tempVoice"]>
export type TempVoiceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Guilds?: boolean | Prisma.GuildsDefaultArgs<ExtArgs>
  TempVoiceConfigs?: boolean | Prisma.TempVoice$TempVoiceConfigsArgs<ExtArgs>
  TempVoicePresets?: boolean | Prisma.TempVoice$TempVoicePresetsArgs<ExtArgs>
  _count?: boolean | Prisma.TempVoiceCountOutputTypeDefaultArgs<ExtArgs>
}
export type TempVoiceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Guilds?: boolean | Prisma.GuildsDefaultArgs<ExtArgs>
}
export type TempVoiceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Guilds?: boolean | Prisma.GuildsDefaultArgs<ExtArgs>
}

export type $TempVoicePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TempVoice"
  objects: {
    Guilds: Prisma.$GuildsPayload<ExtArgs>
    TempVoiceConfigs: Prisma.$TempVoiceConfigPayload<ExtArgs>[]
    TempVoicePresets: Prisma.$TempVoicePresetPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Id: number
    UserInviteMessageTemplateId: string | null
    ModeratorUserIds: string[]
    TempVoiceLogChannelId: string | null
    GuildId: string
  }, ExtArgs["result"]["tempVoice"]>
  composites: {}
}

export type TempVoiceGetPayload<S extends boolean | null | undefined | TempVoiceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TempVoicePayload, S>

export type TempVoiceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TempVoiceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TempVoiceCountAggregateInputType | true
  }

export interface TempVoiceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TempVoice'], meta: { name: 'TempVoice' } }
  /**
   * Find zero or one TempVoice that matches the filter.
   * @param {TempVoiceFindUniqueArgs} args - Arguments to find a TempVoice
   * @example
   * // Get one TempVoice
   * const tempVoice = await prisma.tempVoice.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TempVoiceFindUniqueArgs>(args: Prisma.SelectSubset<T, TempVoiceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TempVoiceClient<runtime.Types.Result.GetResult<Prisma.$TempVoicePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TempVoice that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TempVoiceFindUniqueOrThrowArgs} args - Arguments to find a TempVoice
   * @example
   * // Get one TempVoice
   * const tempVoice = await prisma.tempVoice.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TempVoiceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TempVoiceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceClient<runtime.Types.Result.GetResult<Prisma.$TempVoicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoice that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceFindFirstArgs} args - Arguments to find a TempVoice
   * @example
   * // Get one TempVoice
   * const tempVoice = await prisma.tempVoice.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TempVoiceFindFirstArgs>(args?: Prisma.SelectSubset<T, TempVoiceFindFirstArgs<ExtArgs>>): Prisma.Prisma__TempVoiceClient<runtime.Types.Result.GetResult<Prisma.$TempVoicePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TempVoice that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceFindFirstOrThrowArgs} args - Arguments to find a TempVoice
   * @example
   * // Get one TempVoice
   * const tempVoice = await prisma.tempVoice.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TempVoiceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TempVoiceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TempVoiceClient<runtime.Types.Result.GetResult<Prisma.$TempVoicePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TempVoices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TempVoices
   * const tempVoices = await prisma.tempVoice.findMany()
   * 
   * // Get first 10 TempVoices
   * const tempVoices = await prisma.tempVoice.findMany({ take: 10 })
   * 
   * // Only select the `Id`
   * const tempVoiceWithIdOnly = await prisma.tempVoice.findMany({ select: { Id: true } })
   * 
   */
  findMany<T extends TempVoiceFindManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoicePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TempVoice.
   * @param {TempVoiceCreateArgs} args - Arguments to create a TempVoice.
   * @example
   * // Create one TempVoice
   * const TempVoice = await prisma.tempVoice.create({
   *   data: {
   *     // ... data to create a TempVoice
   *   }
   * })
   * 
   */
  create<T extends TempVoiceCreateArgs>(args: Prisma.SelectSubset<T, TempVoiceCreateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceClient<runtime.Types.Result.GetResult<Prisma.$TempVoicePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TempVoices.
   * @param {TempVoiceCreateManyArgs} args - Arguments to create many TempVoices.
   * @example
   * // Create many TempVoices
   * const tempVoice = await prisma.tempVoice.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TempVoiceCreateManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TempVoices and returns the data saved in the database.
   * @param {TempVoiceCreateManyAndReturnArgs} args - Arguments to create many TempVoices.
   * @example
   * // Create many TempVoices
   * const tempVoice = await prisma.tempVoice.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TempVoices and only return the `Id`
   * const tempVoiceWithIdOnly = await prisma.tempVoice.createManyAndReturn({
   *   select: { Id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TempVoiceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TempVoiceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoicePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TempVoice.
   * @param {TempVoiceDeleteArgs} args - Arguments to delete one TempVoice.
   * @example
   * // Delete one TempVoice
   * const TempVoice = await prisma.tempVoice.delete({
   *   where: {
   *     // ... filter to delete one TempVoice
   *   }
   * })
   * 
   */
  delete<T extends TempVoiceDeleteArgs>(args: Prisma.SelectSubset<T, TempVoiceDeleteArgs<ExtArgs>>): Prisma.Prisma__TempVoiceClient<runtime.Types.Result.GetResult<Prisma.$TempVoicePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TempVoice.
   * @param {TempVoiceUpdateArgs} args - Arguments to update one TempVoice.
   * @example
   * // Update one TempVoice
   * const tempVoice = await prisma.tempVoice.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TempVoiceUpdateArgs>(args: Prisma.SelectSubset<T, TempVoiceUpdateArgs<ExtArgs>>): Prisma.Prisma__TempVoiceClient<runtime.Types.Result.GetResult<Prisma.$TempVoicePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TempVoices.
   * @param {TempVoiceDeleteManyArgs} args - Arguments to filter TempVoices to delete.
   * @example
   * // Delete a few TempVoices
   * const { count } = await prisma.tempVoice.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TempVoiceDeleteManyArgs>(args?: Prisma.SelectSubset<T, TempVoiceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TempVoices
   * const tempVoice = await prisma.tempVoice.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TempVoiceUpdateManyArgs>(args: Prisma.SelectSubset<T, TempVoiceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TempVoices and returns the data updated in the database.
   * @param {TempVoiceUpdateManyAndReturnArgs} args - Arguments to update many TempVoices.
   * @example
   * // Update many TempVoices
   * const tempVoice = await prisma.tempVoice.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TempVoices and only return the `Id`
   * const tempVoiceWithIdOnly = await prisma.tempVoice.updateManyAndReturn({
   *   select: { Id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TempVoiceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TempVoiceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoicePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TempVoice.
   * @param {TempVoiceUpsertArgs} args - Arguments to update or create a TempVoice.
   * @example
   * // Update or create a TempVoice
   * const tempVoice = await prisma.tempVoice.upsert({
   *   create: {
   *     // ... data to create a TempVoice
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TempVoice we want to update
   *   }
   * })
   */
  upsert<T extends TempVoiceUpsertArgs>(args: Prisma.SelectSubset<T, TempVoiceUpsertArgs<ExtArgs>>): Prisma.Prisma__TempVoiceClient<runtime.Types.Result.GetResult<Prisma.$TempVoicePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TempVoices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceCountArgs} args - Arguments to filter TempVoices to count.
   * @example
   * // Count the number of TempVoices
   * const count = await prisma.tempVoice.count({
   *   where: {
   *     // ... the filter for the TempVoices we want to count
   *   }
   * })
  **/
  count<T extends TempVoiceCountArgs>(
    args?: Prisma.Subset<T, TempVoiceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TempVoiceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TempVoice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TempVoiceAggregateArgs>(args: Prisma.Subset<T, TempVoiceAggregateArgs>): Prisma.PrismaPromise<GetTempVoiceAggregateType<T>>

  /**
   * Group by TempVoice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TempVoiceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TempVoiceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TempVoiceGroupByArgs['orderBy'] }
      : { orderBy?: TempVoiceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TempVoiceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTempVoiceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TempVoice model
 */
readonly fields: TempVoiceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TempVoice.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TempVoiceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Guilds<T extends Prisma.GuildsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuildsDefaultArgs<ExtArgs>>): Prisma.Prisma__GuildsClient<runtime.Types.Result.GetResult<Prisma.$GuildsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  TempVoiceConfigs<T extends Prisma.TempVoice$TempVoiceConfigsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempVoice$TempVoiceConfigsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoiceConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  TempVoicePresets<T extends Prisma.TempVoice$TempVoicePresetsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TempVoice$TempVoicePresetsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TempVoicePresetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TempVoice model
 */
export interface TempVoiceFieldRefs {
  readonly Id: Prisma.FieldRef<"TempVoice", 'Int'>
  readonly UserInviteMessageTemplateId: Prisma.FieldRef<"TempVoice", 'String'>
  readonly ModeratorUserIds: Prisma.FieldRef<"TempVoice", 'String[]'>
  readonly TempVoiceLogChannelId: Prisma.FieldRef<"TempVoice", 'String'>
  readonly GuildId: Prisma.FieldRef<"TempVoice", 'String'>
}
    

// Custom InputTypes
/**
 * TempVoice findUnique
 */
export type TempVoiceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceInclude<ExtArgs> | null
  /**
   * Filter, which TempVoice to fetch.
   */
  where: Prisma.TempVoiceWhereUniqueInput
}

/**
 * TempVoice findUniqueOrThrow
 */
export type TempVoiceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceInclude<ExtArgs> | null
  /**
   * Filter, which TempVoice to fetch.
   */
  where: Prisma.TempVoiceWhereUniqueInput
}

/**
 * TempVoice findFirst
 */
export type TempVoiceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceInclude<ExtArgs> | null
  /**
   * Filter, which TempVoice to fetch.
   */
  where?: Prisma.TempVoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoices to fetch.
   */
  orderBy?: Prisma.TempVoiceOrderByWithRelationInput | Prisma.TempVoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoices.
   */
  cursor?: Prisma.TempVoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoices.
   */
  distinct?: Prisma.TempVoiceScalarFieldEnum | Prisma.TempVoiceScalarFieldEnum[]
}

/**
 * TempVoice findFirstOrThrow
 */
export type TempVoiceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceInclude<ExtArgs> | null
  /**
   * Filter, which TempVoice to fetch.
   */
  where?: Prisma.TempVoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoices to fetch.
   */
  orderBy?: Prisma.TempVoiceOrderByWithRelationInput | Prisma.TempVoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TempVoices.
   */
  cursor?: Prisma.TempVoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TempVoices.
   */
  distinct?: Prisma.TempVoiceScalarFieldEnum | Prisma.TempVoiceScalarFieldEnum[]
}

/**
 * TempVoice findMany
 */
export type TempVoiceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceInclude<ExtArgs> | null
  /**
   * Filter, which TempVoices to fetch.
   */
  where?: Prisma.TempVoiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TempVoices to fetch.
   */
  orderBy?: Prisma.TempVoiceOrderByWithRelationInput | Prisma.TempVoiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TempVoices.
   */
  cursor?: Prisma.TempVoiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TempVoices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TempVoices.
   */
  skip?: number
  distinct?: Prisma.TempVoiceScalarFieldEnum | Prisma.TempVoiceScalarFieldEnum[]
}

/**
 * TempVoice create
 */
export type TempVoiceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceInclude<ExtArgs> | null
  /**
   * The data needed to create a TempVoice.
   */
  data: Prisma.XOR<Prisma.TempVoiceCreateInput, Prisma.TempVoiceUncheckedCreateInput>
}

/**
 * TempVoice createMany
 */
export type TempVoiceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TempVoices.
   */
  data: Prisma.TempVoiceCreateManyInput | Prisma.TempVoiceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TempVoice createManyAndReturn
 */
export type TempVoiceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * The data used to create many TempVoices.
   */
  data: Prisma.TempVoiceCreateManyInput | Prisma.TempVoiceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoice update
 */
export type TempVoiceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceInclude<ExtArgs> | null
  /**
   * The data needed to update a TempVoice.
   */
  data: Prisma.XOR<Prisma.TempVoiceUpdateInput, Prisma.TempVoiceUncheckedUpdateInput>
  /**
   * Choose, which TempVoice to update.
   */
  where: Prisma.TempVoiceWhereUniqueInput
}

/**
 * TempVoice updateMany
 */
export type TempVoiceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TempVoices.
   */
  data: Prisma.XOR<Prisma.TempVoiceUpdateManyMutationInput, Prisma.TempVoiceUncheckedUpdateManyInput>
  /**
   * Filter which TempVoices to update
   */
  where?: Prisma.TempVoiceWhereInput
  /**
   * Limit how many TempVoices to update.
   */
  limit?: number
}

/**
 * TempVoice updateManyAndReturn
 */
export type TempVoiceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * The data used to update TempVoices.
   */
  data: Prisma.XOR<Prisma.TempVoiceUpdateManyMutationInput, Prisma.TempVoiceUncheckedUpdateManyInput>
  /**
   * Filter which TempVoices to update
   */
  where?: Prisma.TempVoiceWhereInput
  /**
   * Limit how many TempVoices to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TempVoice upsert
 */
export type TempVoiceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceInclude<ExtArgs> | null
  /**
   * The filter to search for the TempVoice to update in case it exists.
   */
  where: Prisma.TempVoiceWhereUniqueInput
  /**
   * In case the TempVoice found by the `where` argument doesn't exist, create a new TempVoice with this data.
   */
  create: Prisma.XOR<Prisma.TempVoiceCreateInput, Prisma.TempVoiceUncheckedCreateInput>
  /**
   * In case the TempVoice was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TempVoiceUpdateInput, Prisma.TempVoiceUncheckedUpdateInput>
}

/**
 * TempVoice delete
 */
export type TempVoiceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceInclude<ExtArgs> | null
  /**
   * Filter which TempVoice to delete.
   */
  where: Prisma.TempVoiceWhereUniqueInput
}

/**
 * TempVoice deleteMany
 */
export type TempVoiceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TempVoices to delete
   */
  where?: Prisma.TempVoiceWhereInput
  /**
   * Limit how many TempVoices to delete.
   */
  limit?: number
}

/**
 * TempVoice.TempVoiceConfigs
 */
export type TempVoice$TempVoiceConfigsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoiceConfig
   */
  select?: Prisma.TempVoiceConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoiceConfig
   */
  omit?: Prisma.TempVoiceConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceConfigInclude<ExtArgs> | null
  where?: Prisma.TempVoiceConfigWhereInput
  orderBy?: Prisma.TempVoiceConfigOrderByWithRelationInput | Prisma.TempVoiceConfigOrderByWithRelationInput[]
  cursor?: Prisma.TempVoiceConfigWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TempVoiceConfigScalarFieldEnum | Prisma.TempVoiceConfigScalarFieldEnum[]
}

/**
 * TempVoice.TempVoicePresets
 */
export type TempVoice$TempVoicePresetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoicePreset
   */
  select?: Prisma.TempVoicePresetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoicePreset
   */
  omit?: Prisma.TempVoicePresetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoicePresetInclude<ExtArgs> | null
  where?: Prisma.TempVoicePresetWhereInput
  orderBy?: Prisma.TempVoicePresetOrderByWithRelationInput | Prisma.TempVoicePresetOrderByWithRelationInput[]
  cursor?: Prisma.TempVoicePresetWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TempVoicePresetScalarFieldEnum | Prisma.TempVoicePresetScalarFieldEnum[]
}

/**
 * TempVoice without action
 */
export type TempVoiceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TempVoice
   */
  select?: Prisma.TempVoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TempVoice
   */
  omit?: Prisma.TempVoiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TempVoiceInclude<ExtArgs> | null
}
