
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TicketPermissions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TicketPermissions
 * 
 */
export type TicketPermissionsModel = runtime.Types.Result.DefaultSelection<Prisma.$TicketPermissionsPayload>

export type AggregateTicketPermissions = {
  _count: TicketPermissionsCountAggregateOutputType | null
  _avg: TicketPermissionsAvgAggregateOutputType | null
  _sum: TicketPermissionsSumAggregateOutputType | null
  _min: TicketPermissionsMinAggregateOutputType | null
  _max: TicketPermissionsMaxAggregateOutputType | null
}

export type TicketPermissionsAvgAggregateOutputType = {
  Id: number | null
  AllowedDiscordPermissions: number | null
  DeniedDiscordPermissions: number | null
}

export type TicketPermissionsSumAggregateOutputType = {
  Id: number | null
  AllowedDiscordPermissions: bigint | null
  DeniedDiscordPermissions: bigint | null
}

export type TicketPermissionsMinAggregateOutputType = {
  Id: number | null
  UUID: string | null
  DiscordUserId: string | null
  DiscordRoleId: string | null
  HasShadowPing: boolean | null
  IsHandler: boolean | null
  AllowedDiscordPermissions: bigint | null
  DeniedDiscordPermissions: bigint | null
  TicketSetupId: string | null
}

export type TicketPermissionsMaxAggregateOutputType = {
  Id: number | null
  UUID: string | null
  DiscordUserId: string | null
  DiscordRoleId: string | null
  HasShadowPing: boolean | null
  IsHandler: boolean | null
  AllowedDiscordPermissions: bigint | null
  DeniedDiscordPermissions: bigint | null
  TicketSetupId: string | null
}

export type TicketPermissionsCountAggregateOutputType = {
  Id: number
  UUID: number
  DiscordUserId: number
  DiscordRoleId: number
  HasShadowPing: number
  IsHandler: number
  TicketPermissions: number
  AllowedDiscordPermissions: number
  DeniedDiscordPermissions: number
  TicketSetupId: number
  _all: number
}


export type TicketPermissionsAvgAggregateInputType = {
  Id?: true
  AllowedDiscordPermissions?: true
  DeniedDiscordPermissions?: true
}

export type TicketPermissionsSumAggregateInputType = {
  Id?: true
  AllowedDiscordPermissions?: true
  DeniedDiscordPermissions?: true
}

export type TicketPermissionsMinAggregateInputType = {
  Id?: true
  UUID?: true
  DiscordUserId?: true
  DiscordRoleId?: true
  HasShadowPing?: true
  IsHandler?: true
  AllowedDiscordPermissions?: true
  DeniedDiscordPermissions?: true
  TicketSetupId?: true
}

export type TicketPermissionsMaxAggregateInputType = {
  Id?: true
  UUID?: true
  DiscordUserId?: true
  DiscordRoleId?: true
  HasShadowPing?: true
  IsHandler?: true
  AllowedDiscordPermissions?: true
  DeniedDiscordPermissions?: true
  TicketSetupId?: true
}

export type TicketPermissionsCountAggregateInputType = {
  Id?: true
  UUID?: true
  DiscordUserId?: true
  DiscordRoleId?: true
  HasShadowPing?: true
  IsHandler?: true
  TicketPermissions?: true
  AllowedDiscordPermissions?: true
  DeniedDiscordPermissions?: true
  TicketSetupId?: true
  _all?: true
}

export type TicketPermissionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketPermissions to aggregate.
   */
  where?: Prisma.TicketPermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketPermissions to fetch.
   */
  orderBy?: Prisma.TicketPermissionsOrderByWithRelationInput | Prisma.TicketPermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TicketPermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TicketPermissions
  **/
  _count?: true | TicketPermissionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TicketPermissionsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TicketPermissionsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TicketPermissionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TicketPermissionsMaxAggregateInputType
}

export type GetTicketPermissionsAggregateType<T extends TicketPermissionsAggregateArgs> = {
      [P in keyof T & keyof AggregateTicketPermissions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTicketPermissions[P]>
    : Prisma.GetScalarType<T[P], AggregateTicketPermissions[P]>
}




export type TicketPermissionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketPermissionsWhereInput
  orderBy?: Prisma.TicketPermissionsOrderByWithAggregationInput | Prisma.TicketPermissionsOrderByWithAggregationInput[]
  by: Prisma.TicketPermissionsScalarFieldEnum[] | Prisma.TicketPermissionsScalarFieldEnum
  having?: Prisma.TicketPermissionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TicketPermissionsCountAggregateInputType | true
  _avg?: TicketPermissionsAvgAggregateInputType
  _sum?: TicketPermissionsSumAggregateInputType
  _min?: TicketPermissionsMinAggregateInputType
  _max?: TicketPermissionsMaxAggregateInputType
}

export type TicketPermissionsGroupByOutputType = {
  Id: number
  UUID: string
  DiscordUserId: string | null
  DiscordRoleId: string | null
  HasShadowPing: boolean | null
  IsHandler: boolean
  TicketPermissions: string[]
  AllowedDiscordPermissions: bigint | null
  DeniedDiscordPermissions: bigint | null
  TicketSetupId: string
  _count: TicketPermissionsCountAggregateOutputType | null
  _avg: TicketPermissionsAvgAggregateOutputType | null
  _sum: TicketPermissionsSumAggregateOutputType | null
  _min: TicketPermissionsMinAggregateOutputType | null
  _max: TicketPermissionsMaxAggregateOutputType | null
}

type GetTicketPermissionsGroupByPayload<T extends TicketPermissionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TicketPermissionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TicketPermissionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TicketPermissionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TicketPermissionsGroupByOutputType[P]>
      }
    >
  >



export type TicketPermissionsWhereInput = {
  AND?: Prisma.TicketPermissionsWhereInput | Prisma.TicketPermissionsWhereInput[]
  OR?: Prisma.TicketPermissionsWhereInput[]
  NOT?: Prisma.TicketPermissionsWhereInput | Prisma.TicketPermissionsWhereInput[]
  Id?: Prisma.IntFilter<"TicketPermissions"> | number
  UUID?: Prisma.StringFilter<"TicketPermissions"> | string
  DiscordUserId?: Prisma.StringNullableFilter<"TicketPermissions"> | string | null
  DiscordRoleId?: Prisma.StringNullableFilter<"TicketPermissions"> | string | null
  HasShadowPing?: Prisma.BoolNullableFilter<"TicketPermissions"> | boolean | null
  IsHandler?: Prisma.BoolFilter<"TicketPermissions"> | boolean
  TicketPermissions?: Prisma.StringNullableListFilter<"TicketPermissions">
  AllowedDiscordPermissions?: Prisma.BigIntNullableFilter<"TicketPermissions"> | bigint | number | null
  DeniedDiscordPermissions?: Prisma.BigIntNullableFilter<"TicketPermissions"> | bigint | number | null
  TicketSetupId?: Prisma.StringFilter<"TicketPermissions"> | string
  TicketSetup?: Prisma.XOR<Prisma.TicketSetupsScalarRelationFilter, Prisma.TicketSetupsWhereInput>
}

export type TicketPermissionsOrderByWithRelationInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  DiscordUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  DiscordRoleId?: Prisma.SortOrderInput | Prisma.SortOrder
  HasShadowPing?: Prisma.SortOrderInput | Prisma.SortOrder
  IsHandler?: Prisma.SortOrder
  TicketPermissions?: Prisma.SortOrder
  AllowedDiscordPermissions?: Prisma.SortOrderInput | Prisma.SortOrder
  DeniedDiscordPermissions?: Prisma.SortOrderInput | Prisma.SortOrder
  TicketSetupId?: Prisma.SortOrder
  TicketSetup?: Prisma.TicketSetupsOrderByWithRelationInput
}

export type TicketPermissionsWhereUniqueInput = Prisma.AtLeast<{
  Id?: number
  UUID?: string
  AND?: Prisma.TicketPermissionsWhereInput | Prisma.TicketPermissionsWhereInput[]
  OR?: Prisma.TicketPermissionsWhereInput[]
  NOT?: Prisma.TicketPermissionsWhereInput | Prisma.TicketPermissionsWhereInput[]
  DiscordUserId?: Prisma.StringNullableFilter<"TicketPermissions"> | string | null
  DiscordRoleId?: Prisma.StringNullableFilter<"TicketPermissions"> | string | null
  HasShadowPing?: Prisma.BoolNullableFilter<"TicketPermissions"> | boolean | null
  IsHandler?: Prisma.BoolFilter<"TicketPermissions"> | boolean
  TicketPermissions?: Prisma.StringNullableListFilter<"TicketPermissions">
  AllowedDiscordPermissions?: Prisma.BigIntNullableFilter<"TicketPermissions"> | bigint | number | null
  DeniedDiscordPermissions?: Prisma.BigIntNullableFilter<"TicketPermissions"> | bigint | number | null
  TicketSetupId?: Prisma.StringFilter<"TicketPermissions"> | string
  TicketSetup?: Prisma.XOR<Prisma.TicketSetupsScalarRelationFilter, Prisma.TicketSetupsWhereInput>
}, "Id" | "UUID">

export type TicketPermissionsOrderByWithAggregationInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  DiscordUserId?: Prisma.SortOrderInput | Prisma.SortOrder
  DiscordRoleId?: Prisma.SortOrderInput | Prisma.SortOrder
  HasShadowPing?: Prisma.SortOrderInput | Prisma.SortOrder
  IsHandler?: Prisma.SortOrder
  TicketPermissions?: Prisma.SortOrder
  AllowedDiscordPermissions?: Prisma.SortOrderInput | Prisma.SortOrder
  DeniedDiscordPermissions?: Prisma.SortOrderInput | Prisma.SortOrder
  TicketSetupId?: Prisma.SortOrder
  _count?: Prisma.TicketPermissionsCountOrderByAggregateInput
  _avg?: Prisma.TicketPermissionsAvgOrderByAggregateInput
  _max?: Prisma.TicketPermissionsMaxOrderByAggregateInput
  _min?: Prisma.TicketPermissionsMinOrderByAggregateInput
  _sum?: Prisma.TicketPermissionsSumOrderByAggregateInput
}

export type TicketPermissionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TicketPermissionsScalarWhereWithAggregatesInput | Prisma.TicketPermissionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TicketPermissionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TicketPermissionsScalarWhereWithAggregatesInput | Prisma.TicketPermissionsScalarWhereWithAggregatesInput[]
  Id?: Prisma.IntWithAggregatesFilter<"TicketPermissions"> | number
  UUID?: Prisma.StringWithAggregatesFilter<"TicketPermissions"> | string
  DiscordUserId?: Prisma.StringNullableWithAggregatesFilter<"TicketPermissions"> | string | null
  DiscordRoleId?: Prisma.StringNullableWithAggregatesFilter<"TicketPermissions"> | string | null
  HasShadowPing?: Prisma.BoolNullableWithAggregatesFilter<"TicketPermissions"> | boolean | null
  IsHandler?: Prisma.BoolWithAggregatesFilter<"TicketPermissions"> | boolean
  TicketPermissions?: Prisma.StringNullableListFilter<"TicketPermissions">
  AllowedDiscordPermissions?: Prisma.BigIntNullableWithAggregatesFilter<"TicketPermissions"> | bigint | number | null
  DeniedDiscordPermissions?: Prisma.BigIntNullableWithAggregatesFilter<"TicketPermissions"> | bigint | number | null
  TicketSetupId?: Prisma.StringWithAggregatesFilter<"TicketPermissions"> | string
}

export type TicketPermissionsCreateInput = {
  UUID: string
  DiscordUserId?: string | null
  DiscordRoleId?: string | null
  HasShadowPing?: boolean | null
  IsHandler?: boolean
  TicketPermissions?: Prisma.TicketPermissionsCreateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: bigint | number | null
  DeniedDiscordPermissions?: bigint | number | null
  TicketSetup: Prisma.TicketSetupsCreateNestedOneWithoutTicketPermissionsInput
}

export type TicketPermissionsUncheckedCreateInput = {
  Id?: number
  UUID: string
  DiscordUserId?: string | null
  DiscordRoleId?: string | null
  HasShadowPing?: boolean | null
  IsHandler?: boolean
  TicketPermissions?: Prisma.TicketPermissionsCreateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: bigint | number | null
  DeniedDiscordPermissions?: bigint | number | null
  TicketSetupId: string
}

export type TicketPermissionsUpdateInput = {
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  DiscordUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  DiscordRoleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  HasShadowPing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  IsHandler?: Prisma.BoolFieldUpdateOperationsInput | boolean
  TicketPermissions?: Prisma.TicketPermissionsUpdateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  DeniedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  TicketSetup?: Prisma.TicketSetupsUpdateOneRequiredWithoutTicketPermissionsNestedInput
}

export type TicketPermissionsUncheckedUpdateInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  DiscordUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  DiscordRoleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  HasShadowPing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  IsHandler?: Prisma.BoolFieldUpdateOperationsInput | boolean
  TicketPermissions?: Prisma.TicketPermissionsUpdateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  DeniedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  TicketSetupId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketPermissionsCreateManyInput = {
  Id?: number
  UUID: string
  DiscordUserId?: string | null
  DiscordRoleId?: string | null
  HasShadowPing?: boolean | null
  IsHandler?: boolean
  TicketPermissions?: Prisma.TicketPermissionsCreateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: bigint | number | null
  DeniedDiscordPermissions?: bigint | number | null
  TicketSetupId: string
}

export type TicketPermissionsUpdateManyMutationInput = {
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  DiscordUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  DiscordRoleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  HasShadowPing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  IsHandler?: Prisma.BoolFieldUpdateOperationsInput | boolean
  TicketPermissions?: Prisma.TicketPermissionsUpdateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  DeniedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type TicketPermissionsUncheckedUpdateManyInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  DiscordUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  DiscordRoleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  HasShadowPing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  IsHandler?: Prisma.BoolFieldUpdateOperationsInput | boolean
  TicketPermissions?: Prisma.TicketPermissionsUpdateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  DeniedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  TicketSetupId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketPermissionsListRelationFilter = {
  every?: Prisma.TicketPermissionsWhereInput
  some?: Prisma.TicketPermissionsWhereInput
  none?: Prisma.TicketPermissionsWhereInput
}

export type TicketPermissionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TicketPermissionsCountOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  DiscordUserId?: Prisma.SortOrder
  DiscordRoleId?: Prisma.SortOrder
  HasShadowPing?: Prisma.SortOrder
  IsHandler?: Prisma.SortOrder
  TicketPermissions?: Prisma.SortOrder
  AllowedDiscordPermissions?: Prisma.SortOrder
  DeniedDiscordPermissions?: Prisma.SortOrder
  TicketSetupId?: Prisma.SortOrder
}

export type TicketPermissionsAvgOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  AllowedDiscordPermissions?: Prisma.SortOrder
  DeniedDiscordPermissions?: Prisma.SortOrder
}

export type TicketPermissionsMaxOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  DiscordUserId?: Prisma.SortOrder
  DiscordRoleId?: Prisma.SortOrder
  HasShadowPing?: Prisma.SortOrder
  IsHandler?: Prisma.SortOrder
  AllowedDiscordPermissions?: Prisma.SortOrder
  DeniedDiscordPermissions?: Prisma.SortOrder
  TicketSetupId?: Prisma.SortOrder
}

export type TicketPermissionsMinOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  UUID?: Prisma.SortOrder
  DiscordUserId?: Prisma.SortOrder
  DiscordRoleId?: Prisma.SortOrder
  HasShadowPing?: Prisma.SortOrder
  IsHandler?: Prisma.SortOrder
  AllowedDiscordPermissions?: Prisma.SortOrder
  DeniedDiscordPermissions?: Prisma.SortOrder
  TicketSetupId?: Prisma.SortOrder
}

export type TicketPermissionsSumOrderByAggregateInput = {
  Id?: Prisma.SortOrder
  AllowedDiscordPermissions?: Prisma.SortOrder
  DeniedDiscordPermissions?: Prisma.SortOrder
}

export type TicketPermissionsCreateNestedManyWithoutTicketSetupInput = {
  create?: Prisma.XOR<Prisma.TicketPermissionsCreateWithoutTicketSetupInput, Prisma.TicketPermissionsUncheckedCreateWithoutTicketSetupInput> | Prisma.TicketPermissionsCreateWithoutTicketSetupInput[] | Prisma.TicketPermissionsUncheckedCreateWithoutTicketSetupInput[]
  connectOrCreate?: Prisma.TicketPermissionsCreateOrConnectWithoutTicketSetupInput | Prisma.TicketPermissionsCreateOrConnectWithoutTicketSetupInput[]
  createMany?: Prisma.TicketPermissionsCreateManyTicketSetupInputEnvelope
  connect?: Prisma.TicketPermissionsWhereUniqueInput | Prisma.TicketPermissionsWhereUniqueInput[]
}

export type TicketPermissionsUncheckedCreateNestedManyWithoutTicketSetupInput = {
  create?: Prisma.XOR<Prisma.TicketPermissionsCreateWithoutTicketSetupInput, Prisma.TicketPermissionsUncheckedCreateWithoutTicketSetupInput> | Prisma.TicketPermissionsCreateWithoutTicketSetupInput[] | Prisma.TicketPermissionsUncheckedCreateWithoutTicketSetupInput[]
  connectOrCreate?: Prisma.TicketPermissionsCreateOrConnectWithoutTicketSetupInput | Prisma.TicketPermissionsCreateOrConnectWithoutTicketSetupInput[]
  createMany?: Prisma.TicketPermissionsCreateManyTicketSetupInputEnvelope
  connect?: Prisma.TicketPermissionsWhereUniqueInput | Prisma.TicketPermissionsWhereUniqueInput[]
}

export type TicketPermissionsUpdateManyWithoutTicketSetupNestedInput = {
  create?: Prisma.XOR<Prisma.TicketPermissionsCreateWithoutTicketSetupInput, Prisma.TicketPermissionsUncheckedCreateWithoutTicketSetupInput> | Prisma.TicketPermissionsCreateWithoutTicketSetupInput[] | Prisma.TicketPermissionsUncheckedCreateWithoutTicketSetupInput[]
  connectOrCreate?: Prisma.TicketPermissionsCreateOrConnectWithoutTicketSetupInput | Prisma.TicketPermissionsCreateOrConnectWithoutTicketSetupInput[]
  upsert?: Prisma.TicketPermissionsUpsertWithWhereUniqueWithoutTicketSetupInput | Prisma.TicketPermissionsUpsertWithWhereUniqueWithoutTicketSetupInput[]
  createMany?: Prisma.TicketPermissionsCreateManyTicketSetupInputEnvelope
  set?: Prisma.TicketPermissionsWhereUniqueInput | Prisma.TicketPermissionsWhereUniqueInput[]
  disconnect?: Prisma.TicketPermissionsWhereUniqueInput | Prisma.TicketPermissionsWhereUniqueInput[]
  delete?: Prisma.TicketPermissionsWhereUniqueInput | Prisma.TicketPermissionsWhereUniqueInput[]
  connect?: Prisma.TicketPermissionsWhereUniqueInput | Prisma.TicketPermissionsWhereUniqueInput[]
  update?: Prisma.TicketPermissionsUpdateWithWhereUniqueWithoutTicketSetupInput | Prisma.TicketPermissionsUpdateWithWhereUniqueWithoutTicketSetupInput[]
  updateMany?: Prisma.TicketPermissionsUpdateManyWithWhereWithoutTicketSetupInput | Prisma.TicketPermissionsUpdateManyWithWhereWithoutTicketSetupInput[]
  deleteMany?: Prisma.TicketPermissionsScalarWhereInput | Prisma.TicketPermissionsScalarWhereInput[]
}

export type TicketPermissionsUncheckedUpdateManyWithoutTicketSetupNestedInput = {
  create?: Prisma.XOR<Prisma.TicketPermissionsCreateWithoutTicketSetupInput, Prisma.TicketPermissionsUncheckedCreateWithoutTicketSetupInput> | Prisma.TicketPermissionsCreateWithoutTicketSetupInput[] | Prisma.TicketPermissionsUncheckedCreateWithoutTicketSetupInput[]
  connectOrCreate?: Prisma.TicketPermissionsCreateOrConnectWithoutTicketSetupInput | Prisma.TicketPermissionsCreateOrConnectWithoutTicketSetupInput[]
  upsert?: Prisma.TicketPermissionsUpsertWithWhereUniqueWithoutTicketSetupInput | Prisma.TicketPermissionsUpsertWithWhereUniqueWithoutTicketSetupInput[]
  createMany?: Prisma.TicketPermissionsCreateManyTicketSetupInputEnvelope
  set?: Prisma.TicketPermissionsWhereUniqueInput | Prisma.TicketPermissionsWhereUniqueInput[]
  disconnect?: Prisma.TicketPermissionsWhereUniqueInput | Prisma.TicketPermissionsWhereUniqueInput[]
  delete?: Prisma.TicketPermissionsWhereUniqueInput | Prisma.TicketPermissionsWhereUniqueInput[]
  connect?: Prisma.TicketPermissionsWhereUniqueInput | Prisma.TicketPermissionsWhereUniqueInput[]
  update?: Prisma.TicketPermissionsUpdateWithWhereUniqueWithoutTicketSetupInput | Prisma.TicketPermissionsUpdateWithWhereUniqueWithoutTicketSetupInput[]
  updateMany?: Prisma.TicketPermissionsUpdateManyWithWhereWithoutTicketSetupInput | Prisma.TicketPermissionsUpdateManyWithWhereWithoutTicketSetupInput[]
  deleteMany?: Prisma.TicketPermissionsScalarWhereInput | Prisma.TicketPermissionsScalarWhereInput[]
}

export type TicketPermissionsCreateTicketPermissionsInput = {
  set: string[]
}

export type TicketPermissionsUpdateTicketPermissionsInput = {
  set?: string[]
  push?: string | string[]
}

export type NullableBigIntFieldUpdateOperationsInput = {
  set?: bigint | number | null
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}

export type TicketPermissionsCreateWithoutTicketSetupInput = {
  UUID: string
  DiscordUserId?: string | null
  DiscordRoleId?: string | null
  HasShadowPing?: boolean | null
  IsHandler?: boolean
  TicketPermissions?: Prisma.TicketPermissionsCreateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: bigint | number | null
  DeniedDiscordPermissions?: bigint | number | null
}

export type TicketPermissionsUncheckedCreateWithoutTicketSetupInput = {
  Id?: number
  UUID: string
  DiscordUserId?: string | null
  DiscordRoleId?: string | null
  HasShadowPing?: boolean | null
  IsHandler?: boolean
  TicketPermissions?: Prisma.TicketPermissionsCreateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: bigint | number | null
  DeniedDiscordPermissions?: bigint | number | null
}

export type TicketPermissionsCreateOrConnectWithoutTicketSetupInput = {
  where: Prisma.TicketPermissionsWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketPermissionsCreateWithoutTicketSetupInput, Prisma.TicketPermissionsUncheckedCreateWithoutTicketSetupInput>
}

export type TicketPermissionsCreateManyTicketSetupInputEnvelope = {
  data: Prisma.TicketPermissionsCreateManyTicketSetupInput | Prisma.TicketPermissionsCreateManyTicketSetupInput[]
  skipDuplicates?: boolean
}

export type TicketPermissionsUpsertWithWhereUniqueWithoutTicketSetupInput = {
  where: Prisma.TicketPermissionsWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketPermissionsUpdateWithoutTicketSetupInput, Prisma.TicketPermissionsUncheckedUpdateWithoutTicketSetupInput>
  create: Prisma.XOR<Prisma.TicketPermissionsCreateWithoutTicketSetupInput, Prisma.TicketPermissionsUncheckedCreateWithoutTicketSetupInput>
}

export type TicketPermissionsUpdateWithWhereUniqueWithoutTicketSetupInput = {
  where: Prisma.TicketPermissionsWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketPermissionsUpdateWithoutTicketSetupInput, Prisma.TicketPermissionsUncheckedUpdateWithoutTicketSetupInput>
}

export type TicketPermissionsUpdateManyWithWhereWithoutTicketSetupInput = {
  where: Prisma.TicketPermissionsScalarWhereInput
  data: Prisma.XOR<Prisma.TicketPermissionsUpdateManyMutationInput, Prisma.TicketPermissionsUncheckedUpdateManyWithoutTicketSetupInput>
}

export type TicketPermissionsScalarWhereInput = {
  AND?: Prisma.TicketPermissionsScalarWhereInput | Prisma.TicketPermissionsScalarWhereInput[]
  OR?: Prisma.TicketPermissionsScalarWhereInput[]
  NOT?: Prisma.TicketPermissionsScalarWhereInput | Prisma.TicketPermissionsScalarWhereInput[]
  Id?: Prisma.IntFilter<"TicketPermissions"> | number
  UUID?: Prisma.StringFilter<"TicketPermissions"> | string
  DiscordUserId?: Prisma.StringNullableFilter<"TicketPermissions"> | string | null
  DiscordRoleId?: Prisma.StringNullableFilter<"TicketPermissions"> | string | null
  HasShadowPing?: Prisma.BoolNullableFilter<"TicketPermissions"> | boolean | null
  IsHandler?: Prisma.BoolFilter<"TicketPermissions"> | boolean
  TicketPermissions?: Prisma.StringNullableListFilter<"TicketPermissions">
  AllowedDiscordPermissions?: Prisma.BigIntNullableFilter<"TicketPermissions"> | bigint | number | null
  DeniedDiscordPermissions?: Prisma.BigIntNullableFilter<"TicketPermissions"> | bigint | number | null
  TicketSetupId?: Prisma.StringFilter<"TicketPermissions"> | string
}

export type TicketPermissionsCreateManyTicketSetupInput = {
  Id?: number
  UUID: string
  DiscordUserId?: string | null
  DiscordRoleId?: string | null
  HasShadowPing?: boolean | null
  IsHandler?: boolean
  TicketPermissions?: Prisma.TicketPermissionsCreateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: bigint | number | null
  DeniedDiscordPermissions?: bigint | number | null
}

export type TicketPermissionsUpdateWithoutTicketSetupInput = {
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  DiscordUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  DiscordRoleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  HasShadowPing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  IsHandler?: Prisma.BoolFieldUpdateOperationsInput | boolean
  TicketPermissions?: Prisma.TicketPermissionsUpdateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  DeniedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type TicketPermissionsUncheckedUpdateWithoutTicketSetupInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  DiscordUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  DiscordRoleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  HasShadowPing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  IsHandler?: Prisma.BoolFieldUpdateOperationsInput | boolean
  TicketPermissions?: Prisma.TicketPermissionsUpdateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  DeniedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}

export type TicketPermissionsUncheckedUpdateManyWithoutTicketSetupInput = {
  Id?: Prisma.IntFieldUpdateOperationsInput | number
  UUID?: Prisma.StringFieldUpdateOperationsInput | string
  DiscordUserId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  DiscordRoleId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  HasShadowPing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  IsHandler?: Prisma.BoolFieldUpdateOperationsInput | boolean
  TicketPermissions?: Prisma.TicketPermissionsUpdateTicketPermissionsInput | string[]
  AllowedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  DeniedDiscordPermissions?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
}



export type TicketPermissionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UUID?: boolean
  DiscordUserId?: boolean
  DiscordRoleId?: boolean
  HasShadowPing?: boolean
  IsHandler?: boolean
  TicketPermissions?: boolean
  AllowedDiscordPermissions?: boolean
  DeniedDiscordPermissions?: boolean
  TicketSetupId?: boolean
  TicketSetup?: boolean | Prisma.TicketSetupsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketPermissions"]>

export type TicketPermissionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UUID?: boolean
  DiscordUserId?: boolean
  DiscordRoleId?: boolean
  HasShadowPing?: boolean
  IsHandler?: boolean
  TicketPermissions?: boolean
  AllowedDiscordPermissions?: boolean
  DeniedDiscordPermissions?: boolean
  TicketSetupId?: boolean
  TicketSetup?: boolean | Prisma.TicketSetupsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketPermissions"]>

export type TicketPermissionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  Id?: boolean
  UUID?: boolean
  DiscordUserId?: boolean
  DiscordRoleId?: boolean
  HasShadowPing?: boolean
  IsHandler?: boolean
  TicketPermissions?: boolean
  AllowedDiscordPermissions?: boolean
  DeniedDiscordPermissions?: boolean
  TicketSetupId?: boolean
  TicketSetup?: boolean | Prisma.TicketSetupsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketPermissions"]>

export type TicketPermissionsSelectScalar = {
  Id?: boolean
  UUID?: boolean
  DiscordUserId?: boolean
  DiscordRoleId?: boolean
  HasShadowPing?: boolean
  IsHandler?: boolean
  TicketPermissions?: boolean
  AllowedDiscordPermissions?: boolean
  DeniedDiscordPermissions?: boolean
  TicketSetupId?: boolean
}

export type TicketPermissionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"Id" | "UUID" | "DiscordUserId" | "DiscordRoleId" | "HasShadowPing" | "IsHandler" | "TicketPermissions" | "AllowedDiscordPermissions" | "DeniedDiscordPermissions" | "TicketSetupId", ExtArgs["result"]["ticketPermissions"]>
export type TicketPermissionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  TicketSetup?: boolean | Prisma.TicketSetupsDefaultArgs<ExtArgs>
}
export type TicketPermissionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  TicketSetup?: boolean | Prisma.TicketSetupsDefaultArgs<ExtArgs>
}
export type TicketPermissionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  TicketSetup?: boolean | Prisma.TicketSetupsDefaultArgs<ExtArgs>
}

export type $TicketPermissionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TicketPermissions"
  objects: {
    TicketSetup: Prisma.$TicketSetupsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    Id: number
    UUID: string
    DiscordUserId: string | null
    DiscordRoleId: string | null
    HasShadowPing: boolean | null
    IsHandler: boolean
    TicketPermissions: string[]
    AllowedDiscordPermissions: bigint | null
    DeniedDiscordPermissions: bigint | null
    TicketSetupId: string
  }, ExtArgs["result"]["ticketPermissions"]>
  composites: {}
}

export type TicketPermissionsGetPayload<S extends boolean | null | undefined | TicketPermissionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload, S>

export type TicketPermissionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TicketPermissionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TicketPermissionsCountAggregateInputType | true
  }

export interface TicketPermissionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TicketPermissions'], meta: { name: 'TicketPermissions' } }
  /**
   * Find zero or one TicketPermissions that matches the filter.
   * @param {TicketPermissionsFindUniqueArgs} args - Arguments to find a TicketPermissions
   * @example
   * // Get one TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TicketPermissionsFindUniqueArgs>(args: Prisma.SelectSubset<T, TicketPermissionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TicketPermissionsClient<runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TicketPermissions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TicketPermissionsFindUniqueOrThrowArgs} args - Arguments to find a TicketPermissions
   * @example
   * // Get one TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TicketPermissionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TicketPermissionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketPermissionsClient<runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketPermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPermissionsFindFirstArgs} args - Arguments to find a TicketPermissions
   * @example
   * // Get one TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TicketPermissionsFindFirstArgs>(args?: Prisma.SelectSubset<T, TicketPermissionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TicketPermissionsClient<runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketPermissions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPermissionsFindFirstOrThrowArgs} args - Arguments to find a TicketPermissions
   * @example
   * // Get one TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TicketPermissionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TicketPermissionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketPermissionsClient<runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TicketPermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPermissionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.findMany()
   * 
   * // Get first 10 TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.findMany({ take: 10 })
   * 
   * // Only select the `Id`
   * const ticketPermissionsWithIdOnly = await prisma.ticketPermissions.findMany({ select: { Id: true } })
   * 
   */
  findMany<T extends TicketPermissionsFindManyArgs>(args?: Prisma.SelectSubset<T, TicketPermissionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TicketPermissions.
   * @param {TicketPermissionsCreateArgs} args - Arguments to create a TicketPermissions.
   * @example
   * // Create one TicketPermissions
   * const TicketPermissions = await prisma.ticketPermissions.create({
   *   data: {
   *     // ... data to create a TicketPermissions
   *   }
   * })
   * 
   */
  create<T extends TicketPermissionsCreateArgs>(args: Prisma.SelectSubset<T, TicketPermissionsCreateArgs<ExtArgs>>): Prisma.Prisma__TicketPermissionsClient<runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TicketPermissions.
   * @param {TicketPermissionsCreateManyArgs} args - Arguments to create many TicketPermissions.
   * @example
   * // Create many TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TicketPermissionsCreateManyArgs>(args?: Prisma.SelectSubset<T, TicketPermissionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TicketPermissions and returns the data saved in the database.
   * @param {TicketPermissionsCreateManyAndReturnArgs} args - Arguments to create many TicketPermissions.
   * @example
   * // Create many TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TicketPermissions and only return the `Id`
   * const ticketPermissionsWithIdOnly = await prisma.ticketPermissions.createManyAndReturn({
   *   select: { Id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TicketPermissionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TicketPermissionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TicketPermissions.
   * @param {TicketPermissionsDeleteArgs} args - Arguments to delete one TicketPermissions.
   * @example
   * // Delete one TicketPermissions
   * const TicketPermissions = await prisma.ticketPermissions.delete({
   *   where: {
   *     // ... filter to delete one TicketPermissions
   *   }
   * })
   * 
   */
  delete<T extends TicketPermissionsDeleteArgs>(args: Prisma.SelectSubset<T, TicketPermissionsDeleteArgs<ExtArgs>>): Prisma.Prisma__TicketPermissionsClient<runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TicketPermissions.
   * @param {TicketPermissionsUpdateArgs} args - Arguments to update one TicketPermissions.
   * @example
   * // Update one TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TicketPermissionsUpdateArgs>(args: Prisma.SelectSubset<T, TicketPermissionsUpdateArgs<ExtArgs>>): Prisma.Prisma__TicketPermissionsClient<runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TicketPermissions.
   * @param {TicketPermissionsDeleteManyArgs} args - Arguments to filter TicketPermissions to delete.
   * @example
   * // Delete a few TicketPermissions
   * const { count } = await prisma.ticketPermissions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TicketPermissionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TicketPermissionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TicketPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPermissionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TicketPermissionsUpdateManyArgs>(args: Prisma.SelectSubset<T, TicketPermissionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TicketPermissions and returns the data updated in the database.
   * @param {TicketPermissionsUpdateManyAndReturnArgs} args - Arguments to update many TicketPermissions.
   * @example
   * // Update many TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TicketPermissions and only return the `Id`
   * const ticketPermissionsWithIdOnly = await prisma.ticketPermissions.updateManyAndReturn({
   *   select: { Id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TicketPermissionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TicketPermissionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TicketPermissions.
   * @param {TicketPermissionsUpsertArgs} args - Arguments to update or create a TicketPermissions.
   * @example
   * // Update or create a TicketPermissions
   * const ticketPermissions = await prisma.ticketPermissions.upsert({
   *   create: {
   *     // ... data to create a TicketPermissions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TicketPermissions we want to update
   *   }
   * })
   */
  upsert<T extends TicketPermissionsUpsertArgs>(args: Prisma.SelectSubset<T, TicketPermissionsUpsertArgs<ExtArgs>>): Prisma.Prisma__TicketPermissionsClient<runtime.Types.Result.GetResult<Prisma.$TicketPermissionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TicketPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPermissionsCountArgs} args - Arguments to filter TicketPermissions to count.
   * @example
   * // Count the number of TicketPermissions
   * const count = await prisma.ticketPermissions.count({
   *   where: {
   *     // ... the filter for the TicketPermissions we want to count
   *   }
   * })
  **/
  count<T extends TicketPermissionsCountArgs>(
    args?: Prisma.Subset<T, TicketPermissionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TicketPermissionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TicketPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPermissionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TicketPermissionsAggregateArgs>(args: Prisma.Subset<T, TicketPermissionsAggregateArgs>): Prisma.PrismaPromise<GetTicketPermissionsAggregateType<T>>

  /**
   * Group by TicketPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketPermissionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TicketPermissionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TicketPermissionsGroupByArgs['orderBy'] }
      : { orderBy?: TicketPermissionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TicketPermissionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTicketPermissionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TicketPermissions model
 */
readonly fields: TicketPermissionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TicketPermissions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TicketPermissionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  TicketSetup<T extends Prisma.TicketSetupsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TicketSetupsDefaultArgs<ExtArgs>>): Prisma.Prisma__TicketSetupsClient<runtime.Types.Result.GetResult<Prisma.$TicketSetupsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TicketPermissions model
 */
export interface TicketPermissionsFieldRefs {
  readonly Id: Prisma.FieldRef<"TicketPermissions", 'Int'>
  readonly UUID: Prisma.FieldRef<"TicketPermissions", 'String'>
  readonly DiscordUserId: Prisma.FieldRef<"TicketPermissions", 'String'>
  readonly DiscordRoleId: Prisma.FieldRef<"TicketPermissions", 'String'>
  readonly HasShadowPing: Prisma.FieldRef<"TicketPermissions", 'Boolean'>
  readonly IsHandler: Prisma.FieldRef<"TicketPermissions", 'Boolean'>
  readonly TicketPermissions: Prisma.FieldRef<"TicketPermissions", 'String[]'>
  readonly AllowedDiscordPermissions: Prisma.FieldRef<"TicketPermissions", 'BigInt'>
  readonly DeniedDiscordPermissions: Prisma.FieldRef<"TicketPermissions", 'BigInt'>
  readonly TicketSetupId: Prisma.FieldRef<"TicketPermissions", 'String'>
}
    

// Custom InputTypes
/**
 * TicketPermissions findUnique
 */
export type TicketPermissionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsInclude<ExtArgs> | null
  /**
   * Filter, which TicketPermissions to fetch.
   */
  where: Prisma.TicketPermissionsWhereUniqueInput
}

/**
 * TicketPermissions findUniqueOrThrow
 */
export type TicketPermissionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsInclude<ExtArgs> | null
  /**
   * Filter, which TicketPermissions to fetch.
   */
  where: Prisma.TicketPermissionsWhereUniqueInput
}

/**
 * TicketPermissions findFirst
 */
export type TicketPermissionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsInclude<ExtArgs> | null
  /**
   * Filter, which TicketPermissions to fetch.
   */
  where?: Prisma.TicketPermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketPermissions to fetch.
   */
  orderBy?: Prisma.TicketPermissionsOrderByWithRelationInput | Prisma.TicketPermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketPermissions.
   */
  cursor?: Prisma.TicketPermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketPermissions.
   */
  distinct?: Prisma.TicketPermissionsScalarFieldEnum | Prisma.TicketPermissionsScalarFieldEnum[]
}

/**
 * TicketPermissions findFirstOrThrow
 */
export type TicketPermissionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsInclude<ExtArgs> | null
  /**
   * Filter, which TicketPermissions to fetch.
   */
  where?: Prisma.TicketPermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketPermissions to fetch.
   */
  orderBy?: Prisma.TicketPermissionsOrderByWithRelationInput | Prisma.TicketPermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketPermissions.
   */
  cursor?: Prisma.TicketPermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketPermissions.
   */
  distinct?: Prisma.TicketPermissionsScalarFieldEnum | Prisma.TicketPermissionsScalarFieldEnum[]
}

/**
 * TicketPermissions findMany
 */
export type TicketPermissionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsInclude<ExtArgs> | null
  /**
   * Filter, which TicketPermissions to fetch.
   */
  where?: Prisma.TicketPermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketPermissions to fetch.
   */
  orderBy?: Prisma.TicketPermissionsOrderByWithRelationInput | Prisma.TicketPermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TicketPermissions.
   */
  cursor?: Prisma.TicketPermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketPermissions.
   */
  skip?: number
  distinct?: Prisma.TicketPermissionsScalarFieldEnum | Prisma.TicketPermissionsScalarFieldEnum[]
}

/**
 * TicketPermissions create
 */
export type TicketPermissionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsInclude<ExtArgs> | null
  /**
   * The data needed to create a TicketPermissions.
   */
  data: Prisma.XOR<Prisma.TicketPermissionsCreateInput, Prisma.TicketPermissionsUncheckedCreateInput>
}

/**
 * TicketPermissions createMany
 */
export type TicketPermissionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TicketPermissions.
   */
  data: Prisma.TicketPermissionsCreateManyInput | Prisma.TicketPermissionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TicketPermissions createManyAndReturn
 */
export type TicketPermissionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * The data used to create many TicketPermissions.
   */
  data: Prisma.TicketPermissionsCreateManyInput | Prisma.TicketPermissionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TicketPermissions update
 */
export type TicketPermissionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsInclude<ExtArgs> | null
  /**
   * The data needed to update a TicketPermissions.
   */
  data: Prisma.XOR<Prisma.TicketPermissionsUpdateInput, Prisma.TicketPermissionsUncheckedUpdateInput>
  /**
   * Choose, which TicketPermissions to update.
   */
  where: Prisma.TicketPermissionsWhereUniqueInput
}

/**
 * TicketPermissions updateMany
 */
export type TicketPermissionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TicketPermissions.
   */
  data: Prisma.XOR<Prisma.TicketPermissionsUpdateManyMutationInput, Prisma.TicketPermissionsUncheckedUpdateManyInput>
  /**
   * Filter which TicketPermissions to update
   */
  where?: Prisma.TicketPermissionsWhereInput
  /**
   * Limit how many TicketPermissions to update.
   */
  limit?: number
}

/**
 * TicketPermissions updateManyAndReturn
 */
export type TicketPermissionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * The data used to update TicketPermissions.
   */
  data: Prisma.XOR<Prisma.TicketPermissionsUpdateManyMutationInput, Prisma.TicketPermissionsUncheckedUpdateManyInput>
  /**
   * Filter which TicketPermissions to update
   */
  where?: Prisma.TicketPermissionsWhereInput
  /**
   * Limit how many TicketPermissions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TicketPermissions upsert
 */
export type TicketPermissionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsInclude<ExtArgs> | null
  /**
   * The filter to search for the TicketPermissions to update in case it exists.
   */
  where: Prisma.TicketPermissionsWhereUniqueInput
  /**
   * In case the TicketPermissions found by the `where` argument doesn't exist, create a new TicketPermissions with this data.
   */
  create: Prisma.XOR<Prisma.TicketPermissionsCreateInput, Prisma.TicketPermissionsUncheckedCreateInput>
  /**
   * In case the TicketPermissions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TicketPermissionsUpdateInput, Prisma.TicketPermissionsUncheckedUpdateInput>
}

/**
 * TicketPermissions delete
 */
export type TicketPermissionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsInclude<ExtArgs> | null
  /**
   * Filter which TicketPermissions to delete.
   */
  where: Prisma.TicketPermissionsWhereUniqueInput
}

/**
 * TicketPermissions deleteMany
 */
export type TicketPermissionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketPermissions to delete
   */
  where?: Prisma.TicketPermissionsWhereInput
  /**
   * Limit how many TicketPermissions to delete.
   */
  limit?: number
}

/**
 * TicketPermissions without action
 */
export type TicketPermissionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketPermissions
   */
  select?: Prisma.TicketPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketPermissions
   */
  omit?: Prisma.TicketPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketPermissionsInclude<ExtArgs> | null
}
